### PR TITLE
SWATCH-1806: Update swatch-metrics clowdapp to use quarkus-based cmpt

### PR DESCRIPTION
**Pull request by Sgitario**
Jira issue: [SWATCH-1806](https://issues.redhat.com/browse/SWATCH-1806)

## Description
Update the build script to build the swatch-metrics image.
Then, do the switchover by replacing swatch-metrics/deploy/clowdapp.yaml with swatch-metrics/deploy/clowdapp_quarkus.yaml.

## Testing
This is meant only for QE. The existing tests are expected to fail because we're now deploying the swatch metrics app for Quarkus and the endpoints did change as follows:

| App  | Old  | New  |
|---|---|---|
| swatch-metrics | http://swatch-metrics-service:8000/api/rhsm-subscriptions |  http://swatch-metrics-service:8000/api/swatch-metrics |
| swatch-metrics-rhel | http://swatch-metrics-rhel-service:8000/api/rhsm-subscriptions |  http://swatch-metrics-rhel-service:8000/api/swatch-metrics |

### CODE REVIEW

**Comment by ntkathole** [comment]
I raised the QE side PR for changes - [smqe/smqe-tools/-/merge_requests/232](https://gitlab.cee.redhat.com/smqe/smqe-tools/-/merge_requests/232)  
Once this PR gets dev approval, I will merge it and re-run the tests here.

**Comment by Sgitario** [comment]
> I raised the QE side PR for changes - [smqe/smqe-tools/-/merge_requests/232](https://gitlab.cee.redhat.com/smqe/smqe-tools/-/merge_requests/232) Once this PR gets dev approval, I will merge it and re-run the tests here.

Thanks @ntkathole !

**Review by kflahert — APPROVED** [review]

**Review by ntkathole — APPROVED** [review]
Looks good

**Pull request merged**
