### PR TITLE
SWATCH-2523: Updates contract entity to join Offering entity

### PR DESCRIPTION
**Pull request by Sgitario**
Jira issue: SWATCH-2523

## Description
- Added join relationship between contract end offering entities.
- The API changed to remove the "product_id" field, and added the "product_tags" field that is an array of strings. 
- No more references to the contracts.product_id column in the ContractEntity

## Testing
IQE Test MR: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/712

## Verification
1.- podman-compose up
2.- start our API service:
```
SERVER_PORT=8101 DEV_MODE=true SPRING_PROFILES_ACTIVE=api,kafka-queue ./gradlew :bootRun
```
3.- add the ROSA offering:

```
INSERT INTO public.offering (sku, product_name, product_family, cores, sockets, hypervisor_cores, hypervisor_sockets, role, sla, usage, description, has_unlimited_usage, derived_sku,metered) 
VALUES ('RH00001', 'OpenShift Online', '', null, 5, null, null, 'moa-hostedcontrolplane', 'Premium', '', 'Red Hat OpenShift Dedicated on Customer Cloud Subscription (Hourly)', false, 'Article_1589801907847034','true');

INSERT INTO public.sku_product_tag  (sku, product_tag) 
VALUES ('RH00001', 'rosa');
```

4.- start the swatch-contracts service:

```
SUBSCRIPTION_URL=http://localhost:8102 QUARKUS_MANAGEMENT_PORT=9001 ./gradlew :swatch-contracts:quarkusDev
```

5.- create contract:

```
curl -v -X POST http://localhost:8000/api/swatch-contracts/internal/contracts \
-H 'Content-Type: application/json' \
--data-binary @- << EOF
{
  "partner_entitlement": {
        "rhAccountId": "123456",
        "sourcePartner": "aws_marketplace",
        "entitlementDates": {
          "startDate": "2023-05-24T18:46:05Z",
          "endDate": "2023-05-24T20:46:06.273014Z"
        },
        "rhEntitlements": [
          {
            "subscriptionNumber": "12585274",
            "sku": "RH00001"
          }
        ],
        "purchase": {
          "vendorProductCode": "AAAA",
          "contracts": [
            {
              "planId": "<only for azure>",
              "dimensions": [
                {
                  "name": "four_vcpu_hour",
                  "value": "8"
                }
              ]
            }
          ]
        },
        "partnerIdentities": {
          "awsCustomerId": "BBB",
          "sellerAccountId": "CCC",
          "customerAwsAccountId": "DDD"
        }
  },
  "subscription_id": "123456456"
}
EOF
```

Output:
```
{
  "status": {
    "status": "SUCCESS",
    "message": "New contract created"
  },
  "contract": {
    "uuid": "d0fcd58c-9e12-47b3-bff3-73414e69a547",
    "subscription_number": "12585274",
    "sku": "RH00001",
    "start_date": "2023-05-24T18:46:05Z",
    "end_date": "2023-05-24T20:46:06.273014Z",
    "org_id": "123456",
    "billing_provider": "aws",
    "billing_provider_id": "AAAA;BBB;CCC",
    "billing_account_id": "DDD",
    "product_tags": [
      "rosa"
    ],
    "vendor_product_code": "AAAA",
    "metrics": [
      {
        "metric_id": "four_vcpu_hour",
        "value": 8
      }
    ]
  }
}
```

Moreover, verify that the subscription is created with the expected product tags "rosa".

### CODE REVIEW

**Comment by kartikshahc** [comment]
> @kartikshahc I was a bit confused about the terms of product IDs and product tags. Assuming that product IDs is a list of integers to link the engineering IDs and product tags is a list of string to link the actual product tags based on our configuration. Originally, the contract entity has the column "product_id" which was really the product tag. Based on the above assumption, I linked the "offering.product_tags" instead of "offering.product_ids".
> 
> Moreover, I had to update the schema to make the existing product_tag to nullable as we are no longer updating it. And finally, I had to map the contract+offering entities to the contract API. I expect this to break some IQE tests.

yup that is correct. Offering.product_tags is the right replacement. I will check on all this scenarios next week.

**Review by Aurobinda55 — APPROVED** [review]

**Review by kartikshahc — APPROVED** [review]

**Pull request merged**
