### PR TITLE
Retain a year's worth of daily snapshots

### PR DESCRIPTION
**Pull request by awood**
Because of leap year, we would have needed to do at least 366, but I
like round numbers so I went with 370.  A little buffer might be helpful
anyway.

### CODE REVIEW

**Comment by awood** [comment]
TODO: Update internal documentation after this is merged: "Retention" on "Subscription Watch" page.

**Comment by awood** [comment]
@kahowell Do the Jenkins magic strings e.g. ("retest this please") work here?  I think the PR is fine but Jenkins went kaput and for some reason I can't restart it.

**Comment by awood** [comment]
retest this please

**Comment by kahowell** [comment]
@awood, for retest it's Details -> Login -> Re-run; however, we're in the middle of a Jenkins migration, so it might be best to start at the top level pipeline job (i.e. https://stage-jenkins-csb-smqe.cloud.paas.psi.redhat.com/job/Subscriptions%20PR%20Check/ and specifically choose the branch or PR and re-run that way).

**Pull request merged**
