### PR TITLE
SWATCH-1934: Remove InstanceReportSort enum

### PR DESCRIPTION
**Pull request by Sgitario**
Jira issue: [SWATCH-1934](https://issues.redhat.com/browse/SWATCH-1934)

## Description
My proposal here is to separate the map INSTANCE_SORT_PARAM_MAPPING into two collections:
- FIELD_SORT_PARAM_MAPPING: to map the instance fields to the actual columns
- METRICS_TO_SORT: auto-populated from metrics configuration at startup 

Then, in https://github.com/RedHatInsights/rhsm-subscriptions/compare/jcarvaja/SWATCH-1934?expand=1#diff-90f2fbedf15069ad6f8fa3491fd724676933889502bd4cab8bcf99a5c4010982R261 the logic to select the sort has changed to use one or the another. 

## Testing
No functional change here. Only regression testing.

### CODE REVIEW

**Review by lindseyburnett — APPROVED** [review]
Changes look good to me.  Want to run the change by QE though to make sure we're not inadvertently dropping any generated test cases that may have been tied to the enumeration options.

**Comment by Aurobinda55** [comment]
@Sgitario Changes look good to me and no test failures on EE. I have created a PR to modify the iqe api spec ((https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/539)) . You can merge the PR and I will run the regression once the codes are in stage.

**Review by Aurobinda55 — APPROVED** [review]

**Comment by Sgitario** [comment]
> @Sgitario Changes look good to me and no test failures on EE. I have created a PR to modify the iqe api spec ((https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/539)) . You can merge the PR and I will run the regression once the codes are in stage.

Many thanks!

**Pull request merged**
