### PR TITLE
SWATCH-2755 Enable wiremock for internal swatch contract url

### PR DESCRIPTION
**Pull request by kartikshahc**
Jira issue: SWATCH-2755

## Description

Enable wiremock proxy for swatch_contract from swatch_billable_usage
Also change the logic to make gratis identification a bit easier.
```
contract starting in Jan
billable usage in Jan -> gratis

'jan 2' != null && 'jan 2'.isAfter(startOfMonth('jan 4'))
-> true && 'jan 2'.isAfter('jan 1')
-> true && true

billable usage in Feb -> not
'jan 2' != null && 'jan 2'.isAfter(startOfMonth('feb 4'))
-> true && 'jan 2'.isAfter('feb 1')
-> true && false
-> false
```

## Testing

IQE Test MR: 
https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/843
https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/850
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/117912
https://github.com/RedHatInsights/wiremock-consoledot/pull/1

No test steps since the IQE covers a lot of it.

### Wiremock setup
The below will download the wiremock and will run on 8080 port
```
mkdir Programming
mkdir stub
podman run -it --rm  -p 8080:8080   --name wiremock  -v /home/karshah/Programming/stub:/home/wiremock:z wiremock/wiremock:3.9.1
%dev.SWATCH_CONTRACT_SERVICE_URL=http://localhost:8080
SERVER_PORT=8002 QUARKUS_MANAGEMENT_PORT=9002 DEV_MODE=true ./gradlew :swatch-billable-usage:quarkusDev
```

### Without wiremock
```
SERVER_PORT=8001 QUARKUS_MANAGEMENT_PORT=9001 ./gradlew :swatch-contracts:quarkusDev
%dev.SWATCH_CONTRACT_SERVICE_URL=http://localhost:8001
SERVER_PORT=8002 QUARKUS_MANAGEMENT_PORT=9002 DEV_MODE=true ./gradlew :swatch-billable-usage:quarkusDev
```

### CODE REVIEW

**Review by kflahert — APPROVED** [review]

**Comment by liwalker-rh** [comment]
As long as the failures in the most recent PR check have been addressed or are not related then I am good with merging this, especially since these IQE tests are all working.

**Review by liwalker-rh — APPROVED** [review]

**Review by kflahert — APPROVED** [review]

**Review by liwalker-rh — APPROVED** [review]
New changes lgtm!

**Pull request merged**
