### PR TITLE
SWATCH-2813: Use specific clientId's credential in swatch-producer-azure

### PR DESCRIPTION
**Pull request by Sgitario**
Jira issue: SWATCH-2813

## Description
As of ITPART-1180, the clientId associated to a given Azure subscription is available in the /partnerEntitlements response.
When swatch-producer-azure looks up azure usage context and the context includes a clientId value, it should immediately use the azure client configured with the value, and not loop through any other clientId's client instances.

## Testing
0.- Start postgres: `podman-compose up`
1.- Run data migrations: `./gradlew liquibaseUpdate`

And configure the BASILISK offering with an existing product tag:
```
insert into sku_product_tag values ('BASILISK', 'BASILISK');
```

2.- Start the contracts service: 
```
SWATCH_SELF_PSK=placeholder \
  ENTITLEMENT_GATEWAY_URL=http://localhost:8101/mock/partnerApi \
  SWATCH_INTERNAL_SUBSCRIPTION_ENDPOINT=http://localhost:8101/mock/internalSubs \
  SUBSCRIPTION_URL=http://localhost:8101/mock/subs \
  ./gradlew :swatch-contracts:quarkusDev
```

3. Start a wiremock instance: `podman run -it --rm  -p 8101:8080 --name wiremock wiremock/wiremock:2.32.0`
4. Mock the tags endpoint (simulating SKU being synced into swatch)

```shell
curl --data '{
  "priority": 2, "request": {
    "urlPath": "/mock/internalSubs/api/rhsm-subscriptions/v1/internal/offerings/BASILISK/product_tags",
    "method": "GET"
  },
  "response": {
    "status": 200,
    "jsonBody": {"data":["BASILISK"]},
    "headers":{"Content-Type":"application/json"}
  }
}' \
  http://localhost:8101/__admin/mappings/new
```

5. Mock the partner gateway endpoint for an azure subscription

```shell
curl --data '{
  "priority": 2, "request": {
    "urlPath": "/mock/partnerApi/v1/partnerSubscriptions",
    "method": "POST"
  },
  "response": {
    "status": 200,
    "jsonBody": {
       "content": [
           {
               "rhAccountId": "123456789",
               "sourcePartner": "azure_marketplace",
               "partnerIdentities": {
                   "azureSubscriptionId": "fa650050-dedd-4958-b901-d8e5118c0a5f",
                   "clientId": "64dc69e4-d083-49fc-9569-ebece1dd1408",
                   "azureCustomerId": "eadf26ee-6fbc-4295-9a9e-25d4fea8951d_2019-05-31"
               },
               "rhEntitlements": [
                   {
                       "sku": "BASILISK",
                       "subscriptionNumber": "123456"
                   }
               ],
               "purchase": {
                   "vendorProductCode": "rh-rhel-sub-preview",
                   "azureResourceId": "a69ff71c-aa8b-43d9-dea8-822fab4bbb86",
                   "contracts": [
                       {
                           "startDate": "2023-06-09T13:59:43.035365Z",
                           "planId": "rh-rhel-sub-1yr",
                           "dimensions": [
                               {
                                   "name": "vCPU",
                                   "value": 4
                               }
                           ]
                       }
                   ]
               },
               "status": "UNSUBSCRIBED",
               "entitlementDates": {
                   "startDate": "2023-06-09T13:59:43.035365Z",
                   "endDate": "2023-06-09T19:37:46.651363Z"
               }
           }
       ],
       "page": {
           "size": 0,
           "totalElements": 0,
           "totalPages": 0,
           "number": 0
       }
   },
    "headers":{"Content-Type":"application/json"}
  }
}' \
  http://localhost:8101/__admin/mappings/new
```

6. Mock the subscription service so that a subscriptionId can be fetched:

```shell
curl --data '{
  "priority": 2, "request": {
    "urlPath": "/mock/subs/search/criteria;subscription_number=123456/options;products=ALL;showExternalReferences=true/",
    "method": "GET"
  },
  "response": {
    "status": 200,
    "jsonBody": [{
        "id": 12345678,
        "webCustomerId": 123456789,
        "subscriptionNumber": "123456",
        "quantity": 10,
        "subscriptionProducts": null,
        "effectiveStartDate": 1672549200000,
        "effectiveEndDate": 1703998800000,
        "externalReferences": null
    }],
    "headers":{"Content-Type":"application/json"}
  }
}' \
  http://localhost:8101/__admin/mappings/new
```

7. Simulate an incoming partner contract message:

```shell
curl http://localhost:8000/api/swatch-contracts/internal/rpc/partner/contracts -d '{
  "action" : "contract-updated",
  "redHatSubscriptionNumber" : "123456",
  "currentDimensions" : [ {
    "dimensionName" : "vCPU",
    "dimensionValue" : "4",
    "expirationDate" : "2023-04-30T13:14:17.442176Z"
  } ],
  "cloudIdentifiers" : {
    "partner": "azure_marketplace",
    "azureResourceId" : "a69ff71c-aa8b-43d9-dea8-822fab4bbb86",
    "clientId" : "6a545474-5c90-11ee-96b2-8c8caa9b43f1",
    "offerId" : "azureProductCode",
    "planId": "rh-rhel-sub-1yr"
  }
}' -H 'Content-Type: application/json'
```

8. Stop swatch-contracts
9. Run the internal subscription service: `DEV_MODE=true ./gradlew :bootRun`
10. Check the azure context:

```shell
curl -X GET -H 'x-rh-swatch-psk:placeholder' -H 'Origin:console.redhat.com' "http://localhost:8000/api/rhsm-subscriptions/v1/internal/subscriptions/azureUsageContext?orgId=123456789&productId=BASILISK&date=2023-06-10T00:00Z&sla=Premium&usage=Production&billingAccountId=any" | jq
```

Observe that the response has the clientId populated.

Testing the azure producer
--------------------------

1.- Add mock definitions for the token endpoint and azure usage endpoint:

```shell
curl --data '{
  "priority": 2, "request": {
    "urlPath": "/mock/oauth/token",
    "method": "POST"
  },
  "response": {
    "status": 200,
    "jsonBody": {
       "token": "foo"
    },
    "headers":{"Content-Type":"application/json"}
  }
}' \
  http://localhost:8101/__admin/mappings/new

curl --data '{
  "priority": 2, "request": {
    "urlPattern": "/mock/azureMarketplace/api/usageEvent.*",
    "method": "POST"
  },
  "response": {
    "status": 200,
    "jsonBody": {
      "usageEventId": "a501667d-1c4d-4d7a-828f-af4cbbf53b3f",
      "status": "Accepted",
      "messageTime": "2020-01-12T13:19:35.3458658Z",
      "resourceId": "9501b697-8a4d-43bc-a13b-878bfb4ba3fe",
      "quantity": 5.0,
      "dimension": "dim1",
      "effectiveStartTime": "2018-12-01T08:30:14Z",
      "planId": "plan1"
    },
    "headers":{"Content-Type":"application/json"}
  }
}' \
  http://localhost:8101/__admin/mappings/new
```

2.- Deploy swatch-producer-azure on a different port and point it to the running swatch-subscription-sync service:

```shell
SERVER_PORT=8001 \
QUARKUS_MANAGEMENT_PORT=9001 \
WIREMOCK_HOSTNAME=localhost \
ENABLE_AZURE_DRY_RUN=false \
SWATCH_INTERNAL_SUBSCRIPTION_ENDPOINT=http://localhost:8000 \
QUARKUS_PROFILE=dev,wiremock \
./gradlew :swatch-producer-azure:quarkusDev
```

3.- Create the usage directly in database:

```
INSERT INTO billable_usage_remittance(uuid, org_id, product_id, metric_id, accumulation_period, sla, usage, billing_provider, billing_account_id, remittance_pending_date, retry_after, remitted_pending_value)
VALUES ('d125f119-0c98-43f2-a5de-ccf2e8e1ab55', '123456789', 'BASILISK', 'INSTANCE_HOURS', '2024-02', 'Premium', 'Production', 'azure', '123456', '2024-02-11T04:00:09.620406Z', '2023-12-11T04:00:09.620406Z', '4.0')
```

4.- Post some usage by sending message to the topic `platform.rhsm-subscriptions.billable-usage-hourly-aggregate`:

```
{"windowTimestamp":"2023-12-21T01:10:28Z","aggregateId": "e81bc918-6434-4a58-9192-8a8dd73ec8fb","aggregateKey": {"orgId": "123456789","billingProvider": "azure","metricId": "INSTANCE_HOURS","productId": "BASILISK"}, "remittanceUuids": ["d125f119-0c98-43f2-a5de-ccf2e8e1ab55"]}
```

```shell
curl 'http://localhost:8001/api/swatch-producer-azure/internal/azure/billable_usage' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
    "org_id":"123456789",
    "id":null,
    "billing_provider":"azure",
    "billing_account_id":"64dc69e4-d083-49fc-9569-ebece1dd1408",
    "snapshot_date":"2023-12-21T01:10:28Z",
    "product_id":"BASILISK",
    "sla":"Premium",
    "usage":"Production",
    "uom":"Storage-gibibyte-months",
    "value":42.0
  }'
```

Observe in swatch-producer-azure logs that there is a warning trace saying that the above client ID was not found:

```
2024-09-04 11:38:54,243 WARN  [com.red.swa.azu.ser.AzureMarketplaceService] (vert.x-worker-thread-1) The azure client ID '64dc69e4-d083-49fc-9569-ebece1dd1408' was not found. It will iterate over all the existing clients.
```

The existing client uses the client ID "test", so let's use it. 
First, we need to update the subscription billing provider ID:

```
UPDATE public."subscription"
SET billing_provider_id='a69ff71c-aa8b-43d9-dea8-822fab4bbb86;rh-rhel-sub-1yr;rh-rhel-sub-preview;eadf26ee-6fbc-4295-9a9e-25d4fea8951d_2019-05-31;test'
WHERE subscription_id='12345678'
```

And send again a new usage by repeating the step 4.

Now, the above warning trace should not be printed and the usage should have been sent as before.

### CODE REVIEW

**Comment by wottop** [comment]
lgtm

**Review by liwalker-rh — APPROVED** [review]
Looks good testing locally and in PR checks (failure in latest run is not related). There is some azure IQE testing with wiremock currently in progress that should help to cover any additional automation work for this.

**Pull request merged**
