### PR TITLE
Hot reload Quarkus code in ephemeral environments

### PR DESCRIPTION
**Pull request by awood**
Jira issue:  unofficial follow-up to SWATCH-1220

## Description

Swatchdog can now do hot deploys of our Quarkus apps.

### Setup
1. Install `poetry`: `sudo dnf install poetry`
2. Create and activate the poetry environment by running `poetry shell` in the top level of the repo.
3. Install the necessary dependencies with `poetry install`
4. Log in to the ephemeral openshift cluster.
5. Build the application containers.  You will need to do a rebuild because this feature required some changes in the underlying containers.  I **strongly** recommend you use the `bin/build-images.sh` script which will try to push the images to your personal `quay.io` space and tag them with the short hash of the current HEAD.
  It is **highly recommended**  to use the `bin/build-images.sh` script because that script correctly provides the podman build-args to instrument the Quarkus application JAR files.  If, for whatever reason, you don't want to use the script, you need to make sure that your podman builds add `--build-arg-file bin/dev-argfile.conf` to them.  You can look at the build-arg file, but it's purpose is to label the build artifact as a snapshot and to add the `-Dquarkus.package.type=mutable-jar` flag to the build.
7. Make sure the images that you pushed at the step 5 are public in Quay.io.
8. Run an EE deployment of those containers.  Here is the command I use for reference:
    ```
    VER=$(git rev-parse --short=7 HEAD) ;  bonfire deploy rhsm \
    --source=appsre \
    --ref-env insights-production \
    --optional-deps-method none \
    --frontends false \
    --timeout 1800 \
    -i quay.io/awood/swatch-metrics=$VER \
    -i quay.io/awood/rhsm-subscriptions=$VER \
    -i quay.io/awood/swatch-contracts=$VER \
    -i quay.io/awood/swatch-producer-aws=$VER \
    -i quay.io/awood/swatch-producer-azure=$VER \
    -i quay.io/awood/swatch-system-conduit=$VER \
    -p swatch-metrics/IMAGE=quay.io/awood/swatch-metrics \
    -p swatch-tally/IMAGE=quay.io/awood/rhsm-subscriptions \
    -p swatch-api/IMAGE=quay.io/awood/rhsm-subscriptions \
    -p swatch-contracts/IMAGE=quay.io/awood/swatch-contracts \
    -p swatch-producer-aws/IMAGE=quay.io/awood/swatch-producer-aws \
    -p swatch-producer-azure/IMAGE=quay.io/awood/swatch-producer-azure \
    -p swatch-system-conduit/IMAGE=quay.io/awood/rhsm-subscriptions \
    -p swatch-system-conduit/CONDUIT_IMAGE=quay.io/awood/swatch-system-conduit \
    -p swatch-producer-red-hat-marketplace/IMAGE=quay.io/awood/rhsm-subscriptions \
    -p swatch-subscription-sync/IMAGE=quay.io/awood/rhsm-subscriptions \
    -p swatch-api/JAVA_OPTS_APPEND=-Dspring.devtools.restart.enabled=true \
    -p swatch-contracts/QUARKUS_LAUNCH_DEVMODE=true \
    -p swatch-producer-aws/QUARKUS_LAUNCH_DEVMODE=true \
    -p swatch-producer-azure/QUARKUS_LAUNCH_DEVMODE=true \
    -p swatch-metrics/QUARKUS_LAUNCH_DEVMODE=true
    ```
    In the future, it will make sense to edit your `~/.config/bonfire/config.yaml` to set those last 5 parameters automatically, but for now, just set them on the `bonfire` command.

### Steps

1.  Make some trivial change to a Quarkus application.  The easiest thing to do is just add a `System.out.println("Hello world!")` as the first line in the `main` function in `com.redhat.swatch.contract.config.Main`.
1.  Run swatchdog
    ```
    poetry run swatchdog ee deploy
    ```
1. The script has an interactive mode where you pick the project to deploy.  Select `:swatch-contracts` (assuming that's the project you modified in step 1).  Then select the pod to deploy to.  You'll want to choose the `swatch-contracts-service` pod.  The interactive portions use [fzf](https://github.com/junegunn/fzf) so you can either type some of the name (fuzzy-matching is enabled) or just use the arrow keys.  There are also command line arguments so that in the future you don't have to do any interactive stuff at all (so long as the argument you entered is specific enough for there to only be one match).  E.g. `poetry run swatchdog ee deploy --pod-prefix 'swatch-contracts-service' --project swatch-contracts` will require no interaction.  But if you do `--project swatch`, you'll get dropped into fzf but with a more limited menu of matches
1. The script will recompile the Java classes and rsync the changes to the running pod.

### Verification

1. The application restarts and you'll see "Hello world!" on the pod's console.

### CODE REVIEW

**Review by Sgitario — CHANGES_REQUESTED** [review]
I followed all the steps and everything looks fine except for the bonfire deploy that failed because the "--no-remove-resources app:rhsm" was included. I continued the process with using `--no-remove-resources app:rhsm` and when syncing the contract service, the pod didn't restart. I tried to manually restart it, but still the "Hello World" message is missing.
All the poetry commands I tried worked fine with no errors.

**Comment by awood** [comment]
> I followed all the steps and everything looks fine except for the bonfire deploy that failed because the "--no-remove-resources app:rhsm" was included. I continued the process with using `--no-remove-resources app:rhsm` and when syncing the contract service, the pod didn't restart. I tried to manually restart it, but still the "Hello World" message is missing.

The pod should not actually restart.  In fact, if you restart the pod, the changed code that you uploaded will vanish since you're restarting from the built image.  I realize that my verification instructions were incorrect.  I'll correct them in the PR description, but basically after you run `ee deploy`, you should see the *application* restart and "Hello world" get printed to the screen.

**Comment by Sgitario** [comment]
> > I followed all the steps and everything looks fine except for the bonfire deploy that failed because the "--no-remove-resources app:rhsm" was included. I continued the process with using `--no-remove-resources app:rhsm` and when syncing the contract service, the pod didn't restart. I tried to manually restart it, but still the "Hello World" message is missing.
> 
> The pod should not actually restart. In fact, if you restart the pod, the changed code that you uploaded will vanish since you're restarting from the built image. I realize that my verification instructions were incorrect. I'll correct them in the PR description, but basically after you run `ee deploy`, you should see the _application_ restart and "Hello world" get printed to the screen.

Still this is not working for me: I'm not seeing any "Hello world" text after the `ee deploy`. 
I've checked the environment variables of the POD, and I don't see the `QUARKUS_LAUNCH_DEVMODE` one. 
Perhaps, do you use a custom `~/.config/bonfire/config.yaml` file to point out to your local clowdapp files? If so, can you share it here or as part of the steps. Otherwise, I don't understand how it can work.

**Comment by awood** [comment]
> Still this is not working for me: I'm not seeing any "Hello world" text after the `ee deploy`.
> I've checked the environment variables of the POD, and I don't see the `QUARKUS_LAUNCH_DEVMODE` one.
> Perhaps, do you use a custom `~/.config/bonfire/config.yaml` file to point out to your local clowdapp files? If so, can you share it here or as part of the steps. Otherwise, I don't understand how it can work.

It's part of the bonfire command in step 7 of the setup.  It's passed in as a template variable (`-p swatch-contracts/QUARKUS_LAUNCH_DEVMODE=true`).  Which then shows up in the environment via [this part](https://github.com/RedHatInsights/rhsm-subscriptions/blob/awood/swatchdog/swatch-contracts/deploy/clowdapp.yaml#L121-L122) of the `clowapp.yaml`.

Are you running a different bonfire command?  Or maybe you can check your pod's YAML to see if `QUARKUS_LAUNCH_DEVMODE` is present at all?  It sounds like it wasn't, so maybe see if the `swatch-metrics/deploy/clowdapp.yaml` in your branch has that parameter defined?

**Comment by Sgitario** [comment]
> > Still this is not working for me: I'm not seeing any "Hello world" text after the `ee deploy`.
> > I've checked the environment variables of the POD, and I don't see the `QUARKUS_LAUNCH_DEVMODE` one.
> > Perhaps, do you use a custom `~/.config/bonfire/config.yaml` file to point out to your local clowdapp files? If so, can you share it here or as part of the steps. Otherwise, I don't understand how it can work.
> 
> It's part of the bonfire command in step 7 of the setup. It's passed in as a template variable (`-p swatch-contracts/QUARKUS_LAUNCH_DEVMODE=true`). Which then shows up in the environment via [this part](https://github.com/RedHatInsights/rhsm-subscriptions/blob/awood/swatchdog/swatch-contracts/deploy/clowdapp.yaml#L121-L122) of the `clowapp.yaml`.
> 
> Are you running a different bonfire command? Or maybe you can check your pod's YAML to see if `QUARKUS_LAUNCH_DEVMODE` is present at all? It sounds like it wasn't, so maybe see if the `swatch-metrics/deploy/clowdapp.yaml` in your branch has that parameter defined?

The QUARKUS_LAUNCH_DEVMODE was not present at all.
I'm using your branch.

**Comment by awood** [comment]
> The QUARKUS_LAUNCH_DEVMODE was not present at all.
> I'm using your branch.

So the template parameter is there in the clowdapp.yaml for swatch-contracts.  How are you doing your bonfire deployment?  I think that's where the disconnect is because that template parameter isn't getting set.  It may be worth releasing the namespace you have an reserving another one.  I have seen in the past bonfire commands not actually refreshing the pods.

**Comment by Sgitario** [comment]
> > The QUARKUS_LAUNCH_DEVMODE was not present at all.
> > I'm using your branch.
> 
> So the template parameter is there in the clowdapp.yaml for swatch-contracts. How are you doing your bonfire deployment? I think that's where the disconnect is because that template parameter isn't getting set. It may be worth releasing the namespace you have an reserving another one. I have seen in the past bonfire commands not actually refreshing the pods.

I copied the bonfire command you shared but using my quay username:

```
VER=$(git rev-parse --short=7 HEAD) ;  bonfire deploy rhsm \
--source=appsre \
--ref-env insights-production \
--optional-deps-method none \
--frontends false \
--timeout 1800 \
-i quay.io/jcarvaja/swatch-metrics=$VER \
-i quay.io/jcarvaja/rhsm-subscriptions=$VER \
-i quay.io/jcarvaja/swatch-contracts=$VER \
-i quay.io/jcarvaja/swatch-producer-aws=$VER \
-i quay.io/jcarvaja/swatch-producer-azure=$VER \
-i quay.io/jcarvaja/swatch-system-conduit=$VER \
-p swatch-metrics/IMAGE=quay.io/jcarvaja/swatch-metrics \
-p swatch-tally/IMAGE=quay.io/jcarvaja/rhsm-subscriptions \
-p swatch-api/IMAGE=quay.io/jcarvaja/rhsm-subscriptions \
-p swatch-contracts/IMAGE=quay.io/jcarvaja/swatch-contracts \
-p swatch-producer-aws/IMAGE=quay.io/jcarvaja/swatch-producer-aws \
-p swatch-producer-azure/IMAGE=quay.io/jcarvaja/swatch-producer-azure \
-p swatch-system-conduit/IMAGE=quay.io/jcarvaja/rhsm-subscriptions \
-p swatch-system-conduit/CONDUIT_IMAGE=quay.io/jcarvaja/swatch-system-conduit \
-p swatch-producer-red-hat-marketplace/IMAGE=quay.io/jcarvaja/rhsm-subscriptions \
-p swatch-subscription-sync/IMAGE=quay.io/jcarvaja/rhsm-subscriptions \
-p swatch-api/JAVA_OPTS_APPEND=-Dspring.devtools.restart.enabled=true \
-p swatch-contracts/QUARKUS_LAUNCH_DEVMODE=true \
-p swatch-producer-aws/QUARKUS_LAUNCH_DEVMODE=true \
-p swatch-producer-azure/QUARKUS_LAUNCH_DEVMODE=true \
-p swatch-metrics/QUARKUS_LAUNCH_DEVMODE=true
```

I think it's worthy to either have a call to run the steps (I'm fine to do it tomorrow at your time) or let somebody else in the team to try it out (maybe it's something related to my setup).

**Comment by lindseyburnett** [comment]
THIS IS AWESOME

image

image

**Review by lindseyburnett — APPROVED** [review]

**Review by Sgitario — APPROVED** [review]
Approving according to the Lindsey's feedback

**Pull request merged**
