### PR TITLE
SWATCH-2756: Product configuration for rhel-aus-addon

### PR DESCRIPTION
**Pull request by wottop**
Jira issue: SWATCH-2756

## Description

Adding product configuration to the tally

### Setup

1. Setup wiremock or hit against product service 
2. Sync SKU:
```http PUT :8882/api/swatch-contracts/internal/rpc/offerings/sync/MCT2342```
3. Check for the offering:
```http GET :8882/api/swatch-contracts/internal/offerings/MCT2342/product_tags```
4. Import data from HBI:
``import-from-gabi.py --hbi --org-id='xxxxxxx'
5. Keep only the data for one host [just for ease of use]
6. Change the RH_PROD value to '251'

### Steps

1. Run a nightly tally:
```http PUT ":8000/api/rhsm-subscriptions/v1/internal/rpc/tally/snapshots/xxxxxxx" x-rh-swatch-psk:placeholder```

### Verification

1. You should see the tally entries in the appropriate tables.

### CODE REVIEW

**Review by kahowell — CHANGES_REQUESTED** [review]
Can you please update the `SubscriptionDefinitionRegistryTest.testLoadAllTheThings` test to simply assert `subscriptionDefinitionRegistry.getSubscriptions()` is not empty?

**Review by kahowell — APPROVED** [review]

**Review by liwalker-rh — APPROVED** [review]
Testing locally by syncing offerings by this sku results in correct sku_product_tag table mapping. Also, usage contributes to the applicable product tag based on using this eng id.

**Pull request merged**
