### PR TITLE
SWATCH-2226 syncContractByOrgId should sync all contracts

### PR DESCRIPTION
**Pull request by kartikshahc**
Jira issue: SWATCH-2226

## Description

**Note: Please only run `syncContractsByOrg` endpoint since we want to only run by org first and make sure the sync and its results are okay on prod.** 

### ${{\color{Red}\Huge{\textsf{ Don't run the syncAllContracts until QE validates this in prod.}}}}\$

- [ ] We have to cleanup old contracts because they had empty billing_provider_id hence when we sync the contract it thinks that it is a new contract. Hence we are deleting any active contracts or has empty billing provider for a given org.
- [ ] We are calling Partner gateway for a given org and updating contracts and subscription.

## Testing

It is best to directly to connect with prod and modify some of these data to test against prod. However I will be doing my best to put some wiremock based steps but, reviewer has to be innovative to test it with mocking.

### Setup test data with prod like current scenario

**offering:**
`INSERT INTO public.offering (sku, product_name, product_family, cores, sockets, hypervisor_cores, hypervisor_sockets, role, sla, usage, description, has_unlimited_usage, derived_sku, metered) VALUES ('MW02393', 'OpenShift Online', 'OpenShift Enterprise', null, null, null, null, '', 'Premium', '', 'Red Hat OpenShift Service on AWS Hosted Control Planes (Hourly)', false, '', true);
`

**org_config:**
`INSERT INTO public.org_config (org_id, opt_in_type, created, updated) VALUES ('3949694', 'DB', '2020-04-14 20:31:41.660008 +00:00', '2023-05-22 08:30:04.560645 +00:00');`

**contracts:**
```
INSERT INTO public.contracts (uuid, subscription_number, last_updated, start_date, end_date, org_id, sku, billing_provider, billing_account_id, product_id, vendor_product_code, billing_provider_id) VALUES ('161eab92-78db-4d03-a59e-d2d87e75768a', '14060133', '2024-02-02 08:57:29.470864 +00:00', '2023-12-29 11:37:38.590479 +00:00', '2024-02-02 08:57:29.470864 +00:00', '3949694', 'MW02393', 'aws', '157884790730', 'rosa', 'bcwuzc8ww10vvxfair55m', '');
INSERT INTO public.contracts (uuid, subscription_number, last_updated, start_date, end_date, org_id, sku, billing_provider, billing_account_id, product_id, vendor_product_code, billing_provider_id) VALUES ('b9ed5af1-f381-4192-b473-35b63ad77b3e', '14060133', '2024-02-02 08:57:29.470864 +00:00', '2024-02-02 08:57:29.470864 +00:00', null, '3949694', 'MW02393', 'aws', '157884790730', 'rosa', 'bcwuzc8ww10vvxfair55m', '');

```

**contract_metrics:**
```
INSERT INTO public.contract_metrics (contract_uuid, metric_id, metric_value) VALUES ('b9ed5af1-f381-4192-b473-35b63ad77b3e', 'premium_support', 1);
INSERT INTO public.contract_metrics (contract_uuid, metric_id, metric_value) VALUES ('b9ed5af1-f381-4192-b473-35b63ad77b3e', 'four_vcpu_hour', 18600);
```

**subscription:**
```
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, subscription_number, billing_provider, billing_account_id) VALUES ('RH00069', '3949694', '9504913', 1, '2019-09-13 04:00:00.000000 +00:00', '2026-12-31 05:00:00.000000 +00:00', '', '9505069', '', '');
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, subscription_number, billing_provider, billing_account_id) VALUES ('RH00009F3', '3949694', '8686822', 12, '2021-01-01 05:00:00.000000 +00:00', '2023-12-31 05:00:00.000000 +00:00', '', '8686978', '', '');
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, subscription_number, billing_provider, billing_account_id) VALUES ('RH00007F3', '3949694', '8686823', 45, '2021-01-01 05:00:00.000000 +00:00', '2023-12-31 05:00:00.000000 +00:00', '', '8686977', '', '');
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, subscription_number, billing_provider, billing_account_id) VALUES ('RH00009F3', '3949694', '8686800', 4, '2021-01-01 05:00:00.000000 +00:00', '2023-12-31 05:00:00.000000 +00:00', '', '8686955', '', '');
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, subscription_number, billing_provider, billing_account_id) VALUES ('MW01369', '3949694', '14065661', 1, '2023-12-30 00:00:00.000000 +00:00', '2024-02-27 00:00:00.000000 +00:00', '', '14065818', '', '');
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, subscription_number, billing_provider, billing_account_id) VALUES ('MW02393', '3949694', '14059976', 1, '2024-02-02 00:00:00.000000 +00:00', '2025-02-01 23:59:59.000000 +00:00', 'bcwuzc8ww10vvxfair55m;ZaTQYpfisUj;771835612317', '14060133', 'aws', '157884790730');
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, subscription_number, billing_provider, billing_account_id) VALUES ('MW02393', '3949694', '14059976', 1, '2023-11-06 00:00:00.000000 +00:00', '2024-02-01 23:59:59.000000 +00:00', 'bcwuzc8ww10vvxfair55m;ZaTQYpfisUj;771835612317', '14060133', 'aws', '157884790730');
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, subscription_number, billing_provider, billing_account_id) VALUES ('MW02393', '3949694', '14059976', 1, '2023-12-29 11:37:38.590479 +00:00', '2024-02-02 08:57:29.470864 +00:00', '', '14060133', 'aws', '157884790730');
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, subscription_number, billing_provider, billing_account_id) VALUES ('MCT4022', '3949694', '13985196', 10, '2023-12-14 05:00:00.000000 +00:00', '2027-01-01 04:59:59.000000 +00:00', '', '13985353', '', '');
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, subscription_number, billing_provider, billing_account_id) VALUES ('RH00009', '3949694', '13985194', 15, '2024-01-01 05:00:00.000000 +00:00', '2024-12-31 05:00:00.000000 +00:00', '', '13985351', '', '');
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, subscription_number, billing_provider, billing_account_id) VALUES ('RH00009', '3949694', '13985193', 12, '2024-01-01 05:00:00.000000 +00:00', '2024-12-31 05:00:00.000000 +00:00', '', '13985350', '', '');
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, subscription_number, billing_provider, billing_account_id) VALUES ('RH00007', '3949694', '13985192', 34, '2024-01-01 05:00:00.000000 +00:00', '2024-12-31 05:00:00.000000 +00:00', '', '13985349', '', '');
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, subscription_number, billing_provider, billing_account_id) VALUES ('MCT3691F3', '3949694', '13985185', 2, '2024-01-01 05:00:00.000000 +00:00', '2026-12-31 05:00:00.000000 +00:00', '', '13985343', '', '');
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, subscription_number, billing_provider, billing_account_id) VALUES ('RH00270', '3949694', '13985181', 10, '2024-01-01 05:00:00.000000 +00:00', '2024-12-31 05:00:00.000000 +00:00', '', '13985338', '', '');
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, subscription_number, billing_provider, billing_account_id) VALUES ('MW02393', '3949694', '13787254', 1, '2023-11-06 05:00:00.000000 +00:00', '2024-11-06 04:59:59.000000 +00:00', 'bcwuzc8ww10vvxfair55m;G7VY9CZp6JV;771835612317', '13787411', 'aws', '918934589723');
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, subscription_number, billing_provider, billing_account_id) VALUES ('MW02393', '3949694', '13787217', 1, '2023-11-06 05:00:00.000000 +00:00', '2024-11-06 04:59:59.000000 +00:00', 'bcwuzc8ww10vvxfair55m;9eZA9pRHXmm;771835612317', '13787374', 'aws', '638936737416');
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, subscription_number, billing_provider, billing_account_id) VALUES ('MW01369', '3949694', '13755903', 1, '2023-10-31 04:00:00.000000 +00:00', '2023-12-29 05:00:00.000000 +00:00', '', '13756060', '', '');
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, subscription_number, billing_provider, billing_account_id) VALUES ('MCT3754F3', '3949694', '11601249', 216, '2022-09-13 04:00:00.000000 +00:00', '2025-09-12 04:00:00.000000 +00:00', '', '11601406', '', '');

```

subscription_product_ids:
```
INSERT INTO public.subscription_product_ids (product_id, subscription_id, start_date) VALUES ('rhel-for-x86-eus', '11601249', '2022-09-13 04:00:00.000000 +00:00');
INSERT INTO public.subscription_product_ids (product_id, subscription_id, start_date) VALUES ('RHEL for ARM', '11601249', '2022-09-13 04:00:00.000000 +00:00');
INSERT INTO public.subscription_product_ids (product_id, subscription_id, start_date) VALUES ('OpenShift Container Platform', '11601249', '2022-09-13 04:00:00.000000 +00:00');
INSERT INTO public.subscription_product_ids (product_id, subscription_id, start_date) VALUES ('RHEL for x86', '8686823', '2021-01-01 05:00:00.000000 +00:00');
INSERT INTO public.subscription_product_ids (product_id, subscription_id, start_date) VALUES ('RHEL for x86', '8686800', '2021-01-01 05:00:00.000000 +00:00');
INSERT INTO public.subscription_product_ids (product_id, subscription_id, start_date) VALUES ('RHEL for x86', '8686822', '2021-01-01 05:00:00.000000 +00:00');
INSERT INTO public.subscription_product_ids (product_id, subscription_id, start_date) VALUES ('rhel-for-x86-eus', '13755903', '2023-10-31 04:00:00.000000 +00:00');
INSERT INTO public.subscription_product_ids (product_id, subscription_id, start_date) VALUES ('OpenShift Container Platform', '13755903', '2023-10-31 04:00:00.000000 +00:00');
INSERT INTO public.subscription_product_ids (product_id, subscription_id, start_date) VALUES ('RHEL for ARM', '13755903', '2023-10-31 04:00:00.000000 +00:00');
INSERT INTO public.subscription_product_ids (product_id, subscription_id, start_date) VALUES ('RHEL for x86', '13985192', '2024-01-01 05:00:00.000000 +00:00');
INSERT INTO public.subscription_product_ids (product_id, subscription_id, start_date) VALUES ('rhel-for-x86-els-payg', '13985181', '2024-01-01 05:00:00.000000 +00:00');
INSERT INTO public.subscription_product_ids (product_id, subscription_id, start_date) VALUES ('RHEL for x86', '13985193', '2024-01-01 05:00:00.000000 +00:00');
INSERT INTO public.subscription_product_ids (product_id, subscription_id, start_date) VALUES ('RHEL for x86', '13985194', '2024-01-01 05:00:00.000000 +00:00');
INSERT INTO public.subscription_product_ids (product_id, subscription_id, start_date) VALUES ('RHEL for x86', '13985196', '2023-12-14 05:00:00.000000 +00:00');
INSERT INTO public.subscription_product_ids (product_id, subscription_id, start_date) VALUES ('rhel-for-x86-eus', '14065661', '2023-12-30 00:00:00.000000 +00:00');
INSERT INTO public.subscription_product_ids (product_id, subscription_id, start_date) VALUES ('OpenShift Container Platform', '14065661', '2023-12-30 00:00:00.000000 +00:00');
INSERT INTO public.subscription_product_ids (product_id, subscription_id, start_date) VALUES ('RHEL for ARM', '14065661', '2023-12-30 00:00:00.000000 +00:00');

```

**subscription_measurements:**
```
INSERT INTO public.subscription_measurements (subscription_id, start_date, metric_id, measurement_type, value) VALUES ('13985192', '2024-01-01 05:00:00.000000 +00:00', 'Sockets', 'HYPERVISOR', 68);
INSERT INTO public.subscription_measurements (subscription_id, start_date, metric_id, measurement_type, value) VALUES ('13985181', '2024-01-01 05:00:00.000000 +00:00', 'Sockets', 'PHYSICAL', 20);
INSERT INTO public.subscription_measurements (subscription_id, start_date, metric_id, measurement_type, value) VALUES ('13985193', '2024-01-01 05:00:00.000000 +00:00', 'Sockets', 'PHYSICAL', 24);
INSERT INTO public.subscription_measurements (subscription_id, start_date, metric_id, measurement_type, value) VALUES ('13985194', '2024-01-01 05:00:00.000000 +00:00', 'Sockets', 'PHYSICAL', 30);
INSERT INTO public.subscription_measurements (subscription_id, start_date, metric_id, measurement_type, value) VALUES ('11601249', '2022-09-13 04:00:00.000000 +00:00', 'Cores', 'PHYSICAL', 432);
INSERT INTO public.subscription_measurements (subscription_id, start_date, metric_id, measurement_type, value) VALUES ('8686823', '2021-01-01 05:00:00.000000 +00:00', 'Sockets', 'HYPERVISOR', 90);
INSERT INTO public.subscription_measurements (subscription_id, start_date, metric_id, measurement_type, value) VALUES ('8686800', '2021-01-01 05:00:00.000000 +00:00', 'Sockets', 'PHYSICAL', 8);
INSERT INTO public.subscription_measurements (subscription_id, start_date, metric_id, measurement_type, value) VALUES ('8686822', '2021-01-01 05:00:00.000000 +00:00', 'Sockets', 'PHYSICAL', 24);
```

- Get swatch-core running:
`RHSM_SUBSCRIPTIONS_ENABLE_SYNCHRONOUS_OPERATIONS=true DEV_MODE=true PROM_URL=http://localhost:8082/api/metrics/v1/telemeter/api/v1 SWATCH_CONTRACTS_INTERNAL_SERVICE=http://localhost:8882 SERVER_PORT=8001 SPRING_PROFILES_ACTIVE=worker,kafka-queue,api,capacity-ingress,rh-marketplace,kafka-queue,rhsm-conduit ./gradlew clean :bootRun`

- Get swatch-contracts running with pointing to prod:
```
Index: swatch-contracts/src/main/resources/application.properties
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>ISO-8859-1
===================================================================
diff --git a/swatch-contracts/src/main/resources/application.properties b/swatch-contracts/src/main/resources/application.properties
--- a/swatch-contracts/src/main/resources/application.properties	(revision dde32b0e21b0b2ae3baadbd99ec18a742ebede24)
+++ b/swatch-contracts/src/main/resources/application.properties	(date 1708626650050)
@@ -180,7 +180,7 @@
 mp.messaging.outgoing.contractstest.connector=smallrye-in-memory
 %stage.mp.messaging.incoming.contracts.connector=smallrye-amqp
 %stage.mp.messaging.outgoing.contractstest.connector=smallrye-in-memory
-%prod.mp.messaging.incoming.contracts.connector=smallrye-amqp
+%prod.mp.messaging.incoming.contracts.connector=smallrye-in-memory
 %prod.mp.messaging.outgoing.contractstest.connector=smallrye-in-memory
 
 #This is to trace only my package and enable logging if the org exists
@@ -192,7 +192,7 @@
 %ephemeral.quarkus.otel.sdk.disabled=true
 %wiremock.quarkus.otel.sdk.disabled=true
 %stage.quarkus.otel.sdk.disabled=false
-%prod.quarkus.otel.sdk.disabled=false
+%prod.quarkus.otel.sdk.disabled=true
 
 OTEL_ENDPOINT=http://splunk-otel-collector:4317
 quarkus.otel.exporter.otlp.endpoint=${OTEL_ENDPOINT}

```

`ENABLE_SPLUNK_HEC=false ENTITLEMENT_GATEWAY_URL=https://ibm-entitlement-gateway.api.redhat.com KEYSTORE_PASSWORD=<PWD> KEYSTORE_RESOURCE=file:/home/../rhsm-subscriptions/config/certs/bkpcerts_prod/keystore.jks QUARKUS_PROFILE=prod SWATCH_INTERNAL_SUBSCRIPTION_ENDPOINT=http://localhost:8001 SWATCH_SELF_PSK=placeholder UMB_ENABLED=false RBAC_ENABLED=false RBAC_ENDPOINT=http://localhost:8080 UMB_HOSTNAME=localhost  ./gradlew  :swatch-contracts:quarkusDev
`

### Steps and Verification

**Step 1 before running sync contract by orgid check for capacity:**
`http ':8001/api/rhsm-subscriptions/v1/subscriptions/products/rosa' uom==Cores x-rh-identity:$(echo '{"identity":{"type":"User","internal":{"org_id":"3949694"}}}' | base64 -w0)`

```
{
    "data": [
        {
            "billing_provider": "aws",
            "capacity": 0,
            "has_infinite_quantity": false,
            "hypervisor_capacity": 0,
            "next_event_date": "2024-11-06T04:59:59Z",
            "next_event_type": "Subscription End",
            "product_name": "Red Hat OpenShift Service on AWS Hosted Control Planes (Hourly)",
            "quantity": 3,
            "service_level": "Premium",
            "sku": "MW02393",
            "subscriptions": [
                {
                    "id": "13787217",
                    "number": "13787374"
                },
                {
                    "id": "13787254",
                    "number": "13787411"
                },
                {
                    "id": "14059976",
                    "number": "14060133"
                }
            ],
            "total_capacity": 0,
            "usage": ""
        }
    ],
    "meta": {
        "count": 1,
        "product": "rosa",
        "subscription_type": "On-demand",
        "uom": "cores"
    }
}
```
** ${{\color{Yellow}\Huge{\textsf{ Notice it doesn't have capacity for subscriptionnumber: 14060133}}}}\$ **

Step 1 Run the syncContractsByOrg with is_pre_cleanup flag true on this branch:
`curl -X 'POST'   'http://localhost:8000/api/swatch-contracts/internal/rpc/sync/contracts/3949694?is_pre_cleanup=true'   -H 'accept: application/json'   -H 'x-rh-swatch-psk: placeholder'   -d ''`

 **Output Verification**:
`{"status":"SUCCESS","message":"Contracts Synced for 3949694"}`

**Logs:**
 Total contract deleted for org 3949694 during pre cleanup 2

** ${{\color{Yellow}\Huge{\textsf{ Notice table changes and capacity}}}}\$ **
- Contract table now has missed contracts
- Capacity now shows up

**contracts:**
```
uuid,subscription_number,last_updated,start_date,end_date,org_id,sku,billing_provider,billing_account_id,product_id,vendor_product_code,billing_provider_id
aa8a47bb-5c92-4d5a-aa41-e9de70d0c78f,14060133,2024-02-22 16:27:43.225667 +00:00,2024-02-02 08:59:32.714240 +00:00,2025-02-02 08:57:18.166000 +00:00,3949694,MW02393,aws,157884790730,rosa,bcwuzc8ww10vvxfair55m,bcwuzc8ww10vvxfair55m;ZaTQYpfisUj;771835612317
105b2389-a029-45e3-bc0a-dc1640d533fb,13787374,2024-02-22 16:27:43.373510 +00:00,2023-11-06 21:35:36.936064 +00:00,2024-11-06 21:33:27.224000 +00:00,3949694,MW02393,aws,638936737416,rosa,bcwuzc8ww10vvxfair55m,bcwuzc8ww10vvxfair55m;9eZA9pRHXmm;771835612317
216cef25-8658-4f34-90eb-dc5c25cf6bd7,13787411,2024-02-22 16:27:43.478937 +00:00,2023-11-06 21:51:32.946104 +00:00,2024-11-06 21:49:21.391000 +00:00,3949694,MW02393,aws,918934589723,rosa,bcwuzc8ww10vvxfair55m,bcwuzc8ww10vvxfair55m;G7VY9CZp6JV;771835612317
```

**contract_metrics:**
```
uuid,subscription_number,last_updated,start_date,end_date,org_id,sku,billing_provider,billing_account_id,product_id,vendor_product_code,billing_provider_id
aa8a47bb-5c92-4d5a-aa41-e9de70d0c78f,14060133,2024-02-22 16:27:43.225667 +00:00,2024-02-02 08:59:32.714240 +00:00,2025-02-02 08:57:18.166000 +00:00,3949694,MW02393,aws,157884790730,rosa,bcwuzc8ww10vvxfair55m,bcwuzc8ww10vvxfair55m;ZaTQYpfisUj;771835612317
105b2389-a029-45e3-bc0a-dc1640d533fb,13787374,2024-02-22 16:27:43.373510 +00:00,2023-11-06 21:35:36.936064 +00:00,2024-11-06 21:33:27.224000 +00:00,3949694,MW02393,aws,638936737416,rosa,bcwuzc8ww10vvxfair55m,bcwuzc8ww10vvxfair55m;9eZA9pRHXmm;771835612317
216cef25-8658-4f34-90eb-dc5c25cf6bd7,13787411,2024-02-22 16:27:43.478937 +00:00,2023-11-06 21:51:32.946104 +00:00,2024-11-06 21:49:21.391000 +00:00,3949694,MW02393,aws,918934589723,rosa,bcwuzc8ww10vvxfair55m,bcwuzc8ww10vvxfair55m;G7VY9CZp6JV;771835612317
```

**subscription:**
```
sku,org_id,subscription_id,quantity,start_date,end_date,billing_provider_id,subscription_number,billing_provider,billing_account_id
RH00069,3949694,9504913,1,2019-09-13 04:00:00.000000 +00:00,2026-12-31 05:00:00.000000 +00:00,"",9505069,"",""
RH00009F3,3949694,8686822,12,2021-01-01 05:00:00.000000 +00:00,2023-12-31 05:00:00.000000 +00:00,"",8686978,"",""
RH00007F3,3949694,8686823,45,2021-01-01 05:00:00.000000 +00:00,2023-12-31 05:00:00.000000 +00:00,"",8686977,"",""
RH00009F3,3949694,8686800,4,2021-01-01 05:00:00.000000 +00:00,2023-12-31 05:00:00.000000 +00:00,"",8686955,"",""
MW01369,3949694,14065661,1,2023-12-30 00:00:00.000000 +00:00,2024-02-27 00:00:00.000000 +00:00,"",14065818,"",""
MW02393,3949694,14059976,1,2024-02-02 08:59:32.714240 +00:00,2025-02-02 08:57:18.166000 +00:00,bcwuzc8ww10vvxfair55m;ZaTQYpfisUj;771835612317,14060133,aws,157884790730
MW02393,3949694,14059976,1,2024-02-02 00:00:00.000000 +00:00,2025-02-01 23:59:59.000000 +00:00,bcwuzc8ww10vvxfair55m;ZaTQYpfisUj;771835612317,14060133,aws,157884790730
MW02393,3949694,14059976,1,2023-11-06 00:00:00.000000 +00:00,2024-02-01 23:59:59.000000 +00:00,bcwuzc8ww10vvxfair55m;ZaTQYpfisUj;771835612317,14060133,aws,157884790730
MW02393,3949694,14059976,1,2023-12-29 11:37:38.590479 +00:00,2024-02-02 08:57:29.470864 +00:00,"",14060133,aws,157884790730
MCT4022,3949694,13985196,10,2023-12-14 05:00:00.000000 +00:00,2027-01-01 04:59:59.000000 +00:00,"",13985353,"",""
RH00009,3949694,13985194,15,2024-01-01 05:00:00.000000 +00:00,2024-12-31 05:00:00.000000 +00:00,"",13985351,"",""
RH00009,3949694,13985193,12,2024-01-01 05:00:00.000000 +00:00,2024-12-31 05:00:00.000000 +00:00,"",13985350,"",""
RH00007,3949694,13985192,34,2024-01-01 05:00:00.000000 +00:00,2024-12-31 05:00:00.000000 +00:00,"",13985349,"",""
MCT3691F3,3949694,13985185,2,2024-01-01 05:00:00.000000 +00:00,2026-12-31 05:00:00.000000 +00:00,"",13985343,"",""
RH00270,3949694,13985181,10,2024-01-01 05:00:00.000000 +00:00,2024-12-31 05:00:00.000000 +00:00,"",13985338,"",""
MW02393,3949694,13787254,1,2023-11-06 05:00:00.000000 +00:00,2024-11-06 04:59:59.000000 +00:00,bcwuzc8ww10vvxfair55m;G7VY9CZp6JV;771835612317,13787411,aws,918934589723
MW02393,3949694,13787254,1,2023-11-06 21:51:32.946104 +00:00,2024-11-06 21:49:21.391000 +00:00,bcwuzc8ww10vvxfair55m;G7VY9CZp6JV;771835612317,13787411,aws,918934589723
MW02393,3949694,13787217,1,2023-11-06 21:35:36.936064 +00:00,2024-11-06 21:33:27.224000 +00:00,bcwuzc8ww10vvxfair55m;9eZA9pRHXmm;771835612317,13787374,aws,638936737416
MW02393,3949694,13787217,1,2023-11-06 05:00:00.000000 +00:00,2024-11-06 04:59:59.000000 +00:00,bcwuzc8ww10vvxfair55m;9eZA9pRHXmm;771835612317,13787374,aws,638936737416
MW01369,3949694,13755903,1,2023-10-31 04:00:00.000000 +00:00,2023-12-29 05:00:00.000000 +00:00,"",13756060,"",""
MCT3754F3,3949694,11601249,216,2022-09-13 04:00:00.000000 +00:00,2025-09-12 04:00:00.000000 +00:00,"",11601406,"",""
```

**subscription_measurements:**
```
subscription_id,start_date,metric_id,measurement_type,value
13985192,2024-01-01 05:00:00.000000 +00:00,Sockets,HYPERVISOR,68
13985181,2024-01-01 05:00:00.000000 +00:00,Sockets,PHYSICAL,20
13985193,2024-01-01 05:00:00.000000 +00:00,Sockets,PHYSICAL,24
13985194,2024-01-01 05:00:00.000000 +00:00,Sockets,PHYSICAL,30
11601249,2022-09-13 04:00:00.000000 +00:00,Cores,PHYSICAL,432
8686823,2021-01-01 05:00:00.000000 +00:00,Sockets,HYPERVISOR,90
8686800,2021-01-01 05:00:00.000000 +00:00,Sockets,PHYSICAL,8
8686822,2021-01-01 05:00:00.000000 +00:00,Sockets,PHYSICAL,24
14059976,2024-02-02 08:59:32.714240 +00:00,Cores,PHYSICAL,74400
```

**subscription_product_ids:**
```
product_id,subscription_id,start_date
rhel-for-x86-eus,11601249,2022-09-13 04:00:00.000000 +00:00
RHEL for ARM,11601249,2022-09-13 04:00:00.000000 +00:00
OpenShift Container Platform,11601249,2022-09-13 04:00:00.000000 +00:00
RHEL for x86,8686823,2021-01-01 05:00:00.000000 +00:00
RHEL for x86,8686800,2021-01-01 05:00:00.000000 +00:00
RHEL for x86,8686822,2021-01-01 05:00:00.000000 +00:00
rhel-for-x86-eus,13755903,2023-10-31 04:00:00.000000 +00:00
OpenShift Container Platform,13755903,2023-10-31 04:00:00.000000 +00:00
RHEL for ARM,13755903,2023-10-31 04:00:00.000000 +00:00
RHEL for x86,13985192,2024-01-01 05:00:00.000000 +00:00
rhel-for-x86-els-payg,13985181,2024-01-01 05:00:00.000000 +00:00
RHEL for x86,13985193,2024-01-01 05:00:00.000000 +00:00
RHEL for x86,13985194,2024-01-01 05:00:00.000000 +00:00
RHEL for x86,13985196,2023-12-14 05:00:00.000000 +00:00
rhel-for-x86-eus,14065661,2023-12-30 00:00:00.000000 +00:00
OpenShift Container Platform,14065661,2023-12-30 00:00:00.000000 +00:00
RHEL for ARM,14065661,2023-12-30 00:00:00.000000 +00:00
rosa,14059976,2024-02-02 08:59:32.714240 +00:00
rosa,13787217,2023-11-06 21:35:36.936064 +00:00
rosa,13787254,2023-11-06 21:51:32.946104 +00:00
```

Capacity api:
`http ':8001/api/rhsm-subscriptions/v1/subscriptions/products/rosa' uom==Cores x-rh-identity:$(echo '{"identity":{"type":"User","internal":{"org_id":"3949694"}}}' | base64 -w0)`

```
{
    "data": [
        {
            "billing_provider": "aws",
            "capacity": 74400,
            "has_infinite_quantity": false,
            "hypervisor_capacity": 0,
            "next_event_date": "2025-02-02T08:57:18.166Z",
            "next_event_type": "Subscription End",
            "product_name": "Red Hat OpenShift Service on AWS Hosted Control Planes (Hourly)",
            "quantity": 1,
            "service_level": "Premium",
            "sku": "MW02393",
            "subscriptions": [
                {
                    "id": "14059976",
                    "number": "14060133"
                }
            ],
            "total_capacity": 74400,
            "uom": "cores",
            "usage": ""
        }
    ],
    "meta": {
        "count": 1,
        "product": "rosa",
        "subscription_type": "On-demand",
        "uom": "cores"
    }
}

```
I want QE to validate this with subscription sync and see if the capacity is still showing correctly. One thing I notice is capacity doesn't pull the subscription_id='13787254' and '13787217'. This is the same issue on main branch and is not related to this PR. This is because when a contract is created after subscription it has different start date.

The above is not a bug since it will show up when you do:
`http ':8001/api/rhsm-subscriptions/v1/subscriptions/products/rosa'  x-rh-identity:$(echo '{"identity":{"type":"User","internal":{"org_id":"3949694"}}}' | base64 -w0)`

### CODE REVIEW

**Comment by Aurobinda55** [comment]
Verification steps - 

- From the Iqe shell; create a contract using the iqe command 
 ```
contract_data1={'instance_hours': 5,
 'cores': 7,
 'billing_provider': 'aws',
 'billing_account_id': 'test129',
 'sku': 'MW02393',
'start_date': '2024-02-01T10:44:55Z'}
application.rhsm_subscriptions.create_contract(product_id=product_id, **contract_data1) 
```
(the new contract creation logic is not yet in the main branch, so using the old payload format )
- Contract created with the valid details 
- Sync contract  with is_pre_cleanup=False/True
 ```
From smqe_tools import sync_contract
sync_contract(org_id="14541308"); is_pre_cleanup=False 
```
- Verified that no contract was deleted and got the below log message 
```
2024-02-28 06:53:16,984 DEBUG [com.red.swa.con.ser.ContractService] (executor-thread-3) {sampled=true, spanId=0c5e06a02aeff08e, traceId=46321e4a466dcd405b5a4f377bdf9977, user=urn:console.redhat.com:service:swatch} Contracts fetched for org 14541308 from upstream class PartnerEntitlements {
content: []
page: class PartnerEntitlementsPage {
size: 20
totalElements: 0
totalPages: 0
number: 0
}
} 
```
it was trying to fetch the contract and as there was no contract in the upstream ,so it Failed in response with message 
```
{'status': 'FAILED',
 'message': 'No contracts found in upstream for the org 14541308'}
```
Again,
sync_contract(org_id="14541308",is_pre_cleanup=True);
and verified that 1 activate contract deleted and got the below logs 
```
Total contract deleted for org 14541308 during pre cleanup 1
2024-02-28 06:54:03,497 DEBUG [com.red.swa.con.ser.ContractService] (executor-thread-1) {sampled=true, spanId=b4cd4c019d756b4e, traceId=d92227d188ef4a56d362e35c02a026e5, user=urn:console.redhat.com:service:swatch} Contracts fetched for org 14541308 from upstream class PartnerEntitlements 
```
In both the cases, the sync contract api worked fine with the is_pre_cleanup flag and tried to fetch the contract from the upstream , but failed as we don't have the sufficient data . 

There is a imitation for QE to  clone the prod data or connect to prod IT entitlement gateway, since it requires special certs for auth, which we don’t have. 

So , based on the  above mentioned log message  ack the PR , once the  PR in stage  I will  check the second scenario  mentioned in https://redhat-internal.slack.com/archives/C04K9MVQ9R9/p1708930970635189

**Review by Aurobinda55 — APPROVED** [review]

**Review by kahowell — APPROVED** [review]

**Pull request merged**
