### PR TITLE
Sample openshift definition for deploying wiremock to ephemeral environment

### PR DESCRIPTION
**Pull request by lindseyburnett**
Supports testing of #2717 in Ephemeral Environments

The gist here is to optionally shove a wiremock deployment & service into an ephemeral environment, and then you can configure port-forward the pod to create stubs, and then configure other pods to point to wiremock.

This PR gives the yaml for wiremock to be deployed, and creation of a "wiremock" quarkus profile that will set ENTITLEMENT_GATEWAY_URL, SWATCH_INTERNAL_SUBSCRIPTION_ENDPOINT, and SUBSCRIPTION_URL to point to a deployed wiremock service.

Example workflow:

Deploy swatch with bonfire.  The template ref for this example is this PR's commit (needed for that mentioned ClowdApp change).  Then follow instructions in the README.md file to deploy wiremock and create a stub.

```
TEMPLATE_REF=f14b85cd8b00d3fc95e48dd3a4f2320cf4ef8398 IMAGE_TAG=pr-2717-latest && bonfire deploy rhsm \
 --source=appsre \
 --ref-env insights-production \
 --optional-deps-method none \
 --frontends false \
 --timeout 1800 \
 --no-remove-resources rhsm \
 --no-remove-resources swatch-api \
 --no-remove-resources swatch-contracts \
 --no-remove-resources swatch-producer-aws \
 --no-remove-resources swatch-producer-red-hat-marketplace \
 --no-remove-resources swatch-metrics \
 --no-remove-resources swatch-subscription-sync \
 --no-remove-resources swatch-system-conduit \
 --no-remove-resources swatch-tally \
 --no-remove-resources swatch-producer-azure \
 -i quay.io/cloudservices/rhsm-subscriptions=$IMAGE_TAG \
 -i quay.io/cloudservices/swatch-contracts=$IMAGE_TAG \
 -i quay.io/cloudservices/swatch-metrics=$IMAGE_TAG \
 -i quay.io/cloudservices/swatch-producer-aws=$IMAGE_TAG \
 -i quay.io/cloudservices/swatch-producer-azure=$IMAGE_TAG \
 -i quay.io/cloudservices/swatch-system-conduit=$IMAGE_TAG \
 --set-template-ref rhsm=$TEMPLATE_REF \
 --set-template-ref swatch-api=$TEMPLATE_REF \
 --set-template-ref swatch-contracts=$TEMPLATE_REF \
 --set-template-ref swatch-producer-aws=$TEMPLATE_REF \
 --set-template-ref swatch-producer-red-hat-marketplace=$TEMPLATE_REF \
 --set-template-ref swatch-metrics=$TEMPLATE_REF \
 --set-template-ref swatch-subscription-sync=$TEMPLATE_REF \
 --set-template-ref swatch-system-conduit=$TEMPLATE_REF \
 --set-template-ref swatch-tally=$TEMPLATE_REF \
 --set-template-ref swatch-producer-azure=$TEMPLATE_REF \
 -p swatch-contracts/QUARKUS_PROFILE=wiremock
```

### CODE REVIEW

**Review by kflahert — APPROVED** [review]
Was able to test successfully just need to update the deploy command to fix:

`TEMPLATE_REF=TEMPLATE_REF=5beaf2ac881a7079568e6305ac1887637fdc9620`
to
`TEMPLATE_REF=5beaf2ac881a7079568e6305ac1887637fdc9620`

**Comment by lindseyburnett** [comment]
> Was able to test successfully just need to update the deploy command to fix:
> 
> `TEMPLATE_REF=TEMPLATE_REF=5beaf2ac881a7079568e6305ac1887637fdc9620` to `TEMPLATE_REF=5beaf2ac881a7079568e6305ac1887637fdc9620`

thanks for the catch...updated in the description

**Review by kahowell — APPROVED** [review]

**Pull request merged**
