### PR TITLE
[Feature branch] Nightly tally - minimize memory usage

### PR DESCRIPTION
**Pull request by kahowell**

### CODE REVIEW

**Comment by kahowell** [comment]
4bcaf4d to cd395c6: rebase against `main`

**Comment by kahowell** [comment]
cd395c6 to 4bcaf4d: changed my mind, easier to integrate by merging `main`.

**Comment by kahowell** [comment]
Note: everything up to d1e2a64 (inclusive) already reviewed, looking to get necessary QE tests updated, performance evaluation before merging.

**Comment by ntkathole** [comment]
Test is failing as system (OpenShift Container Platform product) created with following facts increasing hypervisor_cores, hypervisor_instance_count as well as cores in tally, which is new behavior. Earlier such system was not changing to hypervisor_cores and hypervisor_instance_count. 

System facts:

` 'display_name': 'virtual_mockvyvbfgru.example.gov',
  'facts': [ { 'facts': { 'ARCHITECTURE': 'x86_64',
                          'BILLING_MODEL': 'Standard',
                          'IS_VIRTUAL': True,
                          'MEMORY': 62,
                          'RH_PROD': ['290'],
                          'SYNC_TIMESTAMP': '2023-02-24T08:27:54.288170+00:00',
                          'SYSPURPOSE_ADDONS': [],
                          'SYSPURPOSE_UNITS': 'Cores/vCPU',
                          'SYSPURPOSE_USAGE': 'Disaster Recovery',
                          'orgId': '14540822'},
               'namespace': 'rhsm'}],
[{'cores': 20,
 'display_name': 'virtual_mockvyvbfgru.example.gov',
 'hardware_type': 'VIRTUALIZED',
 'insights_id': '2dfda735-3b50-492a-9543-16184ae357cf',
 'inventory_id': 'e26c85c0-6e95-49e4-966d-90d525b3a8dc',
 'is_hypervisor': False,
 'is_unmapped_guest': True,
 'last_seen': datetime.datetime(2023, 2, 20, 8, 27, 54, 305043, tzinfo=tzlocal()),
 'measurement_type': 'VIRTUAL',
 'sockets': 0,
 'subscription_manager_id': '2fe5d3c1-6cff-4bf5-a3d3-73dfd13dee3c'}]`

Tally results:

`{'cloud_cores': 0,
 'cloud_instance_count': 0,
 'cloud_sockets': 0,
 'core_hours': 20.0,
 'cores': 20,
 'date': datetime.datetime(2023, 2, 20, 0, 0, tzinfo=tzlocal()),
 'has_cloudigrade_data': False,
 'has_cloudigrade_mismatch': False,
 'has_data': True,
 'hypervisor_cores': 20,
 'hypervisor_instance_count': 1,
 'hypervisor_sockets': 0,
 'instance_count': 1,
 'physical_cores': 0,
 'physical_instance_count': 0,
 'physical_sockets': 0,
 'sockets': 0}`

**Comment by ntkathole** [comment]
Thanks @mstead for clarification. I have raised MR to update the test, Once feature branch merge plan is confirmed, I will merge MR and retest this before merge.

**Pull request merged**
