### PR TITLE
SWATCH-1386: Add metric_id to openapi definitions

### PR DESCRIPTION
**Pull request by Sgitario**
Jira issue: [SWATCH-1386](https://issues.redhat.com/browse/SWATCH-1386)
Jira issue: [SWATCH-1383](https://issues.redhat.com/browse/SWATCH-1383)

## Description
metric_id is included on the OpenAPI endpoints & populated where we are currently using UOM. This includes both query parameters & response bodies. Apart from the above change, I've also:
- Removed the unused "HostReport" model
- Removed the "uom" field from the event model because it was not used

## Testing
Since, we haven't removed the uom field, the QE tests should work the same. 
QE needs to be updated to use "metric_id" instead of "uom", so adding the QE label.

### CODE REVIEW

**Review by lindseyburnett — APPROVED** [review]

**Review by ntkathole — APPROVED** [review]
Looks good!

```

In [10]: app.rhsm_subscriptions.get_instances_report(product_id="RHEL for x86", uom="Sockets")
2024-03-15 05:41:39.938 [    INFO] [iqe.base.rest_client] REST: METHOD=GET, request_id=None, params=[('limit', 100), ('offset', 0), ('uom', 'Sockets')]
Out[10]:
[{'id': '3d2e9d75-6080-45f3-b05f-f27b18d74e61',
  'instance_id': '0978a2df-c409-4211-b42b-e96624a36e11',
  'display_name': 'physical_mockdnmqeuug.example.biz',
  'measurements': [2.0],
  'last_seen': datetime.datetime(2024, 3, 15, 5, 41, 1, 704900, tzinfo=tzlocal()),
  'number_of_guests': 0,
  'category': 'physical',
  'subscription_manager_id': '8968a9f6-975c-43de-b180-d07439a48ed1',
  '_labeled_measurements': {'Sockets': 2.0}}]

In [11]: app.rhsm_subscriptions.get_instances_report(product_id="RHEL for x86", metric_id="Sockets")
2024-03-15 05:41:43.461 [    INFO] [iqe.base.rest_client] REST: METHOD=GET, request_id=None, params=[('limit', 100), ('offset', 0), ('metric_id', 'Sockets')]
Out[11]:
[{'id': '3d2e9d75-6080-45f3-b05f-f27b18d74e61',
  'instance_id': '0978a2df-c409-4211-b42b-e96624a36e11',
  'display_name': 'physical_mockdnmqeuug.example.biz',
  'measurements': [2.0],
  'last_seen': datetime.datetime(2024, 3, 15, 5, 41, 1, 704900, tzinfo=tzlocal()),
  'number_of_guests': 0,
  'category': 'physical',
  'subscription_manager_id': '8968a9f6-975c-43de-b180-d07439a48ed1',
  '_labeled_measurements': {'Sockets': 2.0}}]

In [18]: app.rhsm_subscriptions.get_skus_report(metric_id="sockets")
2024-03-15 05:45:54.464 [    INFO] [iqe.base.rest_client] REST: METHOD=GET, request_id=None, params=[('sort', 'next_event_date'), ('limit', 100), ('offset', 0), ('metric_id', 'sockets')]
Out[18]: []

In [19]: app.rhsm_subscriptions.get_skus_report(uom="sockets")
2024-03-15 05:46:00.939 [    INFO] [iqe.base.rest_client] REST: METHOD=GET, request_id=None, params=[('sort', 'next_event_date'), ('limit', 100), ('offset', 0), ('uom', 'sockets')]
Out[19]: []
```

Openapi updated for automation - https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/613

**Pull request merged**
