### PR TITLE
SWATCH-1243: Fixing Missing Release version for Operating System

### PR DESCRIPTION
**Pull request by ksynvrit**
Jira issue: [SWATCH-1243](https://issues.redhat.com/browse/SWATCH-1243)

## Description

Error was caused due to `"` empty being placed as a value for Os version and the current logic would produce a Operating system with a name, but null major & minor versions. So we will just return the OS has null. 

## Testing

1. Run Rhsm-conduit with these environment viables:
```
DEV_MODE=true;RHSM_USE_STUB=true
## SideNote: Run these step on `main` branch to reproduce error and than switch back to verify that the change address the issue.
```
2. Go to `StubRhsmApi` and make the `distribution.version` =`""`.
3. Run `syncOrg(String)` in Hawtio for conduit, the input string can be anything as we will be leveraging the mock values here.
```
http://localhost:9000/hawtio/jmx/operations?nid=root-org.candlepin.subscriptions.conduit.jmx-RhsmConduitJmxBean-rhsmConduitJmxBean
```
Make sure Kafka pods are running and use either Big Data tools in the IDE or Kafka UI:
 If you're using Big Data Tool make sure to create a consumer within the `platform.inventory.host-ingress` topic to see the message being sent.

The expected message output received from Rhsm-conduit when the we get a empty OS version should have operating system as`null`:
```
{"operation":"add_host","data":{"account":"ACCOUNT_1","org_id":"orgId321","subscription_manager_id":"663b6f0d-cfe5-488e-aa14-24855c1275eb","bios_uuid":"acc67480-4957-4c45-b6ac-7c2614c9045f","fqdn":"host1.test.com","facts":[{"namespace":"rhsm","facts":{"SYNC_TIMESTAMP":"2023-01-24T16:28:48.956227664Z","IS_VIRTUAL":true,"SYSPURPOSE_SLA":"Premium","MEMORY":32,"ARCHITECTURE":"x86_64","VM_HOST":"hypervisor1.test.com","SYSPURPOSE_UNITS":"Sockets","RH_PROD":["72"],"orgId":"orgId321","BILLING_MODEL":"standard"}}],"system_profile":{"operating_system": null,"os_release":"6","arch":"x86_64","cores_per_socket":2,"infrastructure_type":"virtual","system_memory_bytes":33543999488,"number_of_sockets":2,"owner_id":"663b6f0d-cfe5-488e-aa14-24855c1275eb"},"stale_timestamp":"2023-01-26T16:28:48.956227664Z","reporter":"rhsm-conduit"},"platform_metadata":{"request_id":"5f30fac1-721f-41fd-8c0a-897a9ea4c653"}}

```

### CODE REVIEW

**Comment by ntkathole** [comment]
VERIFIED in EE

After this fix, Host with `distribution.version =""` is getting added to HBI successfully. 

While in stage, this throws warning

`[WARN ] [org.candlepin.subscriptions.conduit.inventory.InventoryService] - Invalid OperatingSystemVersion: found "" but should be in format "major.minor"`
 and Kafka throws `System profile does not conform to schema.\n'major' is a required`

Fix looks good to me, But there is a scenario if distribution.version is something other than int, example : "7Server" or "5-0", then I see error in sync conduit. I see same errors in prod as well.

```
2023-06-02 08:28:52,768 [thread=http-nio-9000-exec-4] [ERROR] [org.candlepin.subscriptions.conduit.inventory.kafka.KafkaEnabledInventoryService] - Unable to send host create/update message.
java.lang.NumberFormatException: For input string: "5-0"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
```
Let me know if you think this needs different issue or can be handled in same PR.

**Comment by ksynvrit** [comment]
> VERIFIED in EE
> 
> After this fix, Host with `distribution.version =""` is getting added to HBI successfully.
> 
> While in stage, this throws warning
> 
> `[WARN ] [org.candlepin.subscriptions.conduit.inventory.InventoryService] - Invalid OperatingSystemVersion: found "" but should be in format "major.minor"` and Kafka throws `System profile does not conform to schema.\n'major' is a required`
> 
> Fix looks good to me, But there is a scenario if distribution.version is something other than int, example : "7Server" or "5-0", then I see error in sync conduit. I see same errors in prod as well.
> 
> ```
> 2023-06-02 08:28:52,768 [thread=http-nio-9000-exec-4] [ERROR] [org.candlepin.subscriptions.conduit.inventory.kafka.KafkaEnabledInventoryService] - Unable to send host create/update message.
> java.lang.NumberFormatException: For input string: "5-0"
> at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
> ```
> 
> Let me know if you think this needs different issue or can be handled in same PR.

I believe it can be handle in the same PR, my only question is. If the case for `5-0` is a probable string given as a Os_Version?

**Comment by ntkathole** [comment]
> I believe it can be handle in the same PR, my only question is. If the case for `5-0` is a probable string given as a Os_Version?

Original value in system is "7.5-0.14", but there are also some cases such as "unknown", "7Server". I think we should just add a fallback to not break in case distribution.version is not in the X or X.Y format.

**Comment by ksynvrit** [comment]
Will add new logic to handle to  

> > I believe it can be handle in the same PR, my only question is. If the case for `5-0` is a probable string given as a Os_Version?
> 
> Original value in system is "7.5-0.14", but there are also some cases such as "unknown", "7Server". I think we should just add a fallback to not break in case distribution.version is not in the X or X.Y format.

I have added additional logic to capture extra cases, review again at your convenients

**Review by ntkathole — APPROVED** [review]
Tested with updated version. Looks good to me 👍 
Added coverage in `iqe tests plugin rhsm_subscriptions -k test_empty_operating_system_release_version`

**Pull request merged**
