### PR TITLE
ENT-3627: Fix Daily Metric Tally Increases

### PR DESCRIPTION
**Pull request by mstead**
Daily snapshot values increase when the date changes. Properly set the
dates when updating instance measurements.

## Testing

```bash
# Start with a clean deployment.
$ podman-compose down; podman-compose up -d

# Deploy the application connected to a Telemeter instance (PROM_URL)
$ DEV_MODE=true  PROM_URL="http://localhost:8082/api/v1" ./gradlew clean bootRun

# Opt-in account: 6661312
$ curl 'http://localhost:8080/actuator/hawtio/jolokia/' -H 'Content-Type: application/json' -d '{"type":"exec","mbean":"org.candlepin.subscriptions.jmx:name=optInJmxBean,type=OptInJmxBean","operation":"createOrUpdateOptInConfig(java.lang.String,java.lang.String,boolean,boolean,boolean)","arguments":["6661312","123456",true,true,true]}'

# Gather metrics for an account: 6661312
$ curl 'http://localhost:8080/actuator/hawtio/jolokia/' -H 'Content-Type: application/json' -d '{"type":"exec","mbean":"org.candlepin.subscriptions.metering.jmx:name=openshiftJmxBean,type=OpenShiftJmxBean","operation":"performCustomOpenshiftMeteringForAccount(java.lang.String, java.lang.String, java.lang.Integer)","arguments":["6661312", "2021-03-19T16:00:00Z", 5760]}'

# No real report data
$ curl -H "x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6IjY2NjEzMTIiLCAiaW50ZXJuYWwiOnsib3JnX2lkIjoiMTIzNDU2In19fQ==" "http://localhost:8080/api/rhsm-subscriptions/v1/tally/products/OpenShift-metrics?granularity=daily&beginning=2021-03-16T00:00:00.000Z&ending=2021-03-17T23:59:59.999Z" | python -mjson.tool

# Run the hourly tally and verify you get an IllegalArguementException due to dates.
$ curl 'http://localhost:8080/actuator/hawtio/jolokia/' -H 'Content-Type: application/json' -d '{"type":"exec","mbean":"org.candlepin.subscriptions.jmx:name=tallyJmxBean,type=TallyJmxBean","operation":"tallyAccountByHourly(java.lang.String,java.lang.String,java.lang.String)","arguments":["6661312", "2021-03-16T14:50:03.711582Z", "2021-03-17T14:50:03.711582Z"]}'

# Run a valid tally
$ curl 'http://localhost:8080/actuator/hawtio/jolokia/' -H 'Content-Type: application/json' -d '{"type":"exec","mbean":"org.candlepin.subscriptions.jmx:name=tallyJmxBean,type=TallyJmxBean","operation":"tallyAccountByHourly(java.lang.String,java.lang.String,java.lang.String)","arguments":["6661312", "2021-03-16T14:00Z", "2021-03-17T15:00Z"]}'

# Check the core_hours numbers again and you should have real values.
$ curl -H "x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6IjY2NjEzMTIiLCAiaW50ZXJuYWwiOnsib3JnX2lkIjoiMTIzNDU2In19fQ==" "http://localhost:8080/api/rhsm-subscriptions/v1/tally/products/OpenShift-metrics?granularity=daily&beginning=2021-03-16T00:00:00.000Z&ending=2021-03-17T23:59:59.999Z" | python -mjson.tool

# Run the tally again, and because it detected a re-tally, it will process from the start of the month, picking up any that were out of range on the first attempt.
$ curl 'http://localhost:8080/actuator/hawtio/jolokia/' -H 'Content-Type: application/json' -d '{"type":"exec","mbean":"org.candlepin.subscriptions.jmx:name=tallyJmxBean,type=TallyJmxBean","operation":"tallyAccountByHourly(java.lang.String,java.lang.String,java.lang.String)","arguments":["6661312", "2021-03-16T14:00Z", "2021-03-17T15:00Z"]}'

# Get a daily report and notice the numbers go up. This is correct because of new data.
$ curl -H "x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6IjY2NjEzMTIiLCAiaW50ZXJuYWwiOnsib3JnX2lkIjoiMTIzNDU2In19fQ==" "http://localhost:8080/api/rhsm-subscriptions/v1/tally/products/OpenShift-metrics?granularity=daily&beginning=2021-03-16T00:00:00.000Z&ending=2021-03-17T23:59:59.999Z" | python -mjson.tool

# Do another tally shifting the start date ahead to miss some hours. End result should be same as the report above, and not increase.
$ curl 'http://localhost:8080/actuator/hawtio/jolokia/' -H 'Content-Type: application/json' -d '{"type":"exec","mbean":"org.candlepin.subscriptions.jmx:name=tallyJmxBean,type=TallyJmxBean","operation":"tallyAccountByHourly(java.lang.String,java.lang.String,java.lang.String)","arguments":["6661312", "2021-03-16T20:00Z", "2021-03-17T15:00Z"]}'
```

### CODE REVIEW

**Review by dmckoske — APPROVED** [review]
Looks good to me.  There are some good examples here on how to use clock objects for tallies.  It seems whenever we use now(), we get into trouble, especially without truncating it by hour.

**Review by kahowell — CHANGES_REQUESTED** [review]
A few requests we discussed:
- [x] don't adjust the times when we're not re-tallying
- [x] validate at the beginning of the method that start time and end time are at the top of the hour (throw IllegalArgumentException otherwise)
- [x] validate the Tally hourly JMX params to ensure they stop and end at the top of the hour (throw IllegalArgumentException otherwise)

**Comment by awood** [comment]
tumblr_mof769z9nL1qg4blro3_500

**Comment by mstead** [comment]
@kahowell Addressed your feedback. Please take another look.

**Review by kahowell — APPROVED** [review]

**Pull request merged**
