### PR TITLE
Swatch-2413: billable usage aggregation flush

### PR DESCRIPTION
**Pull request by kflahert**
Jira issue: SWATCH-2413

### Setup

1. Start swatch-billable-usage service: `KSTREAM_BILLABLE_USAGE_AGGREGATION_WINDOW_DURATION=10s KSTREAM_BILLABLE_USAGE_AGGREGATION_GRACE_DURATION=2s`
2. Publish a message to platform.rhsm-subscriptions.billable-usage topic: `{"org_id":"org123","billing_provider":"azure","billing_account_id":"testAzureTenantId;testAzureSubscriptionId1","snapshot_date":"2024-01-24T17:00:19.007433Z","product_id":"rhel-for-x86-els-payg","sla":"Premium","usage":"Production","uom":"vCPUs","value":"3.0"} `

### Steps

1. Wait at least 12 seconds and then run http command to call new internal endpoint:
`http PUT :8000/api/swatch-billable-usage/internal/rpc/topics/flush`

### Verification

1. Check logs to see that the billable usage aggregate has been sent.

### CODE REVIEW

**Review by awood — APPROVED** [review]
Looks great.  Would you mind squashing when you merge?

**Comment by kflahert** [comment]
> Looks great. Would you mind squashing when you merge?

@awood thanks! Will do.

**Comment by san7ket** [comment]
@kflahert what would be flush timer for eph , i see it's hourly for all other env.

**Comment by kflahert** [comment]
> @kflahert what would be flush timer for eph , i see it's hourly for all other env.

@san7ket we can't set this low enough for EE since the minimum for a cron job is 1 min, so we'd still need to setup IQE to call this API.

**Comment by san7ket** [comment]
```
In [41]:     billing_account_id = "test" + fauxfactory.gen_alpha(3).lower()
    ...:     billing_provider = "aws"
    ...:     application.rhsm_subscriptions.create_mock_subscription(
    ...:         product_id=product_id,
    ...:         billing_provider=billing_provider,
    ...:         billing_account_id=billing_account_id,
    ...:         start_day=(datetime.date.today() - datetime.timedelta(days=10)).strftime("%Y-%m-%d"),
    ...:     )
2024-04-17 09:47:38.424 [    INFO] [root] SKUs for rhel-for-x86-els-payg : ['RH02781HR']
2024-04-17 09:47:38.954 [    INFO] [root] PUT request response url: http://swatch-subscription-sync-service:8000/api/rhsm-subscriptions/v1/internal/rpc/offerings/sync/RH02781HR, status_code: 200
2024-04-17 09:47:38.954 [    INFO] [root] Response: {
    "detail": "syncResult=SKIPPED_MATCHING (Upstream matches stored item, did not sync) for offeringSku=\"RH02781HR\"."
}
2024-04-17 09:47:38.955 [    INFO] [root] Offering RH02781HR synced.
2024-04-17 09:47:38.988 [    INFO] [root] POST request response url: http://swatch-subscription-sync-service:8000/api/rhsm-subscriptions/v1/internal/subscriptions?reconcileCapacity=true, status_code: 200
2024-04-17 09:47:38.988 [    INFO] [root] Response: {
    "detail": "Success"
}
Out[41]: 
[{'id': '932679',
  'subscriptionNumber': '9601552',
  'subscriptionProducts': [{'sku': 'RH02781HR'}],
  'webCustomerId': '17790804',
  'quantity': 1,
  'oracleAccountNumber': '',
  'effectiveStartDate': 1712448913906.0,
  'effectiveEndDate': 1744848913906.0,
  'externalReferences': {'awsMarketplace': {'accountID': None,
    'subscriptionID': None,
    'customerID': 'testgqm',
    'productCode': 'testProductCode',
    'sellerAccount': '1234567',
    'customerAccountID': 'testgqm'}}}]

In [42]: value = random.randint(1, 20)
    ...: hours_value = random.randint(1, 5)
    ...: data = {
    ...:     metric.lower(): value,
    ...:     "billing_provider": billing_provider,
    ...:     "billing_account_id": billing_account_id,
    ...:     "hours": hours_value,
    ...:     "event_source": "cost-management",
    ...: }
    ...: # Create Payg host with help of Kafka record
    ...: host_instance = application.rhsm_subscriptions.create_metering_event(
    ...:     product_id=product_id, **data
    ...: )
In [44]: application.rhsm_subscriptions.sync_tally_hourly(
    ...:     product_id=product_id, perform_metering=False, wait=True, wait_for_remittance=True
    ...: )
2024-04-17 09:48:39.298 [    INFO] [root] GET request response url: http://swatch-tally-service:8000/api/rhsm-subscriptions/v1/internal/remittance/accountRemittances?productId=rhel-for-x86-els-payg&orgId=17790804&metric_id=vCPUs, status_code: 200
2024-04-17 09:48:39.298 [    INFO] [root] Response: [
    {
        "accumulationPeriod": "2024-04",
        "billingAccountId": "testgqm",
        "billingProvider": "aws",
        "metricId": "vCPUs",
        "orgId": "17790804",
        "productId": "rhel-for-x86-els-payg",
        "remittanceDate": "2024-04-17T09:48:24.936728Z",
        "remittedValue": 65.0
    }
]

In [45]: flush = call_internal_rest_api(app="swatch-billable-usage", endpoint="/internal/rpc/topics/flush",method="PUT")
2024-04-17 09:48:53.722 [    INFO] [root] PUT request response url: http://swatch-billable-usage-service:8000/api/swatch-billable-usage/internal/rpc/topics/flush, status_code: 200
2024-04-17 09:48:53.722 [    INFO] [root] Response: {
    "status": "Success"
}
In [45]: flush = call_internal_rest_api(app="swatch-billable-usage", endpoint="/internal/rpc/topics/flush",method="PUT")
2024-04-17 09:48:53.722 [    INFO] [root] PUT request response url: http://swatch-billable-usage-service:8000/api/swatch-billable-usage/internal/rpc/topics/flush, status_code: 200
2024-04-17 09:48:53.722 [    INFO] [root] Response: {
    "status": "Success"
}

{"timestamp":"2024-04-17T09:48:54.443540875Z","sequence":286,"loggerClassName":"org.slf4j.impl.Slf4jLogger","loggerName":"com.redhat.swatch.aws.processors.BillableUsageAggregateProcessor","level":"DEBUG","message":"Picked up billable usage message BillableUsageAggregate(totalValue=65.0, windowTimestamp=2024-04-17T09:00Z, aggregateId=a7dbe443-a901-4e39-9e7f-18429d22b928, aggregateKey=BillableUsageAggregateKey(orgId=17790804, productId=rhel-for-x86-els-payg, metricId=VCPUS, sla=Premium, usage=Production, billingProvider=aws, billingAccountId=testgqm), snapshotDates=[2024-04-17T09:48:24.876406793Z, 2024-04-17T09:48:24.896493144Z, 2024-04-17T09:48:24.936727679Z, 2024-04-17T09:48:24.917355792Z, 2024-04-17T09:48:24.855465842Z]) to process","threadName":"executor-thread-1","threadId":20,"mdc":{"spanId":"edaee03addcd2403","traceId":"06fe8674053e6d1d4127b3911b4fbb0d","sampled":"true"},"ndc":"","hostName":"swatch-producer-aws-service-57cc5db4c7-946s6","processName":"quarkus-run.jar","processId":1}
{"timestamp":"2024-04-17T09:48:54.753266259Z","sequence":287,"loggerClassName":"org.slf4j.impl.Slf4jLogger","loggerName":"com.redhat.swatch.aws.processors.BillableUsageAggregateProcessor","level":"INFO","message":"Sending usage request to AWS: BatchMeterUsageRequest(UsageRecords=[UsageRecord(Timestamp=2024-04-17T09:00:00Z, CustomerIdentifier=testgqm, Dimension=vCPU_hours, Quantity=65)], ProductCode=testProductCode), organization=17790804, product_id=rhel-for-x86-els-payg","threadName":"executor-thread-1","threadId":20,"mdc":{"org_id":"17790804","spanId":"edaee03addcd2403","traceId":"06fe8674053e6d1d4127b3911b4fbb0d","sampled":"true"},"ndc":"","hostName":"swatch-producer-aws-service-57cc5db4c7-946s6","processName":"quarkus-run.jar","processId":1}
{"timestamp":"2024-04-17T09:48:55.5029682Z","sequence":288,"loggerClassName":"org.slf4j.impl.Slf4jLogger","loggerName":"com.redhat.swatch.aws.processors.BillableUsageAggregateProcessor","level":"DEBUG","message":"BatchMeterUsageResponse(Results=[UsageRecordResult(UsageRecord=UsageRecord(Timestamp=2024-04-17T09:00:00Z, CustomerIdentifier=testgqm, Dimension=vCPU_hours, Quantity=65), MeteringRecordId=6f6d3f071fd145f68b6f2be11d2c135c, Status=CustomerNotSubscribed)], UnprocessedRecords=[])","threadName":"executor-thread-1","threadId":20,"mdc":{"org_id":"17790804","spanId":"edaee03addcd2403","traceId":"06fe8674053e6d1d4127b3911b4fbb0d","sampled":"true"},"ndc":"","hostName":"swatch-producer-aws-service-57cc5db4c7-946s6","processName":"quarkus-run.jar","processId":1}
{"timestamp":"2024-04-17T09:48:55.504395597Z","sequence":289,"loggerClassName":"org.slf4j.impl.Slf4jLogger","loggerName":"com.redhat.swatch.aws.processors.BillableUsageAggregateProcessor","level":"WARN","message":"No subscription found for organization=17790804, product_id=rhel-for-x86-els-payg, result=UsageRecordResult(UsageRecord=UsageRecord(Timestamp=2024-04-17T09:00:00Z, CustomerIdentifier=testgqm, Dimension=vCPU_hours, Quantity=65), MeteringRecordId=6f6d3f071fd145f68b6f2be11d2c135c, Status=CustomerNotSubscribed)","threadName":"executor-thread-1","threadId":20,"mdc":{"org_id":"17790804","spanId":"edaee03addcd2403","traceId":"06fe8674053e6d1d4127b3911b4fbb0d","sampled":"true"},"ndc":"","hostName":"swatch-producer-aws-service-57cc5db4c7-946s6","processName":"quarkus-run.jar","processId":1}

In [46]: application.rhsm_subscriptions.get_moto_aws_billing(reset_moto=False)
2024-04-17 09:53:06.627 [    INFO] [root] AWS moto Usage: [{'Timestamp': 1713344400.0, 'CustomerIdentifier': 'testgqm', 'Dimension': 'vCPU_hours', 'Quantity': 65}]
Out[46]: 
[{'Timestamp': 1713344400.0,
  'CustomerIdentifier': 'testgqm',
  'Dimension': 'vCPU_hours',
  'Quantity': 65}]


```

**Pull request merged**
