### PR TITLE
SWATCH-1365: Add FK relationship between Offering and Subscription

### PR DESCRIPTION
**Pull request by awood**
Adding the FK relationship allows us to remove a cross join that we needed to perform between the offering and subscription tables that had poor performance compared to an inner join.

Also set orphan-removal true on relationship between Subscription and SubscriptionMeasurement.

Jira issue: [SWATCH-1365](https://issues.redhat.com/browse/SWATCH-1365)

### Setup

1. Save the following as `manualJoin.patch`
   ```patch
   diff --git a/src/test/java/org/candlepin/subscriptions/db/SubscriptionMeasurementRepositoryTest.java b/src/test/java/org/candlepin/subscriptions/db/SubscriptionMeasurementRepositoryTest.java
   index e624fb98..c47b29d2 100644
   --- a/src/test/java/org/candlepin/subscriptions/db/SubscriptionMeasurementRepositoryTest.java
   +++ b/src/test/java/org/candlepin/subscriptions/db/SubscriptionMeasurementRepositoryTest.java
   @@ -39,6 +39,8 @@ import org.candlepin.subscriptions.db.model.Usage;
    import org.candlepin.subscriptions.utilization.api.model.MetricId;
    import org.junit.jupiter.api.BeforeEach;
    import org.junit.jupiter.api.Test;
   +import org.slf4j.Logger;
   +import org.slf4j.LoggerFactory;
    import org.springframework.beans.factory.annotation.Autowired;
    import org.springframework.boot.test.context.SpringBootTest;
    import org.springframework.test.context.ActiveProfiles;
   @@ -92,6 +94,19 @@ class SubscriptionMeasurementRepositoryTest {
        subscriptionRepository.saveAndFlush(subscription);
      }
    
   +  private static final Logger log =
   +      LoggerFactory.getLogger(SubscriptionMeasurementRepositoryTest.class);
   +
   +  @Test
   +  void manualJoinTest() {
   +    var specification =
   +        SubscriptionMeasurementRepository.slaEquals(ServiceLevel.PREMIUM).and(SubscriptionMeasurementRepository.usageEquals(Usage.PRODUCTION));
   +
   +    log.info("BEGIN TEST");
   +    var result = subscriptionMeasurementRepository.findAll(specification);
   +    assertThat(result, contains(physicalCores));
   +  }
   +
      @Test
      void testSimpleFetch() {
        var subscriptionId = new SubscriptionCompoundId();
   diff --git a/swatch-core-test/src/main/resources/application-test.yaml b/swatch-core-test/src/main/resources/application-test.yaml
   index f72bb574..4331148c 100644
   --- a/swatch-core-test/src/main/resources/application-test.yaml
   +++ b/swatch-core-test/src/main/resources/application-test.yaml
   @@ -34,10 +34,14 @@ logging:
      level:
        org:
          candlepin: INFO
   +      hibernate:
   +        type: TRACE
    spring:
      jpa:
   +    show-sql: true
        properties:
          hibernate:
   +        format_sql: true
            jdbc:
              # Force the testing database into UTC to prevent test failures when the database
              # determines the 'current' time in a query. NOTE: This is primarily when tests
   ```

### Steps

1. `git checkout main && patch -p1 < manualJoin.patch`
1. `./gradlew :test -i --tests=SubscriptionMeasurementRepositoryTest.manualJoinTest`
1. Observe the output after the log line reading `BEGIN TEST`.  The query has **two** cross joins on `offering1_` and `offering2_`.  The wrapping is a bit weird in the Hibernate output but the `cross` directive is associated with the `join` on the subsequent line.
   ```sql
   select
       subscripti0_.measurement_type as measurem1_13_0_,
       subscripti0_.metric_id as metric_i2_13_0_,
       subscripti0_.start_date as start_da0_13_0_,
       subscripti0_.subscription_id as subscrip0_13_0_,
       subscripti3_.start_date as start_da1_12_1_,
       subscripti3_.subscription_id as subscrip2_12_1_,
       subscripti0_.start_date as start_da4_13_0_,
       subscripti0_.subscription_id as subscrip5_13_0_,
       subscripti0_.value as value3_13_0_,
       subscripti3_.account_number as account_3_12_1_,
       subscripti3_.billing_account_id as billing_4_12_1_,
       subscripti3_.billing_provider as billing_5_12_1_,
       subscripti3_.billing_provider_id as billing_6_12_1_,
       subscripti3_.end_date as end_date7_12_1_,
       subscripti3_.has_unlimited_usage as has_unli8_12_1_,
       subscripti3_.org_id as org_id9_12_1_,
       subscripti3_.quantity as quantit10_12_1_,
       subscripti3_.sku as sku11_12_1_,
       subscripti3_.subscription_number as subscri12_12_1_
   from
       subscription_measurements subscripti0_ cross
   join
       offering offering1_ cross
   join
       offering offering2_
   inner join
       subscription subscripti3_
           on subscripti0_.start_date=subscripti3_.start_date
           and subscripti0_.subscription_id=subscripti3_.subscription_id
   where
       subscripti3_.sku=offering1_.sku  
       and offering1_.sla=?
       and subscripti3_.sku=offering2_.sku
       and offering2_.usage=?
   ```

### Verification

1. `git checkout origin/awood/SWATCH-1365-slow-query && patch -p1 < manualJoin.patch`
1. `./gradlew :test -i --tests=SubscriptionMeasurementRepositoryTest.manualJoinTest`
1. The select query is now devoid of any cross joins                                                                                                                             
   ```sql                                                                                                                                                                        
   select                                                                                                                                                                        
       subscripti0_.measurement_type as measurem1_13_0_,                                                                                                                         
       subscripti0_.metric_id as metric_i2_13_0_,                                                                                                                                
       subscripti0_.start_date as start_da0_13_0_,                                                                                                                               
       subscripti0_.subscription_id as subscrip0_13_0_,                                                                                                                                 subscripti1_.start_date as start_da1_12_1_,                                                                                                                               
       subscripti1_.subscription_id as subscrip2_12_1_,                                                                                                                          
       offering2_.sku as sku1_8_2_,                                                                                                                                              
       subscripti0_.start_date as start_da4_13_0_,                                                                                                                               
       subscripti0_.subscription_id as subscrip5_13_0_,                                                                                                                          
       subscripti0_.value as value3_13_0_,                                                                                                                                       
       subscripti1_.account_number as account_3_12_1_,                                                                                                                           
       subscripti1_.billing_account_id as billing_4_12_1_,                                                                                                                       
       subscripti1_.billing_provider as billing_5_12_1_,                                                                                                                         
       subscripti1_.billing_provider_id as billing_6_12_1_,                                                                                                                      
       subscripti1_.end_date as end_date7_12_1_,                                                                                                                                 
       subscripti1_.sku as sku11_12_1_,                                                                                                                                          
       subscripti1_.org_id as org_id8_12_1_,                                                                                                                                     
       subscripti1_.quantity as quantity9_12_1_,                                                                                                                                 
       subscripti1_.subscription_number as subscri10_12_1_,                                                                                                                      
       offering2_.cores as cores2_8_2_,                                                                                                                                          
       offering2_.derived_sku as derived_3_8_2_,                                                                                                                                 
       offering2_.description as descript4_8_2_,                                                                                                                                 
       offering2_.has_unlimited_usage as has_unli5_8_2_,                                                                                                                         
       offering2_.hypervisor_cores as hypervis6_8_2_,                                                                                                                            
       offering2_.hypervisor_sockets as hypervis7_8_2_,                                                                                                                          
       offering2_.product_family as product_8_8_2_,                                                                                                                              
       offering2_.product_name as product_9_8_2_,                                                                                                                                
       offering2_.role as role10_8_2_,                                                                                                                                           
       offering2_.sla as sla11_8_2_,                                                                                                                                             
       offering2_.sockets as sockets12_8_2_,                                                                                                                                     
       offering2_.usage as usage13_8_2_                                                                                                                                          
   from                                                                                                                                                                          
       subscription_measurements subscripti0_                                                                                                                                    
   inner join                                                                                                                                                                    
       subscription subscripti1_                                                                                                                                                 
           on subscripti0_.start_date=subscripti1_.start_date                                                                                                                    
           and subscripti0_.subscription_id=subscripti1_.subscription_id                                                                                                         
   inner join                                                                                                                                                                    
       offering offering2_                                                                                                                                                       
           on subscripti1_.sku=offering2_.sku                                                                                                                                    
   where                                                                                                                                                                         
       offering2_.sla=?                                                                                                                                                          
       and offering2_.usage=?                                                                                                                                                    
   ```

### CODE REVIEW

**Review by kflahert — APPROVED** [review]

**Comment by kahowell** [comment]
@awood can you please apply the same data-model changes to the entities defined in `swatch-contracts`?

**Pull request merged**
