### PR TITLE
SWATCH-2346: Also check dmi.bios.vendor for aws host detection

### PR DESCRIPTION
**Pull request by wottop**
Jira issue: SWATCH-2346

## Description
Added check of dmi.bios.vendor in addtion to dmi.bios.version to determine if the host is aws. Some fact sets now have the needed information in this other fact.

## Testing
Covered by a unit test

### Verification
1. A unit test run
2. Use a consumer that has the alternative field and confirm that its cloud provider value is 'aws'

### CODE REVIEW

**Review by Sgitario — APPROVED** [review]

**Comment by wottop** [comment]
Note IQE tests here: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/630

**Review by TrayvonMcKnight — APPROVED** [review]

**Pull request merged**
