### PR TITLE
SWATCH-1912: Remove deprecated GET /capacity/products/{product_id}

### PR DESCRIPTION
**Pull request by Sgitario**
Jira issue: [SWATCH-1912](https://issues.redhat.com/browse/SWATCH-1912)

## Description
The endpoint "/capacity/products/{product_id}" was marked as deprecated a while ago.
Use /capacity/products/{product_id}/{metric_id} instead.

### CODE REVIEW

**Review by awood — APPROVED** [review]
So happy to get this done!  :man_dancing:

**Review by ssidhaye — APPROVED** [review]

**Pull request merged**
