### PR TITLE
SWATCH-1729: Refactor swatch-tally Job to use curl and internal endpoint

### PR DESCRIPTION
**Pull request by Sgitario**
Jira issue: [SWATCH-1729](https://issues.redhat.com/browse/SWATCH-1729)

## Description
For all cronjobs defined in clowdapps, we should migrate to using k8s cronjobs w/ curl against internal endpoints.

## Testing
Confirm that the endpoint is executed every day at 6:00.
Alternatively, you can deploy the application and overwrite the CAPTURE_SNAPSHOT_SCHEDULE environment property with `CAPTURE_SNAPSHOT_SCHEDULE=*/5 * * * *` (every 5 min).

In the logs of the job created, you should see:

```
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0100 20 100 20 0 0 75 0 --:--:-- --:--:-- --:--:-- 75
{"status":"Success"}
```

And in the logs of the swatch tally service:

```
2023-09-18 10:41:50,978 [thread=main] [INFO ] [org.candlepin.subscriptions.BootApplication] - Started BootApplication in 44.981 seconds (process running for 46.953)
2023-09-18 10:48:02,825 [thread=http-nio-8000-exec-1] [INFO ] [org.candlepin.subscriptions.security.LogPrincipalFilter] self- Internal API: /api/rhsm-subscriptions/v1/internal/rpc/tally/all-org-snapshots requested by user: self
2023-09-18 10:48:02,878 [thread=http-nio-8000-exec-1] [INFO ] [org.candlepin.subscriptions.tally.admin.InternalTallyResource] self- Tally for all orgs triggered over API by self
2023-09-18 10:48:02,987 [thread=http-nio-8000-exec-1] [INFO ] [org.candlepin.subscriptions.tally.job.CaptureSnapshotsTaskManager] self- Queuing all org snapshot production in batches of size one
2023-09-18 10:48:02,995 [thread=http-nio-8000-exec-1] [INFO ] [org.candlepin.subscriptions.tally.job.CaptureSnapshotsTaskManager] self- Done queuing snapshot production for 0 org list.
```

So, the call was made and we confirmed that the service processed it.

### CODE REVIEW

**Review by kflahert — APPROVED** [review]

**Review by ssidhaye — APPROVED** [review]
After setting update cron schedule to run every 5 mins, I see the following lines in swatch-tally log:

```
2023-09-21 07:03:18,627 [thread=main] [INFO ] [org.candlepin.subscriptions.BootApplication] - Started BootApplication in 35.747 seconds (process running for 37.324)
2023-09-21 07:29:33,460 [thread=http-nio-8000-exec-1] [INFO ] [org.candlepin.subscriptions.security.LogPrincipalFilter] self- Internal API: /api/rhsm-subscriptions/v1/internal/rpc/tally/all-org-snapshots requested by user: self
2023-09-21 07:29:33,519 [thread=http-nio-8000-exec-1] [INFO ] [org.candlepin.subscriptions.tally.admin.InternalTallyResource] self- Tally for all orgs triggered over API by self
2023-09-21 07:29:33,618 [thread=http-nio-8000-exec-1] [INFO ] [org.candlepin.subscriptions.tally.job.CaptureSnapshotsTaskManager] self- Queuing all org snapshot production in batches of size one
2023-09-21 07:29:33,625 [thread=http-nio-8000-exec-1] [INFO ] [org.candlepin.subscriptions.tally.job.CaptureSnapshotsTaskManager] self- Done queuing snapshot production for 0 org list.
```

Based on above observations LGTM

**Pull request merged**
