### PR TITLE
SWATCH-1462: Correct mismatch in monthly and running totals

### PR DESCRIPTION
**Pull request by awood**
Jira issue: [SWATCH-1462](https://issues.redhat.com/browse/SWATCH-1462)

### Setup

1. Create a clean database
   ```shell
   createdb -h localhost -U postgres -O rhsm-subscriptions swatch-1462
   ```
2.  Download [SWATCH-1462.zip](https://github.com/RedHatInsights/rhsm-subscriptions/files/12432199/SWATCH-1462.zip) and import it into your database
    ```shell
    zcat SWATCH-1462.zip | psql -h localhost -U rhsm-subscriptions swatch-1462
    ```

### Steps

1.  Deploy the `main` branch with 
    ```shell
    DATABASE_DATABASE=swatch-1462 ./gradlew :bootRun
    ```
2.  I didn't export the `instance_monthly_total` records, but the underlying instances look like
   ```json
    {"data": [
    {
      "id": "1dce12a3-369f-4b4b-aea6-afb119c4f57c",
      "instance_id": "a7730436-5e1c-4122-ad93-a7316ab8fb46",
      "display_name": "automation_moa-hostedcontrolplane_cluster_a7730436-5e1c-4122-ad93-a7316ab8fb46",
      "billing_provider": "aws",
      "billing_account_id": "dom",
      "measurements": [
        3.09,
        12.93
      ],
      "last_seen": "2023-08-08T15:00:00Z",
      "number_of_guests": 0
    },
    {
      "id": "46faea67-b62e-44a3-9055-64171d5f6b8b",
      "instance_id": "191aa496-8f30-4f59-ab60-b341ecbde21f",
      "display_name": "automation_moa-hostedcontrolplane_cluster_191aa496-8f30-4f59-ab60-b341ecbde21f",
      "billing_provider": "aws",
      "billing_account_id": "dom",
      "measurements": [
        3.09,
        12.93
      ],
      "last_seen": "2023-08-02T11:00:00Z",
      "number_of_guests": 0
    },
    {
      "id": "6c09d816-e3b6-401a-92f4-9797edec5a3a",
      "instance_id": "55973b10-6cfe-435b-b33f-e99e1a7a224c",
      "display_name": "automation_moa-hostedcontrolplane_cluster_55973b10-6cfe-435b-b33f-e99e1a7a224c",
      "billing_provider": "aws",
      "billing_account_id": "dom",
      "measurements": [
        3.99,
        2.93
      ],
      "last_seen": "2023-08-07T15:00:00Z",
      "number_of_guests": 0
    },
    {
      "id": "81bd5ea1-f504-4385-95af-7087a1e42552",
      "instance_id": "9968f68a-885d-411c-a4b0-b1c0242b7f91",
      "display_name": "automation_moa-hostedcontrolplane_cluster_9968f68a-885d-411c-a4b0-b1c0242b7f91",
      "billing_provider": "aws",
      "billing_account_id": "dom",
      "measurements": [
        3.09,
        12.93
      ],
      "last_seen": "2023-08-09T13:00:00Z",
      "number_of_guests": 0
    }
  ],
  "meta": {
    "count": 4,
    "product": "rosa",
    "measurements": [
      "Cores",
      "Instance-hours"
    ]
  }}
   ```
3.  Gather a tally report
    ```shell
    http :8000/api/rhsm-subscriptions/v1/tally/products/rosa/Cores \
    granularity==Daily \
    beginning==2023-08-01T00:00:00.000Z \
    ending==2023-08-31T23:59:59.999Z \
    use_running_totals_format==true \
    x-rh-identity:$(echo -n '{"identity":{"account_number":"","type":"User","user":{"is_org_admin":true},"internal":{"org_id":"16788750"}}}' | base64 -w 0) 
    ```
4. Observe that the final running total value is 16 while the monthly total in the meta section is 14.  You get 16 if you run a `Math.ceil` on each cores measurement and 14 if you only run it after totaling all the measurements together.

### Verification

1.  Deploy the `awood/SWATCH-1462-total-mismatch` branch with 
    ```shell
    DATABASE_DATABASE=swatch-1462 ./gradlew :bootRun
    ```
2.  Run the tally report
    ```shell
    http :8000/api/rhsm-subscriptions/v1/tally/products/rosa/Cores \
    granularity==Daily \
    beginning==2023-08-01T00:00:00.000Z \
    ending==2023-08-31T23:59:59.999Z \
    use_running_totals_format==true \
    x-rh-identity:$(echo -n '{"identity":{"account_number":"","type":"User","user":{"is_org_admin":true},"internal":{"org_id":"16788750"}}}' | base64 -w 0) 
    ```
3. Observe that the final running total matches the monthly total.

### CODE REVIEW

**Comment by Sgitario** [comment]
I tried to follow these steps and the step "3. Gather a tally report" failed with:

```
2023-08-25 04:50:50,432 [thread=http-nio-8000-exec-2] [ERROR] [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost]] - Exception Processing ErrorPage[errorCode=0, location=/error]
jakarta.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8819 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Conexión rehusada
        at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:361)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:427)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:71)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.get(ClientInvocationBuilder.java:175)
        at org.candlepin.subscriptions.rbac.ApiClient.invoke(ApiClient.java:686)
        at org.candlepin.subscriptions.rbac.ApiClient.invokeAPI(ApiClient.java:651)
        at org.candlepin.subscriptions.rbac.RbacApiClient.invokeAPI(RbacApiClient.java:61)
```

Perhaps, we should include the RBAC service as part of the podman-compose start or should we disable some Spring profile when running the services locally?

**Comment by Sgitario** [comment]
> I tried to follow these steps and the step "3. Gather a tally report" failed with:
> 
> ```
> 2023-08-25 04:50:50,432 [thread=http-nio-8000-exec-2] [ERROR] [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost]] - Exception Processing ErrorPage[errorCode=0, location=/error]
> jakarta.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8819 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Conexión rehusada
>         at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:361)
>         at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:427)
>         at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:71)
>         at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.get(ClientInvocationBuilder.java:175)
>         at org.candlepin.subscriptions.rbac.ApiClient.invoke(ApiClient.java:686)
>         at org.candlepin.subscriptions.rbac.ApiClient.invokeAPI(ApiClient.java:651)
>         at org.candlepin.subscriptions.rbac.RbacApiClient.invokeAPI(RbacApiClient.java:61)
> ```
> 
> Perhaps, we should include the RBAC service as part of the podman-compose start or should we disable some Spring profile when running the services locally?

I think I figured it out myself. Running `DATABASE_DATABASE=swatch-1462 RHSM_RBAC_USE_STUB=true ./gradlew :bootRun` fixed it for me.

**Review by kahowell — APPROVED** [review]

**Comment by diegomaranhao** [comment]
I tested today again, and the same issue seems to persist. I added a comment on the Jira issue with more information.

**Comment by awood** [comment]
> I think I figured it out myself. Running `DATABASE_DATABASE=swatch-1462 RHSM_RBAC_USE_STUB=true ./gradlew :bootRun` fixed it for me.

Ah, yes.  I left that out.  I have that in a `config/application.properties` file (which is `.gitignore`d).  Just FYI here are some other common setting that I always run with.  I generally find them useful to have enabled as default for local development.

```properties
spring.profiles.active=api,kafka-queue,worker,rhsm-conduit,openshift-metering-worker,capacity-ingress
#,metering-job

# Use the stub RBAC API
rhsm-subscriptions.rbac-service.useStub=true

# Run in development mode to disable security
rhsm-subscriptions.security.dev-mode=true

rhsm-subscriptions.security.anti-csrf-domain-suffix=localhost
rhsm-subscriptions.security.anti-csrf-port=8000
rhsm-subscriptions.security.manual-subscription-editing-enabled=true
rhsm-subscriptions.security.manual-event-editing-enabled=true
rhsm-subscriptions.security.reset-account-enabled=true

rhsm-subscriptions.enableSynchronousOperations=true

rhsm-subscriptions.subscription.enablePaygSubscriptionForceSync=true
rhsm-subscriptions.subscription.useStub=true
```
```

**Comment by diegomaranhao** [comment]
@TrayvonMcKnight will verify this PR, since I was not able to run EE on UI with this PR.

**Review by TrayvonMcKnight — APPROVED** [review]
https://drive.google.com/file/d/1SVg36JNufUCrGKXMMONggD0giad7O8sn/view?usp=drive_link

**Pull request merged**
