### PR TITLE
SWATCH-2214: Synchronize orgs in conduit using tasks

### PR DESCRIPTION
**Pull request by Sgitario**
Jira issue: [SWATCH-2214](https://issues.redhat.com/browse/SWATCH-2214)

## Description
We will allow to enable a synchronous operation to sync the organization by skipping the Kafka queue by running the swatch conduit with ENABLE_SYNCHRONOUS_OPERATIONS=true, plus adding our standard "x-rh-swatch-synchronous-request" header when calling "/internal/rpc/syncOrg" endpoint.

## Testing
Added unit tests to cover this change.

### CODE REVIEW

**Comment by Sgitario** [comment]
> @Sgitario Need to enable async operations in EE and stage `Synchronous conduit operations are not enabled.`

Yes, I know this was the missing bit. I can do this after merging the pull request. However, you're not going to use the sync request, but the Kafka task instead, right?

**Comment by ntkathole** [comment]
> > @Sgitario Need to enable async operations in EE and stage `Synchronous conduit operations are not enabled.`
> 
> Yes, I know this was the missing bit. I can do this after merging the pull request. However, you're not going to use the sync request, but the Kafka task instead, right?

Currently we have enabled automation to use `x-rh-swatch-synchronous-request` true ... Are you suggesting to use `x-rh-swatch-use-thread-pool-executor` instead ?

**Comment by Sgitario** [comment]
> > > @Sgitario Need to enable async operations in EE and stage `Synchronous conduit operations are not enabled.`
> > 
> > 
> > Yes, I know this was the missing bit. I can do this after merging the pull request. However, you're not going to use the sync request, but the Kafka task instead, right?
> 
> Currently we have enabled automation to use `x-rh-swatch-synchronous-request` true ... Are you suggesting to use `x-rh-swatch-use-thread-pool-executor` instead ?

Using "x-rh-swatch-synchronous-request: true" is exactly how it was working before these changes and it will cause gateway timeout issues. 
You need to use x-rh-swatch-synchronous-request: false or not use any header to make it async.

**Review by kflahert — APPROVED** [review]

**Review by ntkathole — APPROVED** [review]

**Pull request merged**
