### PR TITLE
Add pod level memory widget for the tally services

### PR DESCRIPTION
**Pull request by barnabycourt**
The divide by 1000000 in the equation is to convert to Mi used by app-interface specification.

### CODE REVIEW

**Review by kahowell — CHANGES_REQUESTED** [review]
Instead of the divide, it's better to set `Unit` to `Data` -> `bytes(IEC)`

**Comment by barnabycourt** [comment]
I'm happy to consider bytes(IEC) but It doesn't seem to quite match. For example, 
Openshift Console shows: 2.53 GB
Grafana using divide by 1000000: 2556
Grafana using bytes(IEC): 2.38 GB
Grafana using bytes(SI): 2.56 GB

It looks like bytes(SI) is closer. I'd rather over-estimate on our dashboard than under-estimate.  @kahowell what do you think?

**Comment by kahowell** [comment]
@barnabycourt let's take a look at this tomorrow some time. It looks like IEC on my end, unless you click in to the generic prometheus query UI.

I also prefer IEC as we've been specifying our memory request/limits in IEC units.

**Comment by barnabycourt** [comment]
I updated to use IEC memory unit and set the max value of the graph to the current quote limit per conversation with @kahowell

**Review by kahowell — APPROVED** [review]

**Pull request merged**
