### PR TITLE
ENT-3266: Add MarketplaceWorker and template

### PR DESCRIPTION
**Pull request by kahowell**
Note that the payload mapper is currently stubbed out. Temporarily, `MARKETPLACE_MAPPER_STUB_EMPTY` (default true) controls whether the payload emitted is empty or not.

Testing
-------

Run via 
```
MARKETPLACE_MAPPER_STUB_EMPTY=false MARKETPLACE_MAX_ATTEMPTS=1 DEV_MODE=true MARKETPLACE_URL=http://localhost:8088/does-not-exist ./gradlew bootRun
```

Insert some events:

```sql
INSERT INTO events (id, account_number, timestamp, data, event_type, event_source, instance_id) VALUES ('1edc517a-d049-4361-9804-e4111ce061ae', 'account123', '2021-03-10 19:00:00.000000', '{"role":"ocp","sla": "Premium", "usage": "Development/Test", "event_id": "1edc517a-d049-4361-9804-e4111ce061ae", "timestamp": "2021-03-10T19:00:00Z", "event_type": "snapshot", "expiration": "2021-03-10T20:00:00Z", "instance_id": "c6123fbb-84d0-47a7-b069-ff9048caf7c7", "display_name": "c6123fbb-84d0-47a7-b069-ff9048caf7c7", "event_source": "prometheus-openshift", "measurements": [{"uom": "Cores", "value": 12.0}], "service_type": "OpenShift Cluster", "account_number": "account123"}', 'snapshot', 'prometheus-openshift', 'c6123fbb-84d0-47a7-b069-ff9048caf7c7');
INSERT INTO events (id, account_number, timestamp, data, event_type, event_source, instance_id) VALUES ('9fd69ad7-9294-4d8d-a5f4-c5ca45bdb2ec', 'account123', '2021-03-10 19:00:00.000000', '{"role":"ocp","sla": "Standard", "usage": "Development/Test", "event_id": "9fd69ad7-9294-4d8d-a5f4-c5ca45bdb2ec", "timestamp": "2021-03-10T19:00:00Z", "event_type": "snapshot", "expiration": "2021-03-10T20:00:00Z", "instance_id": "0e94471b-f9bb-4b30-8d6e-8ad6c3539392", "display_name": "0e94471b-f9bb-4b30-8d6e-8ad6c3539392", "event_source": "prometheus-openshift", "measurements": [{"uom": "Cores", "value": 12.0}], "service_type": "OpenShift Cluster", "account_number": "account123"}', 'snapshot', 'prometheus-openshift', '0e94471b-f9bb-4b30-8d6e-8ad6c3539392');
INSERT INTO events (id, account_number, timestamp, data, event_type, event_source, instance_id) VALUES ('91ef5257-6f44-4ad5-812e-ae070483e4a7', 'account123', '2021-03-10 20:00:00.000000', '{"role":"ocp","sla": "Premium", "usage": "Production", "event_id": "91ef5257-6f44-4ad5-812e-ae070483e4a7", "timestamp": "2021-03-10T20:00:00Z", "event_type": "snapshot", "expiration": "2021-03-10T21:00:00Z", "instance_id": "bdeffe2b-08c6-40ef-b2cf-e3c458a0273a", "display_name": "bdeffe2b-08c6-40ef-b2cf-e3c458a0273a", "event_source": "prometheus-openshift", "measurements": [{"uom": "Cores", "value": 12.0}], "service_type": "OpenShift Cluster", "account_number": "account123"}', 'snapshot', 'prometheus-openshift', 'bdeffe2b-08c6-40ef-b2cf-e3c458a0273a');
INSERT INTO events (id, account_number, timestamp, data, event_type, event_source, instance_id) VALUES ('a35a0f56-d46b-4c36-ad4b-e6e889e13c9f', 'account123', '2021-03-10 19:00:00.000000', '{"role":"ocp","sla": "Premium", "usage": "Production", "event_id": "a35a0f56-d46b-4c36-ad4b-e6e889e13c9f", "timestamp": "2021-03-10T19:00:00Z", "event_type": "snapshot", "expiration": "2021-03-10T20:00:00Z", "instance_id": "bdeffe2b-08c6-40ef-b2cf-e3c458a0273a", "display_name": "bdeffe2b-08c6-40ef-b2cf-e3c458a0273a", "event_source": "prometheus-openshift", "measurements": [{"uom": "Cores", "value": 12.0}], "service_type": "OpenShift Cluster", "account_number": "account123"}', 'snapshot', 'prometheus-openshift', 'bdeffe2b-08c6-40ef-b2cf-e3c458a0273a');
INSERT INTO events (id, account_number, timestamp, data, event_type, event_source, instance_id) VALUES ('0b021762-59e6-41ae-bbe6-e4ba1deaf3a1', 'account123', '2021-03-10 20:00:00.000000', '{"role":"ocp","sla": "Standard", "usage": "Development/Test", "event_id": "0b021762-59e6-41ae-bbe6-e4ba1deaf3a1", "timestamp": "2021-03-10T20:00:00Z", "event_type": "snapshot", "expiration": "2021-03-10T21:00:00Z", "instance_id": "0e94471b-f9bb-4b30-8d6e-8ad6c3539392", "display_name": "0e94471b-f9bb-4b30-8d6e-8ad6c3539392", "event_source": "prometheus-openshift", "measurements": [{"uom": "Cores", "value": 12.0}], "service_type": "OpenShift Cluster", "account_number": "account123"}', 'snapshot', 'prometheus-openshift', '0e94471b-f9bb-4b30-8d6e-8ad6c3539392');
INSERT INTO events (id, account_number, timestamp, data, event_type, event_source, instance_id) VALUES ('e223e90d-f567-4a4f-b05f-7ad9e67fe5c5', 'account123', '2021-03-10 20:00:00.000000', '{"role":"ocp","sla": "Premium", "usage": "Development/Test", "event_id": "e223e90d-f567-4a4f-b05f-7ad9e67fe5c5", "timestamp": "2021-03-10T20:00:00Z", "event_type": "snapshot", "expiration": "2021-03-10T21:00:00Z", "instance_id": "c6123fbb-84d0-47a7-b069-ff9048caf7c7", "display_name": "c6123fbb-84d0-47a7-b069-ff9048caf7c7", "event_source": "prometheus-openshift", "measurements": [{"uom": "Cores", "value": 12.0}], "service_type": "OpenShift Cluster", "account_number": "account123"}', 'snapshot', 'prometheus-openshift', 'c6123fbb-84d0-47a7-b069-ff9048caf7c7');
INSERT INTO events (id, account_number, timestamp, data, event_type, event_source, instance_id) VALUES ('922855da-29da-438f-b8c5-d2f3df7f62fd', 'account123', '2021-03-10 19:00:00.000000', '{"role":"osd","sla": "Premium", "usage": "Development/Test", "event_id": "922855da-29da-438f-b8c5-d2f3df7f62fd", "timestamp": "2021-03-10T19:00:00Z", "event_type": "snapshot", "expiration": "2021-03-10T20:00:00Z", "instance_id": "f418a78c-2099-4932-9ff2-135dabd09077", "display_name": "f418a78c-2099-4932-9ff2-135dabd09077", "event_source": "prometheus-openshift", "measurements": [{"uom": "Cores", "value": 12.0}], "service_type": "OpenShift Cluster", "account_number": "account123"}', 'snapshot', 'prometheus-openshift', 'f418a78c-2099-4932-9ff2-135dabd09077');
```

Trigger tally:

```
curl 'http://localhost:8080/actuator/hawtio/jolokia/' -H 'Content-Type: application/json' -d '{"type":"exec","mbean":"org.candlepin.subscriptions.jmx:name=tallyJmxBean,type=TallyJmxBean","operation":"tallyAccountByHourly(java.lang.String,java.lang.String,java.lang.String)","arguments":["account123","2021-03-10T00:00:00Z","2021-03-10T23:59:59.999Z"]}'
```

Verify via log activity:

```
2021-03-17 20:40:58,685 [thread=marketplace-worker-0-C-1] [INFO ] [org.candlepin.subscriptions.marketplace.MarketplaceWorker] - mapTallySummary called w/ summary: org.candlepin.subscriptions.json.TallySummary@786d6ad9[accountNumber=account123,tallySnapshots=[org.candlepin.subscriptions.json.TallySnapshot@3f06f070[id=a260e99d-b617-4dd9-9194-64717629b001,snapshotDate=2021-03-10T00:00Z,productId=OpenShift-metrics,sla=Premium,usage=<null>,granularity=Daily,tallyMeasurements=[org.candlepin.subscriptions.json.TallyMeasurement@640060bb[hardwareMeasurementType=PHYSICAL,uom=Cores,value=48.0], org.candlepin.subscriptions.json.TallyMeasurement@42f5afe2[hardwareMeasurementType=TOTAL,uom=Cores,value=48.0]]]]]
2021-03-17 20:40:58,686 [thread=marketplace-worker-0-C-1] [ERROR] [org.springframework.kafka.listener.SeekToCurrentErrorHandler] - Backoff FixedBackOff{interval=0, currentAttempts=10, maxAttempts=9} exhausted for ConsumerRecord(topic = platform.rhsm-subscriptions.tally, partition = 0, leaderEpoch = 0, offset = 246264, CreateTime = 1616013657687, serialized key size = -1, serialized value size = 361, headers = RecordHeaders(headers = [], isReadOnly = false), key = null, value = org.candlepin.subscriptions.json.TallySummary@786d6ad9[accountNumber=account123,tallySnapshots=[org.candlepin.subscriptions.json.TallySnapshot@3f06f070[id=a260e99d-b617-4dd9-9194-64717629b001,snapshotDate=2021-03-10T00:00Z,productId=OpenShift-metrics,sla=Premium,usage=<null>,granularity=Daily,tallyMeasurements=[org.candlepin.subscriptions.json.TallyMeasurement@640060bb[hardwareMeasurementType=PHYSICAL,uom=Cores,value=48.0], org.candlepin.subscriptions.json.TallyMeasurement@42f5afe2[hardwareMeasurementType=TOTAL,uom=Cores,value=48.0]]]]])
org.springframework.kafka.listener.ListenerExecutionFailedException: Listener method 'public void org.candlepin.subscriptions.marketplace.MarketplaceWorker.receive(org.candlepin.subscriptions.json.TallySummary)' threw exception; nested exception is javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request; nested exception is javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request
```

This shows that when the stubbed mapper emits a non-empty payload, the producer attempts to send it to the configured marketplace URL

You can also try with `MARKETPLACE_MAPPER_STUB_EMPTY=true` (or omitted) to see that when the mapper emits an empty payload, no interaction with Marketplace happens.

Testing on CI
-------------

First, ensure the version has been built by using the CI deploy job
against this branch.

Then:

```
oc process \
    -p KAFKA_BOOTSTRAP_HOST=KAFKA_BOOTSTRAP_HOST=platform-mq-ci-kafka-bootstrap.platform-mq-ci.svc.cluster.local \
    -p IMAGE=docker-registry.default.svc:5000/rhsm-ci/rhsm-subscriptions \
    -p IMAGE_TAG=$(git show --format=%h --no-patch --abbrev=7) \
    -p IMAGE_PULL_SECRET=default-dockercfg-bd4dv \
    -f templates/marketplace-worker.yml | oc -n rhsm-ci apply -f -
```

Then retrigger some tallies if needed, and verify as above, Note that *no* interaction with Marketplace API should happen, since the mapper is not yet implemented, and the stubbed mapper is configured to emit empty payloads.

### CODE REVIEW

**Comment by san7ket** [comment]
Will test this against the PR branch, and then revert ci back to develop branch

**Comment by kahowell** [comment]
@san7ket, I think it's sufficient for dev to test this as part of review. I'm not opposed to QE critiquing early either though :smile:.

**Comment by kahowell** [comment]
NOTE: whichever of this PR and #350 lands last should integrate the mapper with the worker (removing the stubbed mapper and the associated env var).

**Review by mstead — APPROVED** [review]
Overall, this looks good and leave a good integration point.

Deployed to CI and is chugging along processing summary messages.

**Pull request merged**
