### PR TITLE
Use same metricId for OCP (temporarily)

### PR DESCRIPTION
**Pull request by kahowell**
To unblock dev-instance of marketplace-worker

### CODE REVIEW

**Comment by ntkathole** [comment]
@kahowell  is https://sandbox.marketplace.redhat.com/en-us/products/openshift-container-platform-stage not useful ?

**Comment by kahowell** [comment]
@ntkathole once #369 lands, it'll be useful. In the super short term, we're mapping back to a single hard-coded subscription ID for testing purposes, so we need to choose either OCP or OSD.

**Comment by ntkathole** [comment]
ACK :+1:

**Review by dmckoske — APPROVED** [review]
Looks good.  Once this is checked in, I will need to rebase for ENT-3716.

**Pull request merged**
