### PR TITLE
SWATCH-2535: Reset account by org ID to use the billable usage client

### PR DESCRIPTION
**Pull request by Sgitario**
Jira issue: [SWATCH-2535](https://issues.redhat.com/browse/SWATCH-2535)

## Description
- create a new endpoint to reset the remittances by org ID in the billable usage service
- create the billable usage client module to be used by the tally service
- the reset account by org ID should use the billable usage client to reset the remittances

## Testing
Only regression testing.

1.- podman-compose up
2.- start the tally service: `CONTRACT_USE_STUB=true DEV_MODE=true ./gradlew :bootRun`
3.- start the billable usage service: `SERVER_PORT=8002 QUARKUS_MANAGEMENT_PORT=9002 ./gradlew :swatch-billable-usage:quarkusDev`
4.- insert some billable usage for org123:

```
INSERT INTO billable_usage_remittance(uuid, org_id, product_id, metric_id, accumulation_period, sla, usage, billing_provider, billing_account_id, remittance_pending_date, retry_after, remitted_pending_value)
VALUES ('e5406d59-5cf3-4e83-abf8-84c149f8b6ba', 'org123', 'rosa', 'CORES', '2024-02', 'Premium', 'Production', 'azure', '123456', '2024-02-11T04:00:09.620406Z', '2023-12-11T04:00:09.620406Z', '4.0')
```

5.- call the reset account from the tally service:

```
curl --fail -H "Origin: https://swatch-tally-service.redhat.com" -H "x-rh-swatch-psk: placeholder" -X DELETE "http://localhost:8000/api/rhsm-subscriptions/v1/internal/rpc/tally/org123"
```

6.- verification:
you should see the DELETE call in the billable usage service (this call is coming from the tally service):
```
2024-05-09 15:56:06,997 INFO  [io.qua.htt.access-log] (executor-thread-2) 127.0.0.1 - - [09/May/2024:15:56:06 +0200] "DELETE /api/swatch-billable-usage/internal/rpc/remittance/org123 HTTP/1.1" 200 20 "-" "OpenAPI-Generator/1.0.0/java
```

and there should not be any billable usages in the database: `select count(*) from billable_usage_remittance where org_id='org123'` should return 0.

### CODE REVIEW

**Comment by Sgitario** [comment]
@mstead assiging this one to you since you're already kind of familiar with these changes (which were part of https://github.com/RedHatInsights/rhsm-subscriptions/pull/3306).

**Review by mstead — APPROVED** [review]
Looks good and functions as expected.

**Pull request merged**
