### PR TITLE
SWATCH-1043 New api spec for guests by instance id

### PR DESCRIPTION
**Pull request by kartikshahc**
Jira issue: [SWATCH-1043](https://issues.redhat.com/browse/SWATCH-1043)

## Description

This card just covers spec changes for the new api for guests by instance id. There no test steps other than making sure the spec looks correct.

### CODE REVIEW

**Review by lindseyburnett — APPROVED** [review]

**Comment by Aurobinda55** [comment]
@kartikshahc I am getting the below error after updating our automation with the new api spec changes. Could you please check and confirm if I am missing anything or if this error is due to the recent changes? 

```
ApiException: (406)
Reason: 
HTTP response headers: HTTPHeaderDict({'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/vnd.api+json', 'Content-Length': '109', 'Date': 'Fri, 16 Jun 2023 14:54:39 GMT'})
HTTP response body: {"errors":[{"status":"406","code":"SUBSCRIPTIONS1001","title":"RESTEASY003635: No match for accept header"}]}
```

**Comment by kartikshahc** [comment]
@Aurobinda55 this is just spec changes without any implementation within it. Not sure why would are you getting the issue

**Review by Aurobinda55 — APPROVED** [review]
looks good.

**Pull request merged**
