### PR TITLE
SWATCH-2175: Meter ROSA Classic

### PR DESCRIPTION
**Pull request by awood**
Jira issue: SWATCH-2175

## Description
Adjust PromQL queries to meter ROSA Classic.  ROSA Classic is only metered on
cores and not instance-hours which creates an novel condition where different
metrics for the same product can point to different PromQL templates.

Also correct `swatchdog` so that it can handle heterogeneous template usage
within the same product.

### Setup
1. Check out the `swatch-support-scripts` repo from
   GitLab (contact me if you need a link), `cd` to the checkout.
1. Make sure you have a `~/.token-refresher-prod` file with a token in it.  If
   you do not, run
    ```bash
    ./fetch-vault-credentials
    ```
    Or download the token in the `token-refresher` namespace for `rhsm-prod` in
    Vault.
1. Start a telemeter proxy.
    ```bash
    ./telemeter-prod
    ```
1. Open the link that the script outputs.

### Steps
1. Generate the PromQL queries for Rosa.
    ```bash
    poetry run swatchdog prometheus promql --product rosa
    ```
    Replicated here for your convenience
    ```
    Accounts PromQL for metrics Instance-hours:
    group(min_over_time(ocm_subscription{product='moa-hostedcontrolplane', external_organization != '', billing_model='marketplace'}[1h])) by (external_organization)
    
    Accounts PromQL for metrics Cores:
    group(min_over_time(ocm_subscription{product=~'(moa-hostedcontrolplane|moa)', external_organization != ''}[1h])) by (external_organization)
    
    Instance-hours PromQL:
    max(cluster:usage:workload:capacity_physical_instance_hours) by (_id) * on(_id) group_right min_over_time(ocm_subscription{product="moa-hostedcontrolplane", 
    external_organization=~".*", billing_model="marketplace", metered_by_rh!='false'}[1h])
    
    Cores PromQL:
    max(cluster:usage:workload:capacity_virtual_cpu_hours) by (_id) * on(_id) group_right min_over_time(ocm_subscription{product=~"(moa-hostedcontrolplane|moa)", 
    external_organization=~".*", support=~"Premium|Standard|Self-Support|None", metered_by_rh!='false'}[1h])
    ```

1. Enter the queries into the Thanos Query box.

### Verification
1. The queries are syntactically correct and return results.

### CODE REVIEW

**Comment by awood** [comment]
Note to QE: I'm not totally sure if the QE label is appropriate here, but I'm going to apply it just in case.  I believe this should be mostly just a regression test, but I'd be interested to here thoughts about further testing for generating actual ROSA Classic data to scrape.

**Comment by Aurobinda55** [comment]
Deployed one EE and expose a  Prometheus app manually, check the below steps

**Instance Creation**  

- Add a `rosa-hcp` cluster 
`push_metrics_to_prometheus(org_id="3340851",product_id="rosa",account_number="0369233",hours=5,billing_account_id="test129",display_name="rosa-hcp-cluster")` 

- Again added a `rosa-classic` cluster
`push_metrics_to_prometheus(org_id="3340851",product_id="rosa",account_number="0369233",hours=5,billing_account_id="test129",display_name="rosa-classic-cluster")` 

- DId a hourly tally sync with perform-metering=True
- `app.rhsm_subscriptions.sync_tally_hourly(product_id="rosa",perform_metering=True)`
- Checked the Prometheus UI with the Promql query mentioned above 
**Instance-hours PromQL:**
Screenshot from 2024-09-05 18-30-28
**Cores PromQL:**
Screenshot from 2024-09-05 18-32-41

- Check the instance report and got the below results and it's rejects the control plane for rosa classic 
```
[{'id': '23ff4dc7-34d7-4b58-8761-1cd344463a83',
  'instance_id': 'cluster_1041406622',
  'display_name': 'rosa-hcp-cluster',
  'billing_provider': 'aws',
  'billing_account_id': 'test129',
  'measurements': [115.0, 78.0],
  'last_seen': datetime.datetime(2024, 9, 5, 11, 0, tzinfo=tzlocal()),
  'last_applied_event_record_date': datetime.datetime(2024, 9, 5, 12, 26, 59, 850928, tzinfo=tzlocal()),
  'number_of_guests': 0,
  'category': 'physical',
  '_labeled_measurements': {'Cores': 115.0, 'Instance-hours': 78.0}},
 {'id': '63fffc92-31dd-4d1b-b08d-edf6d8ff3cb3',
  'instance_id': 'cluster_8433852912',
  'display_name': 'rosa-classic-cluster',
  'billing_provider': 'aws',
  'billing_account_id': 'test129',
  'measurements': [170.0, 0.0],
  'last_seen': datetime.datetime(2024, 9, 5, 11, 0, tzinfo=tzlocal()),
  'last_applied_event_record_date': datetime.datetime(2024, 9, 5, 12, 34, 15, 845456, tzinfo=tzlocal()),
  'number_of_guests': 0,
  'category': 'physical',
  '_labeled_measurements': {'Cores': 170.0, 'Instance-hours': 0.0}}]
```
**Contract data**

```
[{'uuid': '05792464-9b0e-4149-a986-c4fb82fef84f',
  'subscription_number': '2730681',
  'sku': 'MW02393',
  'start_date': '2024-09-04T12:22:36Z',
  'end_date': '2024-10-05T12:22:36Z',
  'org_id': '3340851',
  'billing_provider': 'aws',
  'billing_provider_id': '232e2e9b-d617-4bb5-a071-2e6834d0794e;aws_customer_id_123;1234567',
  'billing_account_id': 'test129',
  'product_tags': ['rosa'],
  'vendor_product_code': '232e2e9b-d617-4bb5-a071-2e6834d0794e',
  'metrics': [{'metric_id': 'four_vcpu_hour', 'value': 5},
   {'metric_id': 'control_plane', 'value': 5}]}]
 
```
Verified the remittance and it sends vCPU hours usage   for both rosa classic and rosa hcp and controlplane usage  for rosa-hcp only  

**Remittance**

In [7]: app.rhsm_subscriptions.get_account_remittance(product_id="rosa",metricId="Cores")
2024-09-05 12:35:44.903 [    INFO] [root] Response: [
    {
        "accumulationPeriod": "2024-09",
        "billingAccountId": "test129",
        "billingProvider": "aws",
        "metricId": "Cores",
        "orgId": "3340851",
        "productId": "rosa",
        "remittanceDate": "2024-09-05T12:34:38.148871Z",
        "remittanceErrorCode": "null",
        "remittanceStatus": "pending",
        "remittedValue": 172.0
    },
    {
        "accumulationPeriod": "2024-09",
        "billingAccountId": "test129",
        "billingProvider": "aws",
        "metricId": "Cores",
        "orgId": "3340851",
        "productId": "rosa",
        "remittanceDate": "2024-09-05T12:27:21.672136Z",
        "remittanceErrorCode": "null",
        "remittanceStatus": "succeeded",
        "remittedValue": 96.0
    }
]

*************************************************
In [8]: app.rhsm_subscriptions.get_account_remittance(product_id="rosa",metricId="Instance-hours")

Out[8]: 
[{'orgId': '3340851',
  'productId': 'rosa',
  'metricId': 'Instance-hours',
  'billingProvider': 'aws',
  'billingAccountId': 'test129',
  'remittedValue': 73.0,
  'accumulationPeriod': '2024-09',
  'remittanceDate': '2024-09-05T12:27:21.689993Z',
  'remittanceStatus': 'succeeded',
  'remittanceErrorCode': 'null'}]

Note:
Rosa classic cluster created with product="moa" and rosa-hcp with product="moa-hostedcontrolplane" through Prometheus script.

@awood I hope this addressed your question regarding cluster creation. Please let me know if I missed anything. Thank you!

**Comment by Aurobinda55** [comment]
@awood I hope this addressed your question regarding cluster creation. Please let me know if I missed anything. Thank you!

**Pull request merged**
