### PR TITLE
SWATCH-2356: Send request to enabled-orgs-for-tasks for prune and sync

### PR DESCRIPTION
**Pull request by Sgitario**
Jira issue: [SWATCH-2356](https://issues.redhat.com/browse/SWATCH-2356)

## Description
- The method "pruneUnlistedSubscriptions" from SWATCH-2277 should produce a single message to "platform.rhsm-subscriptions.enabled-orgs-for-tasks" with a message containing the topic name "platform.rhsm-subscriptions.subscription-prune-task".
- The method "syncAllSubscriptions" from SWATCH-2277 should produce a single message to "platform.rhsm-subscriptions.enabled-orgs-for-tasks" with a message containing the topic name "platform.rhsm-subscriptions.subscription-sync-task".
- Create the consumer of "platform.rhsm-subscriptions.subscription-prune-task" that receives a message that includes the orgId. Leave the implementation empty.
- Create the consumer of "platform.rhsm-subscriptions.subscription-sync-task" that receives a message that includes the orgId. Leave the implementation empty.

## Testing
1.- podman-compose up
2.- start tally:

```
DEV_MODE=true SPRING_PROFILES_ACTIVE=worker ./gradlew :bootRun
```

3.- populate some enabled orgs:

```
INSERT INTO org_config(org_id, opt_in_type, created, updated) VALUES('org1', 'API', now(), now());
INSERT INTO org_config(org_id, opt_in_type, created, updated) VALUES('org2', 'API', now(), now());
INSERT INTO org_config(org_id, opt_in_type, created, updated) VALUES('org3', 'API', now(), now());
```

4.- start contracts service:

```
SERVER_PORT=8001 QUARKUS_MANAGEMENT_PORT=9001 ./gradlew :swatch-contracts:quarkusDev
```

5.- start subscriptions prune task:

```
curl -X DELETE http://localhost:8001/api/swatch-contracts/internal/subscriptions/prune
```

Verification: you should see the following traces in the contracts service:
```
2024-04-22 12:58:33,591 INFO  [com.red.swa.con.ser.SubscriptionPruneTaskConsumer] (vert.x-eventloop-thread-2) {sampled=true, spanId=704b47c251d90584, traceId=9f025d6524c19345c352f63a90038edc} Received task for subscription prune with org ID: org2
2024-04-22 12:58:33,617 INFO  [com.red.swa.con.ser.SubscriptionPruneTaskConsumer] (vert.x-eventloop-thread-2) {sampled=true, spanId=c67d5f89d66c21b3, traceId=525dbd269276d86683741c3babda5096} Received task for subscription prune with org ID: org1
2024-04-22 12:58:33,621 INFO  [com.red.swa.con.ser.SubscriptionPruneTaskConsumer] (vert.x-eventloop-thread-2) {sampled=true, spanId=59ff7779ae66dd9f, traceId=991b00e758fe03e8b637997fa35567a7} Received task for subscription prune with org ID: org3
```

6.- start subscriptions sync task:

```
curl -X PUT http://localhost:8001/api/swatch-contracts/internal/rpc/subscriptions/sync?forceSync=true
```

Verification: you should see the following traces in the contracts service:

```
2024-04-22 13:03:41,989 INFO  [com.red.swa.con.ser.SubscriptionSyncTaskConsumer] (vert.x-eventloop-thread-0) {sampled=true, spanId=88f9384fe792ddec, traceId=28e4d858dbedabf09e57c4ddeb0880ff} Received task for subscription sync with org ID: org2
2024-04-22 13:03:42,004 INFO  [com.red.swa.con.ser.SubscriptionSyncTaskConsumer] (vert.x-eventloop-thread-0) {sampled=true, spanId=df381ff8505e1515, traceId=0e93647077b0fdde011928108c962dca} Received task for subscription sync with org ID: org1
2024-04-22 13:03:42,008 INFO  [com.red.swa.con.ser.SubscriptionSyncTaskConsumer] (vert.x-eventloop-thread-0) {sampled=true, spanId=f14bacd241323115, traceId=bf296a85e11219eb9e778686053fb6f3} Received task for subscription sync with org ID: org3
```

### CODE REVIEW

**Comment by kartikshahc** [comment]
Steps are performing as described. Looking into few things in code.

**Comment by Aurobinda55** [comment]
Verification steps:

- Added one org  in org_config
- Called subscriptions/prune api and received the below logs in contract service 
`2024-04-25 07:32:25,704 INFO [com.red.swa.con.ser.SubscriptionPruneTaskConsumer] (vert.x-eventloop-thread-1) {sampled=true, spanId=6279f5906f82e0ba, traceId=1e0b3573570fb704d0fd028a6c2c9e18} Received task for subscription prune with org ID: 14541308`
-  Again called the subscription sync service and got  the below logs  
`2024-04-25 07:34:14,163 INFO [com.red.swa.con.ser.SubscriptionSyncTaskConsumer] (vert.x-eventloop-thread-0) {sampled=true, spanId=9c51d2ff03b27346, traceId=53ed63080ba5ffd8a629c5eab0a27058} Received task for subscription sync with org ID: 14541308`

Looks good to me

**Comment by Aurobinda55** [comment]
https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/669 raised to fix  the failed contract api tests

**Review by Aurobinda55 — APPROVED** [review]

**Review by kartikshahc — APPROVED** [review]

**Pull request merged**
