### PR TITLE
SWATCH-1233: Drop UOM from the swatch

### PR DESCRIPTION
**Pull request by Sgitario**
Jira issue: SWATCH-1233

## Description
UOM is no longer referenced in swatch openapi definitions Automation tests are no longer referencing UOM
UOM is no longer referenced in SWatch code
UOM is no longer stored as part of events. 
Double check that no queries are using UOM
check bin/ scripts to make sure UOM is no longer referenced

## Testing
Only regression testing.

### CODE REVIEW

**Review by wottop — CHANGES_REQUESTED** [review]
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyMeasurementKey.java:77:        + ", uom="
swatch-tally/deploy/clowdapp.yaml:708:        metric_id as uom,

**Comment by Sgitario** [comment]
> swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyMeasurementKey.java:77: + ", uom=" 

Updated

> swatch-tally/deploy/clowdapp.yaml:708: metric_id as uom,

This is used by the floorplan queries, so it should stay as it is as noted in the JIRA description.

PR updated.

**Review by liwalker-rh — APPROVED** [review]
Changes look good in regression testing. I also added an IQE MR to remove variables named UOM in any test and replaced with metric_id when necessary. This will help to avoid anyone being confused about UOM still being seen in tests in the future. https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/874

**Review by wottop — APPROVED** [review]

**Pull request merged**
