### PR TITLE
SWATCH-1761: Add Rhelemeter task lag panel to the grafana dashboard

### PR DESCRIPTION
**Pull request by awood**
Jira issue: [SWATCH-1761](https://issues.redhat.com/browse/SWATCH-1767)

## Description

This PR adds a "Rhelemeter Task Lag" panel to grafana.  The diff is a little noisier than one might expect because I had to rearrange the order of some of the existing panels.

## Testing

Unfortunately, I am not aware of a way to test this.  Importing the entire JSON file to a new grafana dashboard might do it, but I haven't seen a way to do that.

### CODE REVIEW

**Comment by lindseyburnett** [comment]
/retest

Updated instructions in README for importing dashboards in grafana.  Confirmed new graph widget appears

image

**Review by lindseyburnett — APPROVED** [review]

**Comment by awood** [comment]
Thanks for updating the docs, @lindseyburnett  I didn't actually realize they were out of date!

**Pull request merged**
