### PR TITLE
 SWATCH-1111: Add vendorcode to contract table

### PR DESCRIPTION
**Pull request by ksynvrit**
This is to address https://issues.redhat.com/browse/SWATCH-1111. The reminder will be address in another PR, as this is need to have for integration test & https://issues.redhat.com/browse/SWATCH-1118

Testing Steps:
DB Setup:
```
INSERT INTO public.contracts (uuid, subscription_number, last_updated, start_date, end_date, org_id, sku, billing_provider, billing_account_id, product_id, vendor_product_code) VALUES ('469c5d31-8b07-4826-bcf5-cb23419a7b5f', '123456789', '2023-04-07 15:33:58.249887 +00:00', '2023-04-07 15:32:46.568558 +00:00', '2023-04-07 15:33:58.249887 +00:00', '16764785', 'RH00001', 'aws', '568056954830', 'rosa', '6n58d3s3qpvk22dgew2gal7w3');
INSERT INTO public.contracts (uuid, subscription_number, last_updated, start_date, end_date, org_id, sku, billing_provider, billing_account_id, product_id, vendor_product_code) VALUES ('0cc680eb-fd7c-4e7b-b776-c0ec5441632e', '123456789', '2023-04-07 16:14:17.967853 +00:00', '2023-04-07 16:14:17.967853 +00:00', null, '16764785', 'RH00001', 'aws', '568056954830', 'rosa', '6n58d3s3qpvk22dgew2gal7w3');
INSERT INTO public.contracts (uuid, subscription_number, last_updated, start_date, end_date, org_id, sku, billing_provider, billing_account_id, product_id, vendor_product_code) VALUES ('017b22e1-222f-48b4-ac56-faacd208b073', '123456789', '2023-04-07 16:14:17.967853 +00:00', '2023-04-07 16:14:09.091619 +00:00', '2023-04-07 16:14:17.967853 +00:00', '16764785', 'RH00001', 'aws', '568056954830', 'rosa', '6n58d3s3qpvk22dgew2gal7w3');
INSERT INTO public.contracts (uuid, subscription_number, last_updated, start_date, end_date, org_id, sku, billing_provider, billing_account_id, product_id, vendor_product_code) VALUES ('a4d32d8c-a366-4898-9d6c-2d21301023b7', '123456789', '2023-04-07 16:31:00.665511 +00:00', '2023-04-07 16:31:00.665511 +00:00', null, '16764785', 'RH00001', 'aws', '568056954830', 'rosa', '6n58d3s3qpvk22dgew2gal7w3');
INSERT INTO public.contracts (uuid, subscription_number, last_updated, start_date, end_date, org_id, sku, billing_provider, billing_account_id, product_id, vendor_product_code) VALUES ('ff71214d-5c3b-4edc-8e66-260b8ad480a3', '123456789', '2023-04-07 16:31:54.842871 +00:00', '2023-04-07 16:31:54.842871 +00:00', null, '16764785', 'RH00001', 'aws', '568056954830', 'rosa', '6n58d3s3qpvk22dgewTest');
INSERT INTO public.contracts (uuid, subscription_number, last_updated, start_date, end_date, org_id, sku, billing_provider, billing_account_id, product_id, vendor_product_code) VALUES ('eedccb0b-dce8-4948-9520-0b9753638e65', '123456789', '2023-04-07 16:40:41.203122 +00:00', '2023-04-07 16:40:41.203122 +00:00', null, '16764785', 'RH00001', 'aws', '568056954830', 'rosa', '6n58d3s3qpvk22dgewTest');
INSERT INTO public.contracts (uuid, subscription_number, last_updated, start_date, end_date, org_id, sku, billing_provider, billing_account_id, product_id, vendor_product_code) VALUES ('06120a13-46d3-41b5-b89a-796698ececff', '123456789', '2023-04-07 16:42:01.436517 +00:00', '2023-04-07 16:42:01.436517 +00:00', null, '16764785', 'RH00001', 'aws', '568056954830', 'rosa', '6n58d3s3qpvk22dgewTest');
INSERT INTO public.contracts (uuid, subscription_number, last_updated, start_date, end_date, org_id, sku, billing_provider, billing_account_id, product_id, vendor_product_code) VALUES ('463573f6-2aa7-4c36-a572-ba170b93aa0b', '123456789', '2023-04-07 16:42:36.309450 +00:00', '2023-04-07 16:42:36.309450 +00:00', null, '16764785', 'RH00001', 'aws', '568056954830', 'rosa', '6n58d3s3qpvk22dgewTest');
INSERT INTO public.contracts (uuid, subscription_number, last_updated, start_date, end_date, org_id, sku, billing_provider, billing_account_id, product_id, vendor_product_code) VALUES ('4ddd414a-fa8e-42f4-a728-1119f66b594c', '123456789', '2023-04-07 16:42:36.308545 +00:00', '2023-04-07 15:33:58.249887 +00:00', '2023-04-07 16:42:36.308545 +00:00', '16764785', 'RH00001', 'aws', '568056954830', 'rosa', '6n58d3s3qpvk22dgew2gal7w3');
```
Contracts-metrics:
```
INSERT INTO public.contract_metrics (contract_uuid, metric_id, metric_value) VALUES ('469c5d31-8b07-4826-bcf5-cb23419a7b5f', 'vCPU', 4);
INSERT INTO public.contract_metrics (contract_uuid, metric_id, metric_value) VALUES ('4ddd414a-fa8e-42f4-a728-1119f66b594c', 'vCPU', 8);
INSERT INTO public.contract_metrics (contract_uuid, metric_id, metric_value) VALUES ('017b22e1-222f-48b4-ac56-faacd208b073', 'vCPU', 4);
INSERT INTO public.contract_metrics (contract_uuid, metric_id, metric_value) VALUES ('0cc680eb-fd7c-4e7b-b776-c0ec5441632e', 'vCPU', 4.5);
INSERT INTO public.contract_metrics (contract_uuid, metric_id, metric_value) VALUES ('a4d32d8c-a366-4898-9d6c-2d21301023b7', 'vCPU4', 28);
INSERT INTO public.contract_metrics (contract_uuid, metric_id, metric_value) VALUES ('a4d32d8c-a366-4898-9d6c-2d21301023b7', 'vCPU', 18);
INSERT INTO public.contract_metrics (contract_uuid, metric_id, metric_value) VALUES ('ff71214d-5c3b-4edc-8e66-260b8ad480a3', 'vCPU4', 28);
INSERT INTO public.contract_metrics (contract_uuid, metric_id, metric_value) VALUES ('ff71214d-5c3b-4edc-8e66-260b8ad480a3', 'vCPU', 18);
INSERT INTO public.contract_metrics (contract_uuid, metric_id, metric_value) VALUES ('eedccb0b-dce8-4948-9520-0b9753638e65', 'vCPU4', 28);
INSERT INTO public.contract_metrics (contract_uuid, metric_id, metric_value) VALUES ('eedccb0b-dce8-4948-9520-0b9753638e65', 'vCPU', 18);

```

To test UMB message follow the testing steps in this PR https://github.com/RedHatInsights/rhsm-subscriptions/pull/2020

Regression Test PUT request change any of the fields below:
```
{
  "uuid": "4ddd414a-fa8e-42f4-a728-1119f66b594c",
  "subscription_number": "123456789",
  "start_date": "2018-02-10T09:30Z",
  "end_date": "2018-02-10T09:30Z",
  "org_id": "16764785",
  "billing_provider": "aws",
  "billing_account_id": "568056954830",
  "product_id": "rosa",
  "sku": "RH00001",
  "vendor_product_code":"Test1",
  "metrics": [
    {
      "metric_id": "vCPU",
      "value": 8
    },
    {
      "metric_id": "vCPU4",
      "value": 28
    }
  ]
}
```

### CODE REVIEW

**Review by kartikshahc — APPROVED** [review]

**Comment by ksynvrit** [comment]
Do not merge until it tested by QE

**Review by kartikshahc — APPROVED** [review]

**Review by kartikshahc — APPROVED** [review]

**Comment by ntkathole** [comment]
@ksynvrit Contract creation is working fine, but when there is usage and hourly tally is performed, it tries to look up for contract with `vendorProductCode=<null> `and could not find contract even if it exists. 
```
2023-04-10 08:48:59,698 [thread=swatch-producer-billing-0-C-1] [ERROR] [org.candlepin.subscriptions.tally.billing.BillableUsageController] - SUBSCRIPTIONS3004: Expected contract missing - Unable to retrieve contract for usage older than 30 minutes old. Usage: org.candlepin.subscriptions.json.BillableUsage@1ed58fd1[accountNumber=<null>,orgId=3340851,id=fddd83fa-b519-4565-9910-8a7413fafcee,billingProvider=aws,billingAccountId=0f7c8079-84bb-45bb-bd11-8d875da2bc2b,snapshotDate=2023-04-10T07:00Z,productId=rosa,sla=Premium,usage=Production,uom=Instance-hours,value=4.0,billingFactor=<null>,vendorProductCode=<null>] 
```

**Comment by ksynvrit** [comment]
@ntkathole The parameter position was switch which was causing this not to return contracts, please retest and notify me with the result

**Comment by ntkathole** [comment]
> @ntkathole The parameter position was switch which was causing this not to return contracts, please retest and notify me with the result

Thanks @ksynvrit for quick fix; working fine now!

**Pull request merged**
