### PR TITLE
SWATCH-1047 Properly filter by cores/sockets in instance API

### PR DESCRIPTION
**Pull request by mstead**
Jira issue: [SWATCH-1047](https://issues.redhat.com/browse/SWATCH-1047)

## Description
Min cores/sockets was always being passed to the query as 0,
resulting in the same instance results no matter if the UOM was
sockets or cores.

This patch applies logic from the old API to toggle the min value
based on whether the uom is sockets or cores.

## Testing
Drop the database
```
dropdb -U rhsm-subscriptions rhsm-subscriptions && createdb -U rhsm-subscriptions rhsm-subscriptions
```

Load the database from the attached test data file: [bug_data_dump_full.txt](https://github.com/RedHatInsights/rhsm-subscriptions/files/11971683/bug_data_dump_full.txt)
```
psql -U rhsm-subscriptions rhsm-subscriptions < bug_data_dump_full.txt
```

Deploy the app from the main branch.
```
DEV_MODE=true ./gradlew :bootRun
```

Opt in the test org/account
```
http PUT :8000/api/rhsm-subscriptions/v1/opt-in x-rh-identity:$(echo '{"identity":{"account_number":"account123","type":"User","internal":{"org_id":"org123"}}}'| base64 -w0)
```

### Reproduce on main branch
Test with cores
```
http GET ':8000/api/rhsm-subscriptions/v1/instances/products/OpenShift%20Container%20Platform?dir=desc&ending=2023-06-30T23:59:59.999Z&limit=100&offset=0&sort=last_seen&beginning=2023-06-01T00:00:00Z&uom=cores' x-rh-identity:$(echo '{"identity":{"account_number":"account123","type":"User","internal":{"org_id":"org123"}}}'| base64 -w0)
```

Observe - count 82
```
{
...
...
    "meta": {
        "count": 82,
        "measurements": [
            "Cores",
            "Sockets"
        ],
        "product": "OpenShift Container Platform"
    }
}
```

Test with sockets
```
http GET ':8000/api/rhsm-subscriptions/v1/instances/products/OpenShift%20Container%20Platform?dir=desc&ending=2023-06-30T23:59:59.999Z&limit=100&offset=0&sort=last_seen&beginning=2023-06-01T00:00:00Z&uom=sockets' x-rh-identity:$(echo '{"identity":{"account_number":"account123","type":"User","internal":{"org_id":"org123"}}}'| base64 -w0)
```

Observe - count 82
```
{
...
...
    "meta": {
        "count": 82,
        "measurements": [
            "Cores",
            "Sockets"
        ],
        "product": "OpenShift Container Platform"
    }
}
```

### Test fix on PR branch

Check out this branch and deploy again.

Test with cores
```
http GET ':8000/api/rhsm-subscriptions/v1/instances/products/OpenShift%20Container%20Platform?dir=desc&ending=2023-06-30T23:59:59.999Z&limit=100&offset=0&sort=last_seen&beginning=2023-06-01T00:00:00Z&uom=cores' x-rh-identity:$(echo '{"identity":{"account_number":"account123","type":"User","internal":{"org_id":"org123"}}}'| base64 -w0)
```

Observe - count 48
```
{
...
...
    "meta": {
        "count": 48,
        "measurements": [
            "Cores",
            "Sockets"
        ],
        "product": "OpenShift Container Platform"
    }
}
```

Test with sockets
```
http GET ':8000/api/rhsm-subscriptions/v1/instances/products/OpenShift%20Container%20Platform?dir=desc&ending=2023-06-30T23:59:59.999Z&limit=100&offset=0&sort=last_seen&beginning=2023-06-01T00:00:00Z&uom=sockets' x-rh-identity:$(echo '{"identity":{"account_number":"account123","type":"User","internal":{"org_id":"org123"}}}'| base64 -w0)
```

Observe - count 34
```
{
...
...
    "meta": {
        "count": 34,
        "measurements": [
            "Cores",
            "Sockets"
        ],
        "product": "OpenShift Container Platform"
    }
}
```

### CODE REVIEW

**Comment by mstead** [comment]
@Aurobinda55 This PR is a revert of changes that were initially made in #2299 

The initial tests/results that you had done apply here.

**Review by kahowell — APPROVED** [review]

**Comment by Aurobinda55** [comment]
- Created  4 ocp instances 
- 1st and 2nd   instances with ocm_units = Sockets, sockets value 5 and 0  for first and second
- 3rd and 4th instances with ocm_units =Cores, Cores value 9 and 0  for third  and four 
- Called the instances report with filter parameter uom="Sockets"
- Got the only  instance  that has sockets value  > 0 and  expected socket value in response 
- Called the instances report with filter parameter uom ="Cores" 
- Got the only instance that has Cores value > 0 and expected Cores value in response
- Match the  instances value with  the tally api value with the filter parameter applied and got the expected result

**Review by Aurobinda55 — APPROVED** [review]
LGTM

**Pull request merged**
