### PR TITLE
SWATCH-1764: update rosa product name

### PR DESCRIPTION
**Pull request by kflahert**
Jira issue: [SWATCH-1764](https://issues.redhat.com/browse/SWATCH-1764)

## Description

This issue was caused by OCP and ROSA offerings sharing the same product_name. In order to fix, rosa has been updated with a unique product_name.

### Setup

1. Insert following data, including an offering with the new product_name:
```
INSERT INTO public.offering VALUES ('MW02393', 'OpenShift Online', 'OpenShift Enterprise', NULL, NULL, NULL, NULL, NULL, 'Premium', '', 'Red Hat OpenShift Service on AWS Hosted Control Planes (Hourly)', false, NULL, 'rosa');
INSERT INTO public.offering VALUES ('MW01484', 'OpenShift Dedicated', 'OpenShift Enterprise', NULL, NULL, NULL, NULL, NULL, 'Premium', '', 'Red Hat OpenShift Dedicated on Customer Cloud Subscription (Hourly)', false, NULL, 'OpenShift-dedicated-metrics');

INSERT INTO public.subscription VALUES ('MW02393', '13259775', '9063404', 50, '2021-04-14 04:00:00+00', '2024-04-13 03:59:59+00', 'test-subscription-1', '9063559', 'red hat', '')
INSERT INTO public.subscription VALUES ('MW01484', '13259775', '123', 50, '2021-04-14 04:00:00+00', '2024-04-13 03:59:59+00', 'test-subscription-1', '9063559', 'red hat', '')
```
1. Start app with; `DEV_MODE=true SPRING_PROFILES_ACTIVE=capacity-ingress,api ./gradlew :bootRun`
2. Opt in org:
```
curl -X 'PUT' \
  'http://localhost:8000/api/rhsm-subscriptions/v1/opt-in' \
  -H 'accept: application/vnd.api+json' \
  -H 'x-rh-identity: ewogICAgImlkZW50aXR5IjogewogICAgICAgICJ0eXBlIjogIlVzZXIiLAogICAgICAgICJ1c2VyIiA6IHsKICAgICAgICAgICAgImlzX29yZ19hZG1pbiI6IHRydWUKICAgICAgICB9LAogICAgICAgICJpbnRlcm5hbCIgOiB7CiAgICAgICAgICAgICJvcmdfaWQiOiAiMTMyNTk3NzUiCiAgICAgICAgfQogICAgfQp9'
```

### Verification

1. Curl against subscription api for ROSA and verify that 1 subscription shown for sku MW02393:
```
curl -X 'GET' \
  'http://localhost:8000/api/rhsm-subscriptions/v1/subscriptions/products/rosa' \
  -H 'accept: application/vnd.api+json' \
  -H 'x-rh-identity: ewogICAgImlkZW50aXR5IjogewogICAgICAgICJ0eXBlIjogIlVzZXIiLAogICAgICAgICJ1c2VyIiA6IHsKICAgICAgICAgICAgImlzX29yZ19hZG1pbiI6IHRydWUKICAgICAgICB9LAogICAgICAgICJpbnRlcm5hbCIgOiB7CiAgICAgICAgICAgICJvcmdfaWQiOiAiMTMyNTk3NzUiCiAgICAgICAgfQogICAgfQp9'
```

### CODE REVIEW

**Review by ssidhaye — COMMENTED** [review]
After adding subs and opting in I am able to see 1 subscription for sku MW02393

`{
  "data": [
    {
      "sku": "MW02393",
      "product_name": "Red Hat OpenShift Service on AWS Hosted Control Planes (Hourly)",
      "service_level": "Premium",
      "usage": "",
      "subscriptions": [
        {
          "id": "9063404",
          "number": "9063559"
        }
      ],
      "billing_provider": "red hat",
      "next_event_date": "2024-04-13T03:59:59Z",
      "next_event_type": "Subscription End",
      "quantity": 50,
      "capacity": 0,
      "hypervisor_capacity": 0,
      "total_capacity": 0,
      "has_infinite_quantity": false
    }
  ],
  "meta": {
    "count": 1,
    "product": "rosa",
    "subscription_type": "On-demand"
  }
}`

I tried doing the same thing via iqe shell (I wanted to avoid using db inserts, but I ran into problems with add_sku) @ntkathole yesterday I was facing the same problem in another EE, any idea ?

**Review by Sgitario — CHANGES_REQUESTED** [review]
Checking the "service-now" ticket, it's said: 

```
The product name in ROSA SKUs currently shows as "OpenShift Dedicated" and this creates confusion for subscription watch when it comes to metering usage for ROSA clusters. The product name should instead be "Red Hat OpenShift Service on AWS"
```

So, I would have expected the product name to be "Red Hat OpenShift Service on AWS". However, checking the offering "MW01369" or "MW02393", they indeed used "OpenShift Online", then I guess it's all good. 

The problem I see is about casing. In the offering site, the above products use "OpenShift Online" instead of "openshift online" and as far as I see in the code, we do not ignore casing differences.

**Comment by kflahert** [comment]
> Checking the "service-now" ticket, it's said:
> 
> ```
> The product name in ROSA SKUs currently shows as "OpenShift Dedicated" and this creates confusion for subscription watch when it comes to metering usage for ROSA clusters. The product name should instead be "Red Hat OpenShift Service on AWS"
> ```
> 
> So, I would have expected the product name to be "Red Hat OpenShift Service on AWS". However, checking the offering "MW01369" or "MW02393", they indeed used "OpenShift Online", then I guess it's all good.
> 
> The problem I see is about casing. In the offering site, the above products use "OpenShift Online" instead of "openshift online" and as far as I see in the code, we do not ignore casing differences.

Thanks @Sgitario. I fixed the casing. This bug fix changed a bit as I was working it because of some limitations we have with sku's. I added more context in the Jira ticket as to why it's "Openshift Online" and not "Red Hat OpenShift Service on AWS". But basically we aren't able to create new product_names at the moment so we had to go with a pre-existing value that isn't in use.

**Review by Sgitario — APPROVED** [review]
thanks!

**Comment by kflahert** [comment]
> After adding subs and opting in I am able to see 1 subscription for sku MW02393
> 
> `{ "data": [ { "sku": "MW02393", "product_name": "Red Hat OpenShift Service on AWS Hosted Control Planes (Hourly)", "service_level": "Premium", "usage": "", "subscriptions": [ { "id": "9063404", "number": "9063559" } ], "billing_provider": "red hat", "next_event_date": "2024-04-13T03:59:59Z", "next_event_type": "Subscription End", "quantity": 50, "capacity": 0, "hypervisor_capacity": 0, "total_capacity": 0, "has_infinite_quantity": false } ], "meta": { "count": 1, "product": "rosa", "subscription_type": "On-demand" } }`
> 
> I tried doing the same thing via iqe shell (I wanted to avoid using db inserts, but I ran into problems with add_sku) @ntkathole yesterday I was facing the same problem in another EE, any idea ?

@ssidhaye any update on this?

**Review by ssidhaye — APPROVED** [review]

**Pull request merged**
