### PR TITLE
SWATCH-1284: Prevent nullpointer exception

### PR DESCRIPTION
**Pull request by lindseyburnett**
Jira issue: [SWATCH-1284](https://issues.redhat.com/browse/SWATCH-1284)

## Description

Nullpointers were happening in the event `val` was null.  Simply using `Objects.equals` prevents the exception.

### CODE REVIEW

**Review by kartikshahc — APPROVED** [review]

**Review by ntkathole — APPROVED** [review]
Verified in EE

Fix Looks good and offerings are synced successfully! @lindseyburnett should we remove skus from deny-list, which were added in https://github.com/RedHatInsights/rhsm-subscriptions/pull/2168 ? 

```
2023-06-07 12:13:03,572 [thread=http-nio-9000-exec-5] [INFO ] [org.candlepin.subscriptions.product.OfferingJmxBean] - Sync for offering RH02631 triggered over JMX by anonymousUser
2023-06-07 12:13:04,653 [thread=http-nio-9000-exec-5] [INFO ] [org.candlepin.subscriptions.product.UpstreamProductData] - Encountered conflicting attribute values when pulling offeringSku="RH02631" from upstream:
offeringSku="RH02631" already has field=PRODUCT_FAMILY original="RHEL" so will ignore value="Red Hat Enterprise Linux".
offeringSku="RH02631" already has field=X_DESCRIPTION original="Red Hat Enterprise Linux Server for Year 1 of Multi-year Migration, Full Support (Physical or Virtual Nodes, Dedicated, Yearly)" so will ignore value="Red Hat Enterprise Linux Server for Service Providers, Full Support (Physical or Virtual Nodes, Dedicated, Yearly)".
offeringSku="RH02631" already has field=X_ROLE original="Red Hat Enterprise Linux Server" so will ignore value="null".
2023-06-07 12:13:04,661 [thread=http-nio-9000-exec-5] [INFO ] [org.candlepin.subscriptions.product.OfferingSyncController] - syncResult=FETCHED_AND_SYNCED (Successfully fetched and synced updated value from upstream) for offeringSku="RH02631" in offeringSyncTimeMillis=1088.
2023-06-07 12:13:04,663 [thread=capacity-reconciliation-worker-10-C-1] [INFO ] [org.candlepin.subscriptions.capacity.CapacityReconciliationWorker] - Capacity Reconciliation Worker is reconciling capacity for offering with values: ReconcileCapacityByOfferingTask(sku=RH02631, offset=0, limit=100)
```

**Comment by lindseyburnett** [comment]
> Verified in EE
> 
> Fix Looks good and offerings are synced successfully! @lindseyburnett should we remove skus from deny-list, which were added in #2168 ?
> 
> ```
> 2023-06-07 12:13:03,572 [thread=http-nio-9000-exec-5] [INFO ] [org.candlepin.subscriptions.product.OfferingJmxBean] - Sync for offering RH02631 triggered over JMX by anonymousUser
> 2023-06-07 12:13:04,653 [thread=http-nio-9000-exec-5] [INFO ] [org.candlepin.subscriptions.product.UpstreamProductData] - Encountered conflicting attribute values when pulling offeringSku="RH02631" from upstream:
> offeringSku="RH02631" already has field=PRODUCT_FAMILY original="RHEL" so will ignore value="Red Hat Enterprise Linux".
> offeringSku="RH02631" already has field=X_DESCRIPTION original="Red Hat Enterprise Linux Server for Year 1 of Multi-year Migration, Full Support (Physical or Virtual Nodes, Dedicated, Yearly)" so will ignore value="Red Hat Enterprise Linux Server for Service Providers, Full Support (Physical or Virtual Nodes, Dedicated, Yearly)".
> offeringSku="RH02631" already has field=X_ROLE original="Red Hat Enterprise Linux Server" so will ignore value="null".
> 2023-06-07 12:13:04,661 [thread=http-nio-9000-exec-5] [INFO ] [org.candlepin.subscriptions.product.OfferingSyncController] - syncResult=FETCHED_AND_SYNCED (Successfully fetched and synced updated value from upstream) for offeringSku="RH02631" in offeringSyncTimeMillis=1088.
> 2023-06-07 12:13:04,663 [thread=capacity-reconciliation-worker-10-C-1] [INFO ] [org.candlepin.subscriptions.capacity.CapacityReconciliationWorker] - Capacity Reconciliation Worker is reconciling capacity for offering with values: ReconcileCapacityByOfferingTask(sku=RH02631, offset=0, limit=100)
> ```

good idea, just added them back

**Pull request merged**
