### PR TITLE
SWATCH-2279: Port CapacityReconciliationController to swatch-contracts

### PR DESCRIPTION
**Pull request by Sgitario**
Jira issue: SWATCH-2279

## Description
- "/v1/internal/rpc/offerings/reconcile/{sku}" from subscription-sync to swatch-contracts
- Consumer of the topic "platform.rhsm-subscriptions.capacity-reconcile" is now swatch-contracts where producers are swatch-contracts and still the subscription-sync services (this will be fully ported in SWATCH-2280 and SWATCH-2281

## Testing

IQE Test MR: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/752

1.- podman-compose up
2.- create schema `./gradlew liquibaseUpdate`
3.- Create offering:

```
INSERT INTO OFFERING(sku,product_name,product_family,sla,description,cores, sockets, has_unlimited_usage) VALUES ('RH0180192','OpenShift Data Science','OPENSHIFT ENTERPRISE','Premium','Red Hat OpenShift Data Science',10,50,'false');
```

4.- Create more than 100 subscriptions for this offering:

```
INSERT INTO subscription(sku,org_id,subscription_id,quantity,start_date,subscription_number)
select 'RH0180192', 'org123', '16764' || gs, gs, now(), '12396' || gs FROM generate_series(1, 200) AS gs;
```

5.- Start the swatch contracts service: `SERVER_PORT=8001 QUARKUS_MANAGEMENT_PORT=9001 ./gradlew :swatch-contracts:quarkusDev` 

6.- Call '/api/swatch-contracts/internal/rpc/offerings/reconcile/{sku}' to sync all the subscriptions.

curl -X PUT http://localhost:8001/api/swatch-contracts/internal/rpc/offerings/reconcile/RH0180192

Expected output is:

```
{"detail":"Success"}
```

7.- Verify application logs (in swatch-contracts):

```
> :sw2024-06-17 10:22:25,923 INFO  [com.red.swa.con.res.ContractsTestingResource] (executor-thread-1) {sampled=true, spanId=a5e2ac933eb3c08e, traceId=5df683ad205e6dfeb1a9c6079a1a00b0} Capacity Reconciliation for sku RH0180192 triggered
> IDL2024-06-17 10:22:26,490 WARN  [com.red.swa.con.con.ProductDenylist] (executor-thread-1) {sampled=true, spanId=a5e2ac933eb3c08e, traceId=5df683ad205e6dfeb1a9c6079a1a00b0} No denylist present in configuration
<====2024-06-17 10:22:27,643 INFO  [io.sma.rea.mes.kafka] (vert.x-eventloop-thread-2) {} SRMSG18256: Initialize record store for topic-partition 'platform.rhsm-subscriptions.capacity-reconcile-0' at position -1.
<====2024-06-17 10:22:27,652 INFO  [com.red.swa.con.ser.CapacityReconciliationConsumer] (vert.x-worker-thread-1) {sampled=true, spanId=7cb7e6fa73377c31, traceId=f1a4a7e2087efc263cf6051da6c3af86} Capacity Reconciliation Worker is reconciling capacity for offering with values: ReconcileCapacityByOfferingTask(sku=RH0180192, offset=100, limit=100) 
> IDL2024-06-17 10:22:27,817 INFO  [com.red.swa.con.ser.CapacityReconciliationConsumer] (vert.x-worker-thread-1) {sampled=true, spanId=c383655cd6722332, traceId=d3ab42762355e6b5c07f08eb063c2821} Capacity Reconciliation Worker is reconciling capacity for offering with values: ReconcileCapacityByOfferingTask(sku=RH0180192, offset=200, limit=100) 
```

8.- Verify that the kafka topic contains two messages (already consumed by the CapacityReconciliationConsumer class from the swatch-contracts service):

```json
[
  {
    "topic": "platform.rhsm-subscriptions.capacity-reconcile",
    "key": null,
    "value": {
      "sku": "RH0180192",
      "offset": 100,
      "limit": 100
    },
    "partition": 0,
    "offset": 0
  },
  {
    "topic": "platform.rhsm-subscriptions.capacity-reconcile",
    "key": null,
    "value": {
      "sku": "RH0180192",
      "offset": 200,
      "limit": 100
    },
    "partition": 0,
    "offset": 1
  }
]
```

9.- Verify that the subscriptions have now the expected measurements:

```
select * from subscription_measurements order by subscription_id, metric_id
```

10.- Let's now to verify that the subscription sync can enqueue tasks to be consumed by the swatch-contracts service. 

First, we're going to delete all the subscription measurements entries by running `delete from subscription_measurements`

11.- Start the subscription sync service: `PRODUCT_USE_STUB=true DEV_MODE=true SPRING_PROFILES_ACTIVE=capacity-ingress,api,kafka-queue ./gradlew :bootRun`

12.- Call the offering sync service:

`curl -X PUT -H 'x-rh-swatch-psk:placeholder' -H 'Origin:console.redhat.com' http://localhost:8000/api/rhsm-subscriptions/v1/internal/rpc/offerings/sync/RH0180192`

13.- Verify that the swatch contracts handle the sync task by checking the application logs:

```
> IDL2024-06-17 10:36:10,971 INFO  [com.red.swa.con.ser.CapacityReconciliationConsumer] (vert.x-worker-thread-1) {sampled=true, spanId=16c0eaef1e65d2c5, traceId=caf5adb8ac769eb10980163d30058b32} Capacity Reconciliation Worker is reconciling capacity for offering with values: ReconcileCapacityByOfferingTask(sku=RH0180192, offset=0, limit=100) 
> IDL2024-06-17 10:36:11,070 INFO  [com.red.swa.con.ser.CapacityReconciliationConsumer] (vert.x-worker-thread-1) {sampled=true, spanId=b8380214ca9b66fc, traceId=39c188c62fdbfda6f769317d5d09a288} Capacity Reconciliation Worker is reconciling capacity for offering with values: ReconcileCapacityByOfferingTask(sku=RH0180192, offset=100, limit=100) 
> IDL2024-06-17 10:36:11,161 INFO  [com.red.swa.con.ser.CapacityReconciliationConsumer] (vert.x-worker-thread-1) {sampled=true, spanId=78e08629c492b3f6, traceId=bebee514531d79b39deea2f5d95eb831} Capacity Reconciliation Worker is reconciling capacity for offering with values: ReconcileCapacityByOfferingTask(sku=RH0180192, offset=200, limit=100) 
```

14.- Verify that the subscriptions have now the expected measurements:

```
select * from subscription_measurements order by subscription_id, metric_id
```

### CODE REVIEW

**Comment by diegomaranhao** [comment]
Looks good from the QE side, I'll wait for the Dev review to see if changes are needed.

**Review by lindseyburnett — APPROVED** [review]

**Pull request merged**
