### PR TITLE
SWATCH-2742: key constraint exception during account reset

### PR DESCRIPTION
**Pull request by awood**
Jira issue: SWATCH-2742

## Description
Calls to ` DELETE .../api/rhsm-subscriptions/v1/internal/rpc/tally/{org_id}` were failing because the code attempted to delete the `account_services` rows while they were still referenced from `hosts`.

I also included a small fix to `insert-mock-hosts` since I discovered that script wasn't working when I was trying to replicate the issue.

## Testing
Unit test only

### CODE REVIEW

**Comment by awood** [comment]
QE can probably skip this one since the issue is already causing a failing test.

**Review by lindseyburnett — APPROVED** [review]

**Pull request merged**
