### PR TITLE
Swatch-444: Replace MetricId enum with class that checks against product-config

### PR DESCRIPTION
**Pull request by kflahert**
Jira issue: [SWATCH-444](https://issues.redhat.com/browse/SWATCH-444)

## Description

Rather than have using an Enum for metricId we now have a class that will validate a metric ID based on what is inside swatch-product-config. This allows for easier maintainability.

### Setup

1. Start app with: `DEV_MODE=true ./gradlew :bootRun`

### Verification

1. Verify below curl requests have no errors:
```
curl -X 'GET' \
  'http://localhost:8000/api/rhsm-subscriptions/v1/tally/products/OpenShift%20Container%20Platform/Cores?granularity=Daily&beginning=2023-07-21T17%3A32%3A28Z&ending=2023-08-21T17%3A32%3A28Z&use_running_totals_format=false' \
  -H 'accept: application/vnd.api+json' \
  -H 'x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6ImFjY291bnQxMjMiLCJ0eXBlIjoiVXNlciIsInVzZXIiOnsiaXNfb3JnX2FkbWluIjp0cnVlfSwiaW50ZXJuYWwiOnsib3JnX2lkIjoib3JnMTIzIn19fQo='
  
  curl -X 'GET' \
  'http://localhost:8000/api/rhsm-subscriptions/v1/capacity/products/OpenShift%20Container%20Platform/Sockets?granularity=Daily&beginning=2023-07-21T17%3A32%3A28Z&ending=2023-07-22T17%3A32%3A28Z' \
  -H 'accept: application/vnd.api+json' \
  -H 'x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6ImFjY291bnQxMjMiLCJ0eXBlIjoiVXNlciIsInVzZXIiOnsiaXNfb3JnX2FkbWluIjp0cnVlfSwiaW50ZXJuYWwiOnsib3JnX2lkIjoib3JnMTIzIn19fQo='
  
  curl -X 'GET' \
  'http://localhost:8000/api/rhsm-subscriptions/v1/instances/products/OpenShift%20Container%20Platform?uom=Cores' \
  -H 'accept: application/json' \
  -H 'x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6ImFjY291bnQxMjMiLCJ0eXBlIjoiVXNlciIsInVzZXIiOnsiaXNfb3JnX2FkbWluIjp0cnVlfSwiaW50ZXJuYWwiOnsib3JnX2lkIjoib3JnMTIzIn19fQo='
```

1. Verify below curl requests return 400 error:
```
curl -X 'GET' \
  'http://localhost:8000/api/rhsm-subscriptions/v1/tally/products/OpenShift%20Container%20Platform/NotAMetric?granularity=Daily&beginning=2023-07-21T17%3A32%3A28Z&ending=2023-08-21T17%3A32%3A28Z&use_running_totals_format=false' \
  -H 'accept: application/vnd.api+json' \
  -H 'x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6ImFjY291bnQxMjMiLCJ0eXBlIjoiVXNlciIsInVzZXIiOnsiaXNfb3JnX2FkbWluIjp0cnVlfSwiaW50ZXJuYWwiOnsib3JnX2lkIjoib3JnMTIzIn19fQo='
  
  curl -X 'GET' \
  'http://localhost:8000/api/rhsm-subscriptions/v1/capacity/products/OpenShift%20Container%20Platform/NotAMetric?granularity=Daily&beginning=2023-07-21T17%3A32%3A28Z&ending=2023-07-22T17%3A32%3A28Z' \
  -H 'accept: application/vnd.api+json' \
  -H 'x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6ImFjY291bnQxMjMiLCJ0eXBlIjoiVXNlciIsInVzZXIiOnsiaXNfb3JnX2FkbWluIjp0cnVlfSwiaW50ZXJuYWwiOnsib3JnX2lkIjoib3JnMTIzIn19fQo='
  
  curl -X 'GET' \
  'http://localhost:8000/api/rhsm-subscriptions/v1/instances/products/OpenShift%20Container%20Platform?uom=NotAMetric' \
  -H 'accept: application/json' \
  -H 'x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6ImFjY291bnQxMjMiLCJ0eXBlIjoiVXNlciIsInVzZXIiOnsiaXNfb3JnX2FkbWluIjp0cnVlfSwiaW50ZXJuYWwiOnsib3JnX2lkIjoib3JnMTIzIn19fQo='
```

### CODE REVIEW

**Comment by Aurobinda55** [comment]
- Added  openshift event 
- Checked  the above APIs with a valid metric ID and got the correct response 
```
sh-5.1$ curl -X 'GET'   'http://swatch-api-service:8000/api/rhsm-subscriptions/v1/tally/products/OpenShift%20Container%20Platform/Sockets?granularity=Daily&beginning=2023-09-03T01%3A32%3A28Z&ending=2023-09-04T23%3A32%3A28Z&use_running_totals_format=false'   -H 'accept: application/vnd.api+json'   -H 'x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6IjcxNDc1MDQiLCJ0eXBlIjoiVXNlciIsInVzZXIiOnsiaXNfb3JnX2FkbWluIjp0cnVlfSwiaW50ZXJuYWwiOnsib3JnX2lkIjoiMTQ1NDEzMDgifX19'
{"data":[{"date":"2023-09-03T00:00:00Z","value":0,"has_data":false},{"date":"2023-09-04T00:00:00Z","value":3,"has_data":true}],"meta":{"count":2,"product":"OpenShift Container Platform","metric_id":"Sockets","granularity":"Daily"}}sh-5.1$ 
```
- Checked  Apis with an invalid metric id and got error with HTTP status code 400 `{"errors":`[{"status":"400","code":"SUBSCRIPTIONS1001", "title":"HTTP 400 Bad Request","detail":"MetricId: NotAMetric not found in configuration"}]}sh-5.1$ `

**Review by Aurobinda55 — APPROVED** [review]

**Review by kahowell — CHANGES_REQUESTED** [review]
Given we aligned the values of UOM and metricId, we should give the same treatment to the event.yaml `uom` enum. This will essentially eliminate the `org.candlepin.subscriptions.json.Measurement.Uom` class

**Review by kahowell — APPROVED** [review]

**Comment by ntkathole** [comment]
Tests are failing due to errors in tally pod for `Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "tally_measurements_pkey"`

**Pull request merged**
