### PR TITLE
SWATCH-2368: Move billable-usage components to billable-usage

### PR DESCRIPTION
**Pull request by Sgitario**
Jira issue: SWATCH-2368

## Description
- Fully remove the usages of the TallySnapshotRepository repository in the BillableUsageController controller.
- Internal APIs for billable usage moved from tally service to new billable usage service
- Tally summary consumer.
- refactor tally consumer to perform several transactions
- API changes:

| Old | New  |
|---|---|
|http://swatch-tally-service:8000/api/rhsm-subscriptions/v1/internal/remittance/accountRemittances | http://swatch-billable-usage-service:8000/api/swatch-billable-usage/internal/remittance/accountRemittances |
|http://swatch-tally-service:8000/api/rhsm-subscriptions/v1/internal/rpc/remittance/reset_billable_usage_remittance | http://swatch-billable-usage-service:8000/api/swatch-billable-usage/internal/rpc/remittance/reset_billable_usage_remittance |

## Testing
IQE Test MR: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/688
Regression testing only.
smqe-tools needs to be updated to point out to the new API.

### CODE REVIEW

**Review by kflahert — APPROVED** [review]

**Comment by Aurobinda55** [comment]
@Sgitario found some issues with the new remittance API, https://issues.redhat.com/browse/SWATCH-2596 raised investigate.

**Comment by Sgitario** [comment]
> @Sgitario found some issues with the new remittance API, https://issues.redhat.com/browse/SWATCH-2596 raised investigate.

Ok, but the issue that you found, is it unrelated to these changes?

**Comment by Aurobinda55** [comment]
> > @Sgitario found some issues with the new remittance API, https://issues.redhat.com/browse/SWATCH-2596 raised investigate.
> 
> Ok, but the issue that you found, is it unrelated to these changes?

I think the issue I found is related to this PR because I tried to get the remittance on stage and EE (on the main branch) and both look good, this  PR has the issue that I mentioned.

**Comment by Sgitario** [comment]
> > > @Sgitario found some issues with the new remittance API, https://issues.redhat.com/browse/SWATCH-2596 raised investigate.
> > 
> > 
> > Ok, but the issue that you found, is it unrelated to these changes?
> 
> I think the issue I found is related to this PR because I tried to get the remittance on stage and EE (on the main branch) and both look good, this PR has the issue that I mentioned.

Then there should not be a separate JIRA for this, but the issue should be addressed here.

**Comment by Aurobinda55** [comment]
thanks, @Sgitario   closed https://issues.redhat.com/browse/SWATCH-2596 as the issue found in this PR.

**Comment by Aurobinda55** [comment]
There are still a few failures and I am currently looking into it.

**Comment by Sgitario** [comment]
> There are still a few failures and I am currently looking into it.

the same issue or other failures?

**Comment by Aurobinda55** [comment]
> > There are still a few failures and I am currently looking into it.
> 
> the same issue or other failures?

different failures might be related to automation but I am not 100% sure about the actual cause and I am currently looking into it

**Comment by Aurobinda55** [comment]
@Sgitario I see another issue in this PR

Reproducer :

- Create one rhacs cluster with usage cores=0.1
- Sync hourly tally 
- Change the status in the remittance records to null 
- Create one more event with usage cores=1.0
- As per https://github.com/RedHatInsights/rhsm-subscriptions/pull/3301 , there should be two records now one in null status and one in pending status and both having remitted value=1.0 . But in this PR there is only one record showing with status null and value 1.0

**Comment by Sgitario** [comment]
> @Sgitario I see another issue in this PR
> 
> Reproducer :
> 
> * Create one rhacs cluster with usage cores=0.1
> * Sync hourly tally
> * Change the status in the remittance records to null
> * Create one more event with usage cores=1.0

Don't you need to trigger the hourly tally here again?

> * As per [SWATCH-2494: Add all status of billable usage remittance together #3301](https://github.com/RedHatInsights/rhsm-subscriptions/pull/3301) , there should be two records  one in null status and one in pending status and both having remitted value=1.0 . But in this PR there is only one record showing with status null and value 1.0

Anyway, I've just updated the PR with removing the checking of an existing billable usage. Now, main and this branch **should** behave the same. 

Can you run the above steps again? Also, please, share the steps including the iqe methods you use, so I can easily reproduce it.

**Comment by Aurobinda55** [comment]
> > @Sgitario I see another issue in this PR
> > Reproducer :
> > 
> > * Create one rhacs cluster with usage cores=0.1
> > * Sync hourly tally
> > * Change the status in the remittance records to null
> > * Create one more event with usage cores=1.0
> 
> Don't you need to trigger the hourly tally here again?
> 
> > * As per [SWATCH-2494: Add all status of billable usage remittance together #3301](https://github.com/RedHatInsights/rhsm-subscriptions/pull/3301) , there should be two records  one in null status and one in pending status and both having remitted value=1.0 . But in this PR there is only one record showing with status null and value 1.0
> 
> Anyway, I've just updated the PR with removing the checking of an existing billable usage. Now, main and this branch **should** behave the same.
> 
> Can you run the above steps again? Also, please, share the steps including the iqe methods you use, so I can easily reproduce it.

@Sgitario I did hourly tally sync but forgot to mention in reproducer, will update

**Comment by Sgitario** [comment]
> > > @Sgitario I see another issue in this PR
> > > Reproducer :
> > > 
> > > * Create one rhacs cluster with usage cores=0.1
> > > * Sync hourly tally
> > > * Change the status in the remittance records to null
> > > * Create one more event with usage cores=1.0
> > 
> > 
> > Don't you need to trigger the hourly tally here again?
> > > * As per [SWATCH-2494: Add all status of billable usage remittance together #3301](https://github.com/RedHatInsights/rhsm-subscriptions/pull/3301) , there should be two records  one in null status and one in pending status and both having remitted value=1.0 . But in this PR there is only one record showing with status null and value 1.0
> > 
> > 
> > Anyway, I've just updated the PR with removing the checking of an existing billable usage. Now, main and this branch **should** behave the same.
> > Can you run the above steps again? Also, please, share the steps including the iqe methods you use, so I can easily reproduce it.
> 
> @Sgitario I did hourly tally sync but forgot to mention in reproducer, will update

ok ok, please try with the latest changes and double check you still see the issue

**Comment by Aurobinda55** [comment]
All tests look good. and passed the smoke test  Changed the remittance api to use the new billable usage(https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/728).

**Review by Aurobinda55 — APPROVED** [review]

**Comment by Sgitario** [comment]
> jcarvaja/SWATCH-2547

Great! Feel free to merge the linked MR, now that I've already merged this pull request.

**Pull request merged**
