### PR TITLE
SWATCH-2278: Move denylist to swatch-contracts and provide functionality to load it

### PR DESCRIPTION
**Pull request by awood**
Jira issue: SWATCH-2278

## Description
Moves the deny-list to the "ownership" of swatch-contracts.  In reality, the configMap is shared across the namespace so ownership is only a nominal concept here.

### Steps
1. Build the images and deploy to the EEs:
    ```
    bin/build-images.sh;
    VER=$(git rev-parse --short=7 HEAD) ;  bonfire deploy rhsm \
    --source=appsre \
    --ref-env insights-production \
    --optional-deps-method none \
    --frontends false \
    --no-remove-resources app:rhsm \
    --timeout 1800 \
    -i quay.io/awood/swatch-metrics=$VER \
    -i quay.io/awood/rhsm-subscriptions=$VER \
    -i quay.io/awood/swatch-contracts=$VER \
    -i quay.io/awood/swatch-producer-aws=$VER \
    -i quay.io/awood/swatch-producer-azure=$VER \
    -i quay.io/awood/swatch-system-conduit=$VER \
    -p swatch-metrics/IMAGE=quay.io/awood/swatch-metrics \
    -p swatch-tally/IMAGE=quay.io/awood/rhsm-subscriptions \
    -p swatch-api/IMAGE=quay.io/awood/rhsm-subscriptions \
    -p swatch-contracts/IMAGE=quay.io/awood/swatch-contracts \
    -p swatch-producer-aws/IMAGE=quay.io/awood/swatch-producer-aws \
    -p swatch-producer-azure/IMAGE=quay.io/awood/swatch-producer-azure \
    -p swatch-system-conduit/IMAGE=quay.io/awood/rhsm-subscriptions \
    -p swatch-system-conduit/CONDUIT_IMAGE=quay.io/awood/swatch-system-conduit \
    -p swatch-producer-red-hat-marketplace/IMAGE=quay.io/awood/rhsm-subscriptions \
    -p swatch-subscription-sync/IMAGE=quay.io/awood/rhsm-subscriptions
    ```

### Verification
1.  Verify the configMap is present in both contracts and subscription-sync
    ```
    oc get pod/$(oc get pods | cut -d' ' -f1 | grep subscription-sync-service) -o json | jq '.spec.volumes[]? | select (.configMap)'
    oc get pod/$(oc get pods | cut -d' ' -f1 | grep contracts-service) -o json | jq '.spec.volumes[]? | select (.configMap)'
    ```

### CODE REVIEW

**Review by Sgitario — CHANGES_REQUESTED** [review]
I think we agreed with removing the configmap altogether and use a plain text file to be shared by both swatch-contracts and the subscription-sync. I've confirmed that the acceptance criteria is updated to state that. 

Also, there is an unexpected change of the file `poetry.lock` that it's not related to this PR.

**Comment by awood** [comment]
> I think we agreed with removing the configmap altogether and use a plain text file to be shared by both swatch-contracts and the subscription-sync. I've confirmed that the acceptance criteria is updated to state that.

Yes, I'm electing not to do that.  The ConfigMap is shared across the namespace so both pods will be able to access it.  I discussed the matter with @barnabycourt and @kahowell and they both seemed fine with retaining it as a ConfigMap.  What I would like to do is eventually, move this ConfigMap into App-SRE and then add the `qontract.recycle` annotation to it so we can modify the map and have the pods restart without having to do a full release process.

The `poetry.lock` update is just to get bonfire to the lastest version.  I consider it a minor maintenance task and just tossed it in (but as a discrete commit) but if you want it as a separate PR, I can do that.

**Comment by Sgitario** [comment]
We had discussed this topic in two meetings... Fine with me to duplicate the config map and the logic as it will be eventually deleted. I'm adding @kahowell and @barnabycourt as reviewers.

**Review by Sgitario — APPROVED** [review]

**Review by lindseyburnett — APPROVED** [review]

**Pull request merged**
