### PR TITLE
swatch-1382 add metric_id to tally_summary kafka messages

### PR DESCRIPTION
**Pull request by kflahert**
Jira issue: SWATCH-1382

## Description

Add metric_id to tally summary kafka messages and deprecate UOM.

### Setup

1. Start a kafka consumer for platform.rhsm-subscriptions.tally

### Steps

1. Run a tally with any valid data. Can follow steps if you don't have the data already: https://github.com/RedHatInsights/rhsm-subscriptions/pull/3120

### Verification

1. Check kafka consumer for messages that should have metric_id value populated matching UOM.

### CODE REVIEW

**Review by mstead — APPROVED** [review]
Looks good.

**Comment by ssidhaye** [comment]
```

In [7]: app.rhsm_subscriptions.get_account_remittance('RHEL for x86')
2024-03-19 07:18:19.141 [    INFO] [root] GET request response url: http://swatch-tally-service:8000/api/rhsm-subscriptions/v1/internal/remittance/accountRemittances?productId=RHEL+for+x86&orgId=3340851, status_code: 200
2024-03-19 07:18:19.142 [    INFO] [root] Response: [
    {
        "orgId": "3340851",
        "productId": "RHEL for x86",
        "remittedValue": 0.0
    }
]
Out[7]: [{'orgId': '3340851', 'productId': 'RHEL for x86', 'remittedValue': 0.0}]

n [32]: app.rhsm_subscriptions.create_virtual_rhel(sockets=4,cores=2, rh_prod=['69']
  ...: )
2024-03-19 09:26:04.902 [    INFO] [iqe_host_inventory.modeling.kafka_interaction] producing host messages


Out[32]: 
{'display_name': 'virtual_mockjlztlrkx.test.org',
'hardware_type': 'PHYSICAL',
'sockets': 4,
'subscription_manager_id': 'feeab2f0-0731-4305-9298-c5e45c53f485'}

In [33]: app.rhsm_subscriptions.create_physical_rhel(sockets=4,cores=2, rh_prod=['69'
   ...: ])
2024-03-19 09:26:13.788 [    INFO] [iqe_host_inventory.modeling.kafka_interaction] producing host messages

Out[33]: 
{'display_name': 'physical_mockqujesbun.test.info',
'hardware_type': 'PHYSICAL',
'sockets': 4,
'subscription_manager_id': '7e9a16fb-dd80-4f82-8306-ea73290714b8'}


In [34]: app.rhsm_subscriptions.create_public_cloud(cloud_provider='AWS')
2024-03-19 09:26:19.659 [    INFO] [iqe_host_inventory.modeling.kafka_interaction] producing host messages

Out[34]: 
{'display_name': 'cloud_mock_aws_ctdqypcy.example.info',
 'hardware_type': 'CLOUD',
 'sockets': 1,
 'subscription_manager_id': '5f5e67ab-dd3f-4788-a0db-3a9a30ab1231',
 'measurement_type': 'AWS',
 'cloud_provider': 'AWS'}
```


**Remittance after creating instances**

```
In [48]: app.rhsm_subscriptions.get_account_r
    ...: emittance('OpenShift Container Platf
    ...: orm')
2024-03-19 14:57:04.332 [    INFO] [root] GET request response url: http://swatch-tally-service:8000/api/rhsm-subscriptions/v1/internal/remittance/accountRemittances?productId=OpenShift+Container+Platform&orgId=3340851, status_code: 200
2024-03-19 14:57:04.333 [    INFO] [root] Response: [
    {
        "orgId": "3340851",
        "productId": "OpenShift Container Platform",
        "remittedValue": 0.0
    }
]
Out[48]: 
[{'orgId': '3340851',
  'productId': 'OpenShift Container Platform',
  'remittedValue': 0.0}]

In [49]: app.rhsm_subscriptions.get_account_r
    ...: emittance('RHEL for x86')
2024-03-19 14:57:18.624 [    INFO] [root] GET request response url: http://swatch-tally-service:8000/api/rhsm-subscriptions/v1/internal/remittance/accountRemittances?productId=RHEL+for+x86&orgId=3340851, status_code: 200
2024-03-19 14:57:18.624 [    INFO] [root] Response: [
    {
        "orgId": "3340851",
        "productId": "RHEL for x86",
        "remittedValue": 0.0
    }
]
Out[49]: [{'orgId': '3340851', 'productId': 'RHEL for x86', 'remittedValue': 0.0}]
```


DB records

```
host_id                              | usage |product_id                 | sla  | as_hypervisor | cores | sockets | measu rement_type | billing_provider | billing_account_id | version
41927f4e-52d9-4ec3-b854-bf6a4f5dd04b |       | RHEL for x86                 | _ANY | f             |     8 |       1 | VIRTUAL          | _ANY             | _ANY               |       0
7df56804-85d6-4d48-bfed-6e8d80ba9e23 | _ANY  | RHEL for x86                 |      | f             |     8 |       1 | VIRTUAL          | _ANY             | _ANY               |       0
26416af8-767e-46b3-b737-62b17e38f7d9 | _ANY  | OpenShift Container Platform |      | f             |     1 |         | VIRTUAL          | _ANY             | _ANY               |       0
```



I was unable to check kafka messages since `fetch_events_in_range` helper is returning nothing and kafka-ui was having problems. @kflahert Is this OK? Or should I wait till I get kafka-ui / fetch_events working again?

**Review by ssidhaye — APPROVED** [review]

**Pull request merged**
