### PR TITLE
SWATCH-1731: Refactor swatch-offering-sync Job to use curl and internal endpoint

### PR DESCRIPTION
**Pull request by Sgitario**
Jira issue: [SWATCH-1731](https://issues.redhat.com/browse/SWATCH-1731)

## Description
For all cronjobs defined in clowdapps, we should migrate to using k8s cronjobs w/ curl against internal endpoints.

## Testing
Confirm that the endpoint is executed every day at 2:00.
Alternatively, you can deploy the application and overwrite the OFFERING_SYNC_SCHEDULE environment property with `OFFERING_SYNC_SCHEDULE=*/5 * * * *` (every 5 min).
Another option is to directly alter the CronJob resource that is generated when installing the Clowd app. The CronJob to modify is named "swatch-subscription-sync-offering-sync".

In the logs of the job created, you should see:

```
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 0 0 0 0 0 0 0 --:--:-- 0:00:01 --:--:-- 0100 59 100 59 0 0 34 0 0:00:01 0:00:01 --:--:-- 34100 59 100 59 0 0 34 0 0:00:01 0:00:01 --:--:-- 34
{"detail":"Enqueued 4 numProducts offerings to be synced."}
```

And in the logs of the swatch-subscription-sync-service:

```
2023-09-27 05:25:03,203 [thread=http-nio-8000-exec-1] [INFO ] [org.candlepin.subscriptions.security.LogPrincipalFilter] self- Internal API: /api/rhsm-subscriptions/v1/internal/rpc/offerings/sync requested by user: self
2023-09-27 05:25:03,474 [thread=http-nio-8000-exec-1] [INFO ] [org.candlepin.subscriptions.capacity.admin.InternalSubscriptionResource] self- Sync all offerings triggered by self
2023-09-27 05:25:04,493 [thread=http-nio-8000-exec-1] [INFO ] [org.candlepin.subscriptions.product.OfferingSyncController] self- Enqueued numOfferingSyncTasks=4 to sync offerings from upstream in enqueueTimeMillis=1019
```

So, the call was made and we confirmed that the service processed it.

### CODE REVIEW

**Comment by ssidhaye** [comment]
After modifying cron schedule for ` swatch-subscription-sync-offering-sync` job , I am able to see correct log messages in `swatch-subscription-sync-service` logs

```
2023-09-28 06:45:02,459 [thread=http-nio-8000-exec-1] [INFO ] [org.candlepin.subscriptions.security.LogPrincipalFilter] self- Internal API: /api/rhsm-subscriptions/v1/internal/rpc/offerings/sync requested by user: self
2023-09-28 06:45:02,527 [thread=http-nio-8000-exec-1] [INFO ] [org.candlepin.subscriptions.capacity.admin.InternalSubscriptionResource] self- Sync all offerings triggered by self
2023-09-28 06:45:03,021 [thread=http-nio-8000-exec-1] [INFO ] [org.candlepin.subscriptions.product.OfferingSyncController] self- Enqueued numOfferingSyncTasks=4 to sync offerings from upstream in enqueueTimeMillis=493
```

**Review by kflahert — APPROVED** [review]

**Review by ssidhaye — APPROVED** [review]

**Pull request merged**
