### PR TITLE
SWATCH-2766: Fix 500 errors due to out-of-bounds page params

### PR DESCRIPTION
**Pull request by kahowell**
Description
===========

Jira issue: SWATCH-2766

When api requests are made w/ parameters that are out-of-bounds (offset > count), some APIs currently throw exceptions.

Note, I also corrected paging implementation in CapacityResource, which was giving an incorrect `count`.

Testing
=======

Perform the steps with both `main` and these changes.

Setup
-----

Run the application:

```shell
DEV_MODE=true RHSM_RBAC_USE_STUB=true ./gradlew :bootRun
```

Steps
-----

Try each of the following requests:

```shell
http :8000/api/rhsm-subscriptions/v1/capacity/products/RHEL%20for%20x86/Cores \
  beginning==2024-07-02T00:00:00.000Z \
  ending==2024-08-31T23:59:59.999Z \
  granularity==Daily \
  use_running_totals_format==true \
  billing_category==on-demand \
  offset==1000 \
  x-rh-identity:$(echo '{"identity":{"internal":{"org_id":"org123"}}}' | base64 -w0)
```

```shell
http :8000/api/rhsm-subscriptions/v1/subscriptions/products/RHEL%20for%20x86 \
  beginning==2024-07-02T00:00:00.000Z \
  ending==2024-08-31T23:59:59.999Z \
  granularity==Daily \
  use_running_totals_format==true \
  billing_category==on-demand \
  offset==1000 \
  x-rh-identity:$(echo '{"identity":{"internal":{"org_id":"org123"}}}' | base64 -w0)
```

```shell
http :8000/api/rhsm-subscriptions/v2/subscriptions/products/RHEL%20for%20x86 \
  beginning==2024-07-02T00:00:00.000Z \
  ending==2024-08-31T23:59:59.999Z \
  granularity==Daily \
  use_running_totals_format==true \
  billing_category==on-demand \
  offset==1000 \
  x-rh-identity:$(echo '{"identity":{"internal":{"org_id":"org123"}}}' | base64 -w0)
```

Verification
------------

Notice on `main` the requests return 500s. Notice with these changes, the results are empty.

### CODE REVIEW

**Review by kartikshahc — APPROVED** [review]
LGTM

**Comment by kartikshahc** [comment]
@kahowell I was going to ask why  snapshotPage = InMemoryPager.paginate(capacities, Pageable.unpaged()); but, then I saw your recent changes with the added or condition so I am clear.

**Review by mmusil — APPROVED** [review]

**Comment by kahowell** [comment]
Actually addresses https://issues.redhat.com/browse/SWATCH-2773, jira reference was typo'd.

**Pull request merged**
