### PR TITLE
Adjust contract units to measured units before calculating remittance

### PR DESCRIPTION
**Pull request by mstead**
Jira issue: [SWATCH-1206](https://issues.redhat.com/browse/SWATCH-1206)

## Description
Snapshots store usage values in measured units. Contract values coming from the contract service are in billing units.

When calculating remittance, the contracted value must be converted into measured units so that it can be deducted from the measured usage coming from the snapshots. This defines the applicable measured usage that should be used when determining remittance and billed for when required.

applicable_usage = snapshot_total - (contract / billing_factor)

For example, given a contract with 1 4vCPU capacity (billing factor of 0.25), and a tally measurement of 4 vCPUs, the contract should cover the entire tally measurement (assuming it's the first measurement covered by the contract).

applicable_usage = 4 - (1 / 0.25) = 0

### Setup

Prep your DB.
**NOTE** This will truncate/drop some tables.
```
psql -h localhost -U rhsm-subscriptions <<EOF
drop table events;
truncate table hosts cascade;
truncate table tally_snapshots cascade;
truncate table contracts cascade;
EOF
```

Use the attached [remittance-billing-factor-event-data.txt](https://github.com/RedHatInsights/rhsm-subscriptions/files/11407548/remittance-billing-factor-event-data.txt) file to import event metric data into your DB for Feb and March.
```
psql -h localhost -U rhsm-subscriptions < remittance-billing-factor-event-data.txt
```

Create the necessary contracts.
```
psql -h localhost -U rhsm-subscriptions <<EOF
insert into contracts (uuid, org_id, subscription_number, sku, billing_provider, billing_account_id, product_id, last_updated, start_date, end_date, vendor_product_code) values ('429fa1e9-341f-45b8-b4e3-c72ce9f0f3e2', 'org123', '1111', 'RHBASILISK', 'aws', 'mktp-123', 'BASILISK', '2023-02-01 00:00:00.0-00', '2023-02-01 00:00:00.0-00', '2023-02-28 23:59:59.999999-00', 'AWS_BASILISK');
insert into contract_metrics (contract_uuid, metric_id, metric_value) values ('429fa1e9-341f-45b8-b4e3-c72ce9f0f3e2', 'Instance-hours', 500.0);
insert into contracts (uuid, org_id, subscription_number, sku, billing_provider, billing_account_id, product_id, last_updated, start_date, vendor_product_code) values ('bb4ca273-d40f-4875-b75d-89c1d5c690b9', 'org123', '1111', 'RHBASILISK', 'aws', 'mktp-123', 'BASILISK', '2023-03-01 00:00:00.0-00', '2023-03-01 00:00:00.0-00', 'AWS_BASILISK');
insert into contract_metrics (contract_uuid, metric_id, metric_value) values ('bb4ca273-d40f-4875-b75d-89c1d5c690b9', 'Instance-hours', 1000.0);
insert into contracts (uuid, org_id, subscription_number, sku, billing_provider, billing_account_id, product_id, last_updated, start_date, end_date, vendor_product_code) values ('429fa1e9-341f-45b8-b4e3-c72ce9f0f3e1', 'org123', '2222', 'RHROSA', 'aws', 'mktp-123', 'rosa', '2023-02-01 00:00:00.0-00', '2023-02-01 00:00:00.0-00', '2023-02-28 23:59:59.999999-00', 'AWS_ROSA');
insert into contract_metrics (contract_uuid, metric_id, metric_value) values ('429fa1e9-341f-45b8-b4e3-c72ce9f0f3e1', 'Cores', 100.0);
insert into contracts (uuid, org_id, subscription_number, sku, billing_provider, billing_account_id, product_id, last_updated, start_date, vendor_product_code) values ('bb4ca273-d40f-4875-b75d-89c1d5c690b2', 'org123', '2222', 'RHROSA', 'aws', 'mktp-123', 'rosa', '2023-03-01 00:00:00.0-00', '2023-03-01 00:00:00.0-00', 'AWS_ROSA');
insert into contract_metrics (contract_uuid, metric_id, metric_value) values ('bb4ca273-d40f-4875-b75d-89c1d5c690b2', 'Cores', 1000.0);
EOF
```
### Steps
Start swatch-contracts in **terminal 1**
```
SERVER_PORT=8882 ./gradlew  :swatch-contracts:quarkusDev
```

Start the Tally worker in terminal 2
```
SPRING_PROFILES_ACTIVE=worker,kafka-task-queue SWATCH_CONTRACTS_INTERNAL_SERVICE_URL=http://localhost:8882 DEV_MODE=true ./gradlew :bootRun
```

Perform a nightly tally across the event date ranges and ensure that snapshot summaries were created for BASILISK Instance-hours and rosa Cores.
```
http :9000/hawtio/jolokia   type=exec   mbean='org.candlepin.subscriptions.jmx:name=tallyJmxBean,type=TallyJmxBean'   operation='tallyOrgByHourly(java.lang.String,java.lang.String,java.lang.String)'   arguments:='["org123", "2023-02-01T00:00Z", "2023-03-16T00:00Z"]'
```

### Verification

**NOTE** When we are validating the remittance data in the table, we will assume there is nothing currently remitted, and we will base our calculation off of the sum of the the current snapshot values. This is Ok since no matter what snapshot we start at, we will end up with the same remittance.

#### BASILISK Verification
Verify BASILISK Instance-hours remittance first. It is configured with a billing factor of 1.0 (default)

Find the `total_usage` for the single instance under test for Feb and March.
```
psql -U rhsm-subscriptions rhsm-subscriptions -c "select h.instance_id, t.value from instance_monthly_totals t, hosts h where t.instance_id = h.id and month='2023-03' and h.instance_id::text in (select distinct e.instance_id from events e where e.org_id='org123' and extract(month from e.timestamp) = 3 and e.event_type='snapshot_redhat.com:BASILISK:cluster_hour') order by h.instance_id;"
```
```
psql -U rhsm-subscriptions rhsm-subscriptions -c "select h.instance_id, t.value from instance_monthly_totals t, hosts h where t.instance_id = h.id and month='2023-02' and h.instance_id::text in (select distinct e.instance_id from events e where e.org_id='org123' and extract(month from e.timestamp) = 2 and e.event_type='snapshot_redhat.com:BASILISK:cluster_hour') order by h.instance_id;"
```

Verify the correct usage has been remitted. Remittance for both months should be less the contracted amount for that month.

```
psql -U rhsm-subscriptions rhsm-subscriptions -c "select * from billable_usage_remittance where org_id='org123' and product_id='BASILISK' order by accumulation_period;"
```

**Check February**
billing_factor = 1.0
measured_units = 1064.1067677478911
contract_billable_units = 500
contract_measured_units = 500/1.0 = 500
applicable_measured_units = 1064.1067677478911 - 500 = 564.106767748
billable_units = 564.106767748 * 1.0 = 564.106767748
remitted = ceil(564.106767748) = 565

Verify that 565 was remitted for 2023-02 in the remittance table (remitted_value)

**Check March**
billing_factor = 1.0
measured_units = 16990.061835580877
contract_billable_units = 1000
contract_measured_units = 1000/1.0 = 1000
applicable_measured_units = 16990.061835580877 - 1000 = 15990.061835580877
billable_units = 15990.061835580877 * 1.0 = 15990.061835580877
remitted = ceil(15990.061835580877) = 15991

Verify that 15991 was remitted for 2023-03 in the remittance table (remitted_value)

#### ROSA Verification
Next verify rosa Cores Instance-hours. It is configured with a billing factor of 0.25 (tag profile)

Find the `total_usage` for the single instance under test for Feb and March.
```
psql -U rhsm-subscriptions rhsm-subscriptions -c "select h.instance_id, t.value from instance_monthly_totals t, hosts h where t.instance_id = h.id and month='2023-03' and h.instance_id::text in (select distinct e.instance_id from events e where e.org_id='org123' and extract(month from e.timestamp) = 3 and e.event_type='snapshot_redhat.com:rosa:cpu_hour') order by h.instance_id;"
```
```
psql -U rhsm-subscriptions rhsm-subscriptions -c "select h.instance_id, t.value from instance_monthly_totals t, hosts h where t.instance_id = h.id and month='2023-02' and h.instance_id::text in (select distinct e.instance_id from events e where e.org_id='org123' and extract(month from e.timestamp) = 2 and e.event_type='snapshot_redhat.com:rosa:cpu_hour') order by h.instance_id;"
```

Verify the correct usage has been remitted. Remittance for both months should be less the contracted amount for that month.

```
psql -U rhsm-subscriptions rhsm-subscriptions -c "select * from billable_usage_remittance where org_id='org123' and product_id='rosa' order by accumulation_period;"
```

**Check February**
billing_factor = 0.25
measured_units = 1064.1067677478911
contract_billable_units = 100
contract_measured_units = 100/0.25 = 400
applicable_measured_units = 1064.1067677478911 - 400 = 664.106767748
billable_units = 664.106767748 * 0.25 = 166.026691937
remitted = ceil(166.026691937) = 167

Verify that 167 was remitted for 2023-02 in the remittance table (remitted_value)

**Check March**
billing_factor = 0.25
measured_units = 16990.061835580877
contract_billable_units = 1000
contract_measured_units = 1000/0.25 = 4000
applicable_measured_units = 16990.061835580877 - 4000 = 12990.061835581
billable_units = 12990.061835581 * 0.25 = 3247.515458895
remitted = ceil(3247.515458895) = 3248

Verify that 3248 was remitted for 2023-03 in the remittance table (remitted_value)

### CODE REVIEW

**Review by kflahert — APPROVED** [review]

**Review by ntkathole — APPROVED** [review]
VERIFIED on EE

Remittance = math.ceil((usage - (contract/billing_factor)) * billing_factor)

Steps:
1. Added contract for 400 Cores
```
{'billing_account_id': 'nikhil',
 'billing_provider': 'aws',
 'metrics': [{'metric_id': 'Instance-hours', 'value': 400},
  {'metric_id': 'Cores', 'value': 400}],
 'org_id': '3340851',
 'product_id': 'rosa',
 'sku': 'de356f08-087d-49e7-b824-210506383f8e',
 'start_date': '2023-05-08T08:44:56Z',
 'subscription_number': '8f9dd4e1-f4a7-41a6-84c2-2438ab10a41a',
 'uuid': 'b760363f-20bc-4583-a6a6-89080680019c',
 'vendor_product_code': '0744608c-2d1c-4aca-9367-716cf24bcb60'}
```
2. Created usage of 2000 Cores
```

[{'id': '4a8fb9c4-7637-4d57-8182-1ce3ce9b61a8',
  'instance_id': '3d881eca-c773-4600-a1f6-48fb4d13db1e',
  'display_name': 'automation_moa-hostedcontrolplane_cluster_3d881eca-c773-4600-a1f6-48fb4d13db1e',
  'billing_provider': 'aws',
  'billing_account_id': 'nikhil',
  'measurements': [2000.0, 2000.0],
  'last_seen': datetime.datetime(2023, 5, 8, 9, 0, tzinfo=tzlocal()),
  'number_of_guests': 0,
  '_labeled_measurements': {'Cores': 2000.0, 'Instance-hours': 2000.0}}]
```
3. Sync tally and final remittance as expected 
```
[{'orgId': '3340851',
  'productId': 'rosa',
  'metricId': 'Instance-hours',
  'billingProvider': 'aws',
  'billingAccountId': 'nikhil',
  'remittedValue': 1600.0,
  'accumulationPeriod': '2023-05',
  'remittanceDate': '2023-05-08T10:45:36.43719Z'},
 {'orgId': '3340851',
  'productId': 'rosa',
  'metricId': 'Cores',
  'billingProvider': 'aws',
  'billingAccountId': 'nikhil',
  'remittedValue': 100.0,
  'accumulationPeriod': '2023-05',
  'remittanceDate': '2023-05-08T10:45:36.444877Z'}]
```

Automation updated - [iqe-rhsm-subscriptions-plugin/-/merge_requests/424](https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/424)

**Pull request merged**
