### PR TITLE
SWATCH-2505 Remove use of uom for Sku Capacity Report from v1

### PR DESCRIPTION
**Pull request by kartikshahc**
Jira issue: SWATCH-2505

## Description

Remove use of uom for Sku Capacity Report from v1. We will remove the v1 API itself since we have a related card in GUI to use v2 APIs. https://issues.redhat.com/browse/SWATCH-2410
I had following data in database but, seems like we may need more testing other than the happy path. I rely on QE test since I am not sure what exact data is needed to get the response and how the UI queries the backend. 

## Testing

IQE Test MR: 

### Setup

Insert records:
```
INSERT INTO public.org_config (org_id, opt_in_type, created, updated) VALUES ('org123', 'PROMETHEUS', '2024-08-06 17:51:43.999993 +00:00', '2024-08-06 17:51:43.999993 +00:00');
```

```
INSERT INTO public.offering (sku, product_name, product_family, cores, sockets, hypervisor_cores, hypervisor_sockets, role, sla, usage, description, has_unlimited_usage, derived_sku, metered, special_pricing_flag, level_1, level_2) VALUES ('RH00004', 'RHEL Server', 'Red Hat Enterprise Linux', null, 2, null, null, 'Red Hat Enterprise Linux Server', 'Standard', 'Production', 'Red Hat Enterprise Linux Server, Standard (Physical or Virtual Nodes)', false, '', false, '', null, null);
INSERT INTO public.offering (sku, product_name, product_family, cores, sockets, hypervisor_cores, hypervisor_sockets, role, sla, usage, description, has_unlimited_usage, derived_sku, metered, special_pricing_flag, level_1, level_2) VALUES ('RH3413336', 'RHEL Developer Workstation', 'Red Hat Enterprise Linux', null, 2, null, null, '', '', 'Development/Test', 'Red Hat Enterprise Linux Developer Workstation, Enterprise', false, '', false, '', null, null);
```

```
INSERT INTO public.sku_product_tag (sku, product_tag) VALUES ('RH00004', 'RHEL for x86');
INSERT INTO public.sku_product_tag (sku, product_tag) VALUES ('RH3413336', 'RHEL for x86');
```

```
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, subscription_number, billing_provider, billing_account_id) VALUES ('RH00004', 'org123', '1234567', 2, '2024-06-01 04:00:00.000000 +00:00', '2025-05-31 04:00:00.000000 +00:00', '', '1223456', '', '');
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, subscription_number, billing_provider, billing_account_id) VALUES ('RH3413336', 'org123', '235255', 1, '2011-01-01 01:02:33.000000 +00:00', '2031-01-01 01:02:33.000000 +00:00', null, '2253594', null, null);
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, subscription_number, billing_provider, billing_account_id) VALUES ('RH3413336', 'org123', '1234576', 2, '2021-12-08 22:21:40.392000 +00:00', '2025-12-08 22:38:20.392000 +00:00', null, null, null, null);
```

```
INSERT INTO public.subscription_measurements (subscription_id, start_date, metric_id, measurement_type, value) VALUES ('1234576', '2021-12-08 22:21:40.392000 +00:00', 'SOCKETS', 'PHYSICAL', 4);
INSERT INTO public.subscription_measurements (subscription_id, start_date, metric_id, measurement_type, value) VALUES ('235255', '2011-01-01 01:02:33.000000 +00:00', 'SOCKETS', 'PHYSICAL', 2);
INSERT INTO public.subscription_measurements (subscription_id, start_date, metric_id, measurement_type, value) VALUES ('235255', '2011-01-01 01:02:33.000000 +00:00', 'CORES', 'PHYSICAL', 4);
INSERT INTO public.subscription_measurements (subscription_id, start_date, metric_id, measurement_type, value) VALUES ('1234576', '2021-12-08 22:21:40.392000 +00:00', 'CORES', 'PHYSICAL', 8);
INSERT INTO public.subscription_measurements (subscription_id, start_date, metric_id, measurement_type, value) VALUES ('235255', '2011-01-01 01:02:33.000000 +00:00', 'INSTANCE-HOURS', 'PHYSICAL', 4);
```

1. `RHSM_SUBSCRIPTIONS_ENABLE_SYNCHRONOUS_OPERATIONS=true DEV_MODE=true PROM_URL=http://localhost:8082/api/metrics/v1/telemeter/api/v1 SWATCH_CONTRACTS_INTERNAL_SERVICE=http://localhost:8882 SERVER_PORT=8000 SPRING_PROFILES_ACTIVE=worker,kafka-queue,api,capacity-ingress,rh-marketplace,kafka-queue,rhsm-conduit ./gradlew clean :bootRun`

### Steps

1. Subscription capacity APIs for v1 doesn't need uom:
`http :8000/api/rhsm-subscriptions/v1/subscriptions/products/RHEL%20for%20x86   beginning==2024-07-02T00:00:00.000Z   ending==2024-08-31T23:59:59.999Z   granularity==Daily   use_running_totals_format==true   billing_category==on-demand   offset==1000   x-rh-identity:$(echo '{"identity":{"internal":{"org_id":"org123"}}}' | base64 -w0)`

### Verification

1. Response
```
{
    "data": [],
    "meta": {
        "count": 1,
        "product": "RHEL for x86",
        "subscription_type": "Annual"
    }
}
```

### Steps

2. Capacity APIs for v1 doesn't need uom:
`http :8000/api/rhsm-subscriptions/v1/capacity/products/RHEL%20for%20x86/Sockets   beginning==2024-07-02T00:00:00.000Z   ending==2024-08-31T23:59:59.999Z   granularity==Daily   use_running_totals_format==true   billing_category==on-demand   offset==1000   x-rh-identity:$(echo '{"identity":{"internal":{"org_id":"org123"}}}' | base64 -w0)`

### Verification

2. Response
```
{
    "data": [],
    "links": {
        "first": "/api/rhsm-subscriptions/v1/capacity/products/RHEL%20for%20x86/Sockets?beginning=2024-07-02T00%3A00%3A00.000Z&ending=2024-08-31T23%3A59%3A59.999Z&granularity=Daily&use_running_totals_format=true&billing_category=on-demand&offset=0",
        "last": "/api/rhsm-subscriptions/v1/capacity/products/RHEL%20for%20x86/Sockets?beginning=2024-07-02T00%3A00%3A00.000Z&ending=2024-08-31T23%3A59%3A59.999Z&granularity=Daily&use_running_totals_format=true&billing_category=on-demand&offset=50",
        "previous": "/api/rhsm-subscriptions/v1/capacity/products/RHEL%20for%20x86/Sockets?beginning=2024-07-02T00%3A00%3A00.000Z&ending=2024-08-31T23%3A59%3A59.999Z&granularity=Daily&use_running_totals_format=true&billing_category=on-demand&offset=950"
    },
    "meta": {
        "count": 61,
        "granularity": "Daily",
        "metric_id": "Sockets",
        "product": "RHEL for x86"
    }
}

```

### CODE REVIEW

**Review by kflahert — APPROVED** [review]

**Comment by mmusil** [comment]
iqe-rhsm_subscription-plugin [PR#947](https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/847)

All verification steps performed in EE, looking good.

IQE:
```
In [4]: app.rhsm_subscriptions.rest_client.subscriptions_api.get_sku_capacity_report(product_id="RHEL for x86", uom="sockets")
ApiTypeError: Got an unexpected parameter 'uom' to method `get_sku_capacity_report`

In [8]: app.rhsm_subscriptions.rest_client.capacity_api.get_capacity_report_by_metric_id(product_id="RHEL for x86", metric_id="sockets", uom="sockets
   ...: ", granularity="Daily", beginning='2024-08-01T00:00:00Z', ending='2024-08-31T23:59:59.999Z')
  ApiTypeError: Got an unexpected parameter 'uom' to method `get_capacity_report_by_metric_id`

In [20]: app.rhsm_subscriptions.rest_client.subscriptions_api.get_sku_capacity_report(product_id="RHEL for x86")
2024-08-29 08:17:40.541 [    INFO] [iqe.base.rest_client] REST: GET http://swatch-api-service.ephemeral-jzjkwf.svc:8000/api/rhsm-subscriptions/v1/subscriptions/products/RHEL%20for%20x86 with query params [] and x-rh-insights-request-id=None
Out[20]: 
{'data': [{'billing_provider': '',
           'capacity': 8,
           'has_infinite_quantity': False,
           'hypervisor_capacity': 0,
           'metric_id': 'Cores',
           'next_event_date': datetime.datetime(2025, 4, 6, 4, 0, tzinfo=tzlocal()),
           'next_event_type': 'Subscription End',
           'product_name': 'Red Hat OpenShift Container Platform, Premium (2 '
                           'Cores or 4 vCPUs, Embedded, Billing)',
           'quantity': 4,
           'service_level': 'Premium',
           'sku': 'MCT3263',
           'subscriptions': [{...}],
           'total_capacity': 8,
           'usage': ''},
          {'billing_provider': '',
           'capacity': 0,
           'has_infinite_quantity': False,
           'hypervisor_capacity': 6,
           'metric_id': 'Sockets',
           'next_event_date': datetime.datetime(2024, 8, 31, 4, 0, tzinfo=tzlocal()),
           'next_event_type': 'Subscription End',
           'product_name': 'Red Hat Enterprise Linux for Virtual Datacenters, '
                           'Premium',
           'quantity': 3,
           'service_level': 'Premium',
           'sku': 'RH00001',
           'subscriptions': [{...}],
           'total_capacity': 6,
           'usage': 'Production'},
          {'billing_provider': '',
           'capacity': 0,
           'has_infinite_quantity': False,
           'hypervisor_capacity': 16,
           'metric_id': 'Sockets',
           'next_event_date': datetime.datetime(2026, 2, 24, 0, 0, tzinfo=tzlocal()),
           'next_event_type': 'Subscription End',
           'product_name': 'Red Hat Enterprise Linux for Virtual Datacenters, '
                           'Premium',
           'quantity': 8,
           'service_level': 'Premium',
           'sku': 'RH00001F3',
           'subscriptions': [{...}],
           'total_capacity': 16,
           'usage': 'Production'},
          {'billing_provider': '',
           'capacity': 0,
           'has_infinite_quantity': False,
           'hypervisor_capacity': 12,
           'metric_id': 'Sockets',
           'next_event_date': datetime.datetime(2028, 2, 24, 0, 0, tzinfo=tzlocal()),
           'next_event_type': 'Subscription End',
           'product_name': 'Red Hat Enterprise Linux for Virtual Datacenters, '
                           'Premium',
           'quantity': 6,
           'service_level': 'Premium',
           'sku': 'RH00001F5',
           'subscriptions': [{...}],
           'total_capacity': 12,
           'usage': 'Production'},
          {'billing_provider': '',
           'capacity': 0,
           'has_infinite_quantity': False,
           'hypervisor_capacity': 12,
           'metric_id': 'Sockets',
           'next_event_date': datetime.datetime(2026, 2, 24, 0, 0, tzinfo=tzlocal()),
           'next_event_type': 'Subscription End',
           'product_name': 'Red Hat Enterprise Linux for Virtual Datacenters, '
                           'Standard',
           'quantity': 6,
           'service_level': 'Standard',
           'sku': 'RH00002F3',
           'subscriptions': [{...}],
           'total_capacity': 12,
           'usage': 'Production'},
          {'billing_provider': '',
           'capacity': 0,
           'has_infinite_quantity': False,
           'hypervisor_capacity': 12,
           'metric_id': 'Sockets',
           'next_event_date': datetime.datetime(2028, 2, 24, 0, 0, tzinfo=tzlocal()),
           'next_event_type': 'Subscription End',
           'product_name': 'Red Hat Enterprise Linux for Virtual Datacenters, '
                           'Standard',
           'quantity': 6,
           'service_level': 'Standard',
           'sku': 'RH00002F5',
           'subscriptions': [{...}],
           'total_capacity': 12,
           'usage': 'Production'},
          {'billing_provider': '',
           'capacity': 2,
           'has_infinite_quantity': False,
           'hypervisor_capacity': 0,
           'metric_id': 'Sockets',
           'next_event_date': datetime.datetime(2024, 8, 31, 4, 0, tzinfo=tzlocal()),
           'next_event_type': 'Subscription End',
           'product_name': 'Red Hat Enterprise Linux Server, Premium (Physical '
                           'or Virtual Nodes)',
           'quantity': 1,
           'service_level': 'Premium',
           'sku': 'RH00003',
           'subscriptions': [{...}],
           'total_capacity': 2,
           'usage': 'Production'},
          {'billing_provider': '',
           'capacity': 466,
           'has_infinite_quantity': False,
           'hypervisor_capacity': 0,
           'metric_id': 'Sockets',
           'next_event_date': datetime.datetime(2024, 8, 30, 4, 0, tzinfo=tzlocal()),
           'next_event_type': 'Subscription End',
           'product_name': 'Red Hat Enterprise Linux Server, Standard '
                           '(Physical or Virtual Nodes)',
           'quantity': 233,
           'service_level': 'Standard',
           'sku': 'RH00004',
           'subscriptions': [{...}],
           'total_capacity': 466,
           'usage': 'Production'},
          {'billing_provider': '',
           'capacity': 2,
           'has_infinite_quantity': False,
           'hypervisor_capacity': 0,
           'metric_id': 'Sockets',
           'next_event_date': datetime.datetime(2027, 8, 18, 4, 0, tzinfo=tzlocal()),
           'next_event_type': 'Subscription End',
           'product_name': 'Red Hat Enterprise Linux Server, Standard '
                           '(Physical or Virtual Nodes)',
           'quantity': 1,
           'service_level': 'Standard',
           'sku': 'RH00004F3',
           'subscriptions': [{...}],
           'total_capacity': 2,
           'usage': 'Production'},
          {'billing_provider': '',
           'capacity': 4,
           'has_infinite_quantity': False,
           'hypervisor_capacity': 0,
           'metric_id': 'Sockets',
           'next_event_date': datetime.datetime(2025, 2, 20, 0, 0, tzinfo=tzlocal()),
           'next_event_type': 'Subscription End',
           'product_name': 'Red Hat Enterprise Linux Server Entry Level, '
                           'Self-support',
           'quantity': 2,
           'service_level': 'Self-Support',
           'sku': 'RH00005',
           'subscriptions': [{...}],
           'total_capacity': 4,
           'usage': 'Production'},
          {'billing_provider': '',
           'capacity': 0,
           'has_infinite_quantity': False,
           'hypervisor_capacity': 2,
           'metric_id': 'Sockets',
           'next_event_date': datetime.datetime(2025, 8, 18, 4, 0, tzinfo=tzlocal()),
           'next_event_type': 'Subscription End',
           'product_name': 'Red Hat Enterprise Linux for Virtual Datacenters '
                           'with Satellite, Premium',
           'quantity': 1,
           'service_level': 'Premium',
           'sku': 'RH00006',
           'subscriptions': [{'id': '14481930', 'number': '14482087'}],
           'total_capacity': 2,
           'usage': 'Production'},
          {'billing_provider': '',
           'capacity': 0,
           'has_infinite_quantity': False,
           'hypervisor_capacity': 12,
           'metric_id': 'Sockets',
           'next_event_date': datetime.datetime(2026, 2, 24, 0, 0, tzinfo=tzlocal()),
           'next_event_type': 'Subscription End',
           'product_name': 'Red Hat Enterprise Linux for Virtual Datacenters '
                           'with Satellite, Premium',
           'quantity': 6,
           'service_level': 'Premium',
           'sku': 'RH00006F3',
           'subscriptions': [{...}],
           'total_capacity': 12,
           'usage': 'Production'},
          {'billing_provider': '',
           'capacity': 0,
           'has_infinite_quantity': False,
           'hypervisor_capacity': 66,
           'metric_id': 'Sockets',
           'next_event_date': datetime.datetime(2028, 2, 24, 0, 0, tzinfo=tzlocal()),
           'next_event_type': 'Subscription End',
           'product_name': 'Red Hat Enterprise Linux for Virtual Datacenters '
                           'with Satellite, Premium',
           'quantity': 33,
           'service_level': 'Premium',
           'sku': 'RH00006F5',
           'subscriptions': [{...}],
           'total_capacity': 66,
           'usage': 'Production'},
          {'billing_provider': '',
           'capacity': 0,
           'has_infinite_quantity': False,
           'hypervisor_capacity': 12,
           'metric_id': 'Sockets',
           'next_event_date': datetime.datetime(2026, 2, 24, 0, 0, tzinfo=tzlocal()),
           'next_event_type': 'Subscription End',
           'product_name': 'Red Hat Enterprise Linux for Virtual Datacenters '
                           'with Satellite, Standard',
           'quantity': 6,
           'service_level': 'Standard',
           'sku': 'RH00007F3',
           'subscriptions': [{...}],
           'total_capacity': 12,
           'usage': 'Production'},
          {'billing_provider': '',
           'capacity': 0,
           'has_infinite_quantity': False,
           'hypervisor_capacity': 12,
           'metric_id': 'Sockets',
           'next_event_date': datetime.datetime(2028, 2, 24, 0, 0, tzinfo=tzlocal()),
           'next_event_type': 'Subscription End',
           'product_name': 'Red Hat Enterprise Linux for Virtual Datacenters '
                           'with Satellite, Standard',
           'quantity': 6,
           'service_level': 'Standard',
           'sku': 'RH00007F5',
           'subscriptions': [{...}],
           'total_capacity': 12,
           'usage': 'Production'},
          {'billing_provider': '',
           'capacity': 2,
           'has_infinite_quantity': False,
           'hypervisor_capacity': 0,
           'metric_id': 'Sockets',
           'next_event_date': datetime.datetime(2024, 8, 31, 4, 0, tzinfo=tzlocal()),
           'next_event_type': 'Subscription End',
           'product_name': 'Red Hat Enterprise Linux Developer Workstation, '
                           'Enterprise',
           'quantity': 1,
           'service_level': '',
           'sku': 'RH3413336',
           'subscriptions': [{...}],
           'total_capacity': 2,
           'usage': 'Development/Test'}],
 'meta': {'count': 16,
          'product': 'RHEL for x86',
          'subscription_type': 'Annual'}}

```
HTTP verification steps reproduction
```
✗ http :8000/api/rhsm-subscriptions/v1/capacity/products/RHEL%20for%20x86/Sockets \
  beginning==2024-07-02T00:00:00.000Z \
  ending==2024-08-31T23:59:59.999Z \
  granularity==Daily \
  use_running_totals_format==true \
  billing_category==on-demand \
  offset==1000 \
  x-rh-identity: <token>
HTTP/1.1 200 
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Connection: keep-alive
Content-Length: 835
Content-Type: application/vnd.api+json
Date: Thu, 29 Aug 2024 08:59:41 GMT
Expires: 0
Keep-Alive: timeout=60
Pragma: no-cache
Set-Cookie: JSESSIONID=5B7BCF2FCDA9B7A55E637E3A00EFF38F; Path=/; HttpOnly
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 0

{
    "data": [],
    "links": {
        "first": "/api/rhsm-subscriptions/v1/capacity/products/RHEL%20for%20x86/Sockets?beginning=2024-07-02T00%3A00%3A00.000Z&ending=2024-08-31T23%3A59%3A59.999Z&granularity=Daily&use_running_totals_format=true&billing_category=on-demand&offset=0",
        "last": "/api/rhsm-subscriptions/v1/capacity/products/RHEL%20for%20x86/Sockets?beginning=2024-07-02T00%3A00%3A00.000Z&ending=2024-08-31T23%3A59%3A59.999Z&granularity=Daily&use_running_totals_format=true&billing_category=on-demand&offset=50",
        "previous": "/api/rhsm-subscriptions/v1/capacity/products/RHEL%20for%20x86/Sockets?beginning=2024-07-02T00%3A00%3A00.000Z&ending=2024-08-31T23%3A59%3A59.999Z&granularity=Daily&use_running_totals_format=true&billing_category=on-demand&offset=950"
    },
    "meta": {
        "count": 61,
        "granularity": "Daily",
        "metric_id": "Sockets",
        "product": "RHEL for x86"
    }
}
```

**Review by mmusil — APPROVED** [review]

**Comment by mmusil** [comment]
@kartikshahc https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/847 got merged, feel free to merge this.

**Pull request merged**
