### PR TITLE
Add dashboard for validating metrics

### PR DESCRIPTION
**Pull request by kahowell**
https://issues.redhat.com/browse/SWATCH-678

Testing
-------

Install `yq` and then use the following command to get the dashboard JSON:

```
cat dashboards/grafana-dashboard-subscription-watch-metric-validation.configmap.yaml | yq '.data["subscription-watch-metric-validation.json"]' > /tmp/test.json
```

(You can also use `oc extract -f dashboards/grafana-dashboard-subscription-watch-metric-validation.configmap.yaml --confirm` to extract the JSON)

Import the JSON into stage grafana.

Fill out parameters appropriately (see the top panel of the dashboard for details).

### CODE REVIEW

**Comment by barnabycourt** [comment]
Overall this looks really helpful. However, the legends on the stat widget are impossible to read. Also, it is showing measurements for 2 different instances. I would recommend one of the following courses of action.  
A) changing the stat widget so that the query is returning a single value with appropriate label. 
B) Changing to a table so that the value can be read independently for each value with suitable label. 
C) Merging it into the other detected services widget.

**Review by barnabycourt — CHANGES_REQUESTED** [review]
See previous comment

**Comment by kahowell** [comment]
I ended up implementing A) and C)
> A) changing the stat widget so that the query is returning a single value with appropriate label.

The stat widget is now a total across all detected instances.

> C) Merging it into the other detected services widget.

The detected services now has a column with the per instance total across the selected time range.

**Review by barnabycourt — APPROVED** [review]
Love the updates. This will be incredibly helpful

**Pull request merged**
