### PR TITLE
Add RHACS metrics configuration

### PR DESCRIPTION
**Pull request by stehessel**
Draft to add RHACS metrics configuration to Subscription Watch. @kahowell could you take a look and advise if this looks correct?

### CODE REVIEW

**Comment by kahowell** [comment]
ok-to-test

**Comment by stehessel** [comment]
Test metric series in Telemeter stage with `_id=cbm1dfmg26uf3pd68gb0`, `product=rhacs`, `billing_model=marketplace`:

```
subscription_labels{_id="cbm1dfmg26uf3pd68gb0",account="29yhYqdNOMJZ9YxujnJhpWArOMp",billing_model="marketplace",class="Unknown",disconnected="false",ebs_account="10319316",email_domain="redhat.com",external_organization="16064548",has_csm="false",has_tam="false",instance="uhc-acct-mngr-metrics.uhc-stage.svc:8080",job="uhc-acct-mngr-metrics",managed="true",namespace="uhc-stage",organization="29yhYlwmPgDriMIbHoJxD6Wt6hP",product="rhacs",prometheus="openshift-customer-monitoring/ams",receive="true",rhit_web_user_id="55242827",risk="5",service="uhc-acct-mngr-metrics",support="Premium",tenant_id="FB870BF3-9F3A-44FF-9BF7-D7A047A52F43"}


rhacs:rox_central_cluster_metrics_cpu_capacity:avg_over_time1h{_id="cbm1dfmg26uf3pd68gb0",cluster_id="4ee13a50-871d-46b7-bc8b-fb101e02a37a",observability="managed-rhacs",prometheus="rhacs-observability/kafka-prometheus",receive="true",rhacs_instance_id="cbm1dfmg26uf3pd68gb0",tenant_id="FB870BF3-9F3A-44FF-9BF7-D7A047A52F43"}
```

**Comment by kahowell** [comment]
@stehessel there were a few small things outdated and/or that needed fixes. See commits pushed for details. With those, this looks ready to merge IMO, but I'm gonna ask for one more reviewer (since I made some changes :-) )

**Comment by kahowell** [comment]
FYI, I was able to see tallied data showing up in our DB with these changes.

**Comment by stehessel** [comment]
Are there other backend changes required for AWS marketplace integration? What do we have to do for the frontend integration ("Subscription tab" in console)?

**Comment by lindseyburnett** [comment]
card for related front end changes: https://issues.redhat.com/browse/SWATCH-479

**Comment by barnabycourt** [comment]
@stehessel Lets talk offline about the other back-end integrations

**Comment by stehessel** [comment]
Thanks all, I appreciate the help 🙂

**Comment by stehessel** [comment]
Hi,
I have a question about the cores vs vcpu notation in SubWatch. Our PM changed the planned AWS dimension to `vCPU_Hour`. I assume this also need to be changed in https://github.com/RedHatInsights/rhsm-subscriptions/pull/1302/files#diff-2ec33c54c28abcaaab23bb0fded9255f26ef3ca0a4e1c0bede225e702f623eaeR258 then? What about the unit of measure `CORES`? Technically we measure the cpu capacity of a cluster as reported by Kubernetes, so it is the logical cores/vCPU instead of physical cores. Should we keep https://github.com/RedHatInsights/rhsm-subscriptions/pull/1302/files#diff-2ec33c54c28abcaaab23bb0fded9255f26ef3ca0a4e1c0bede225e702f623eaeR259 or do we have to define something else?

**Comment by kahowell** [comment]
@stehessel as far as the CORES/vCPU thing goes, we're just going to handle in the UI, no need to adjust your config changes here. FWIW, we already have a similar duality b/w cores/vCPUs in OSD/OCP - where there are places we refer to the unit as cores, and others as "vCPUs" (for the same measurement). Let's just keep it consistent across the UIs.

**Pull request merged**
