### PR TITLE
SWATCH-1114: internal delete remittance api

### PR DESCRIPTION
**Pull request by kflahert**
This PR is dependent on https://github.com/RedHatInsights/rhsm-subscriptions/pull/2181 merging first.

Jira issue: [SWATCH-1114](https://issues.redhat.com/browse/SWATCH-1114)

## Description

New internal api and cron job to delete remittances older configurable retention policy.

### Setup

1. Deploy app in EE:
```
NAMESPACE=$(bonfire namespace reserve -d 12h)
bonfire deploy rhsm --no-remove-resources swatch-contracts --no-remove-resources swatch-api --no-remove-resources swatch-producer-aws --no-remove-resources swatch-producer-red-hat-marketplace --no-remove-resources swatch-metrics --no-remove-resources swatch-subscription-sync --no-remove-resources swatch-system-conduit --no-remove-resources swatch-tally
```
2. Insert test data:
```
oc exec $(oc -n $NAMESPACE get -o name pod | grep swatch-tally-db | sed -e 's/pod\// /g') -i -t -- psql swatch-tally-db \
-c "INSERT INTO public.account_config VALUES ('account123', 'API', '2023-02-27 19:14:32.53812+00', '2023-02-27 19:14:32.53812+00', 'org123');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2023-06', 'Premium', 'Production', 'aws', 'mktp-123', 0, '2023-06-14 06:00:00+00', 'HOURLY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2023-06', 'Premium', 'Production', 'aws', 'mktp-123', 40, '2023-06-14 12:00:00+00', 'HOURLY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2023-06', 'Premium', 'Production', 'aws', 'mktp-123', 16, '2023-06-14 17:00:00+00', 'HOURLY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2023-06', 'Premium', 'Production', 'aws', 'mktp-123', 56, '2023-06-14 00:00:00+00', 'DAILY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2022-03', 'Premium', 'Production', 'aws', 'mktp-123', 20, '2022-03-14 05:00:00+00', 'HOURLY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2022-03', 'Premium', 'Production', 'aws', 'mktp-123', 92, '2022-03-14 07:00:00+00', 'HOURLY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2022-03', 'Premium', 'Production', 'aws', 'mktp-123', 64, '2022-03-14 23:00:00+00', 'HOURLY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2022-03', 'Premium', 'Production', 'aws', 'mktp-123', 176, '2022-03-14 00:00:00+00', 'DAILY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2023-03', 'Premium', 'Production', 'aws', 'mktp-123', 0, '2023-03-14 03:00:00+00', 'HOURLY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2023-03', 'Premium', 'Production', 'aws', 'mktp-123', 0, '2023-03-14 04:00:00+00', 'HOURLY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2023-03', 'Premium', 'Production', 'aws', 'mktp-123', 0, '2023-03-14 08:00:00+00', 'HOURLY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2023-03', 'Premium', 'Production', 'aws', 'mktp-123', 8, '2023-03-14 09:00:00+00', 'HOURLY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2023-03', 'Premium', 'Production', 'aws', 'mktp-123', 36, '2023-03-14 10:00:00+00', 'HOURLY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2023-03', 'Premium', 'Production', 'aws', 'mktp-123', 36, '2023-03-14 11:00:00+00', 'HOURLY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2023-03', 'Premium', 'Production', 'aws', 'mktp-123', 52, '2023-03-14 13:00:00+00', 'HOURLY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2023-03', 'Premium', 'Production', 'aws', 'mktp-123', 52, '2023-03-14 14:00:00+00', 'HOURLY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2023-03', 'Premium', 'Production', 'aws', 'mktp-123', 96, '2023-03-14 15:00:00+00', 'HOURLY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2023-03', 'Premium', 'Production', 'aws', 'mktp-123', 72, '2023-03-14 16:00:00+00', 'HOURLY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2023-03', 'Premium', 'Production', 'aws', 'mktp-123', 48, '2023-03-14 18:00:00+00', 'HOURLY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2023-03', 'Premium', 'Production', 'aws', 'mktp-123', 20, '2023-03-14 19:00:00+00', 'HOURLY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2023-03', 'Premium', 'Production', 'aws', 'mktp-123', 8, '2023-03-14 20:00:00+00', 'HOURLY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2023-03', 'Premium', 'Production', 'aws', 'mktp-123', 40, '2023-03-14 21:00:00+00', 'HOURLY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2023-03', 'Premium', 'Production', 'aws', 'mktp-123', 96, '2023-03-14 22:00:00+00', 'HOURLY');
INSERT INTO public.billable_usage_remittance VALUES ('account123', 'org123', 'rosa', 'Cores', '2023-03', 'Premium', 'Production', 'aws', 'mktp-123', 564, '2023-03-14 00:00:00+00', 'DAILY');
"; 
```
### Steps

1. Update the remittance-purge job schedule to run in the next minute or two (ex. if its 3:50pm set the schedule for 52 * * * *)
1. Wait for job to finish

### Verification

1. Check db for remittances, only 5 should be left with the newest dates (daily will be saved for 2023-03 since it has a longer retention than hourly)
 `oc exec $(oc -n $NAMESPACE get -o name pod | grep swatch-tally-db | sed -e 's/pod\// /g') -i -t -- psql swatch-tally-db -c "select * from public.billable_usage_remittance;";`

### CODE REVIEW

**Review by kahowell — APPROVED** [review]
LGTM

**Review by Aurobinda55 — APPROVED** [review]
Approved and will verify once the changes are available in the historical remittance feature branch.

**Pull request merged**
