### PR TITLE
SWATCH-2705: Set ApplicationName on postgresql connection

### PR DESCRIPTION
**Pull request by wottop**
Jira issue: SWATCH-2705

## Description

Add the application name to the connection string so queries can be traced back to the application.

### Setup

1. Create a file /tmp/cdappconfig.json:
```{
    "database": {
        "adminPassword": "rhsm-subscriptions",
        "adminUsername": "rhsm-subscriptions",
        "hostname": "localhost",
        "name": "rhsm-subscriptions",
        "password": "rhsm-subscriptions",
        "port": 5432,
        "sslMode": "disable",
        "username": "rhsm-subscriptions"
    },
    "kafka": {
        "brokers": [
            {
                "hostname": "localhost",
                "port": 9092
            }
        ],
        "topics": [
            {
                "name": "platform.rhsm-conduit.tasks",
                "requestedName": "platform.rhsm-conduit.tasks"
            },
            {
                "name": "platform.inventory.host-ingress",
                "requestedName": "platform.inventory.host-ingress"
            }
        ]
    },
    "endpoints": [],
    "metadata": {
        "deployments": [
            {
                "image": "quay.io/cloudservices/swatch-system-conduit:pr-3537-262ad77",
                "name": "service"
            }
        ],
        "envName": "env-ephemeral-fzyud0",
        "name": "swatch-system-conduit"
    },
    "metricsPath": "/metrics",
    "metricsPort": 9000,
    "privatePort": 10000,
    "publicPort": 8000,
    "webPort": 8000
}
 ```
2. ```export ACG_CONFIG=/tmp/cdappconfig.json```
3. Clone https://github.com/RedHatInsights/clowder-quarkus-config-source
4. Use either branch wottop/SWATCH-2705 or main if my branch is already merged
5. Go to local directory for the clowder-quarkus-config-source repo. Run ```mvn install```.
6. Change the dependencies.gradle file for the rhsm-subscriptions project so that the clowder-quarkus-config-source version matches the snapshot jar you just made, i.e.:
```libraries["clowder-quarkus-config-source"] = "com.redhat.cloud.common:clowder-quarkus-config-source:2.6.2-SNAPSHOT``` 

### Steps

1. ```podman-compose up -d```
- Spring Apps
1. ```RHSM_SUBSCRIPTIONS_ENABLE_SYNCHRONOUS_OPERATIONS=true DEV_MODE=true PROM_URL=http://localhost:8082/api/metrics/v1/telemeter/api/v1 SWATCH_CONTRACTS_INTERNAL_SERVICE=http://localhost:8882 SERVER_PORT=8000 SPRING_PROFILES_ACTIVE=worker,kafka-queue,api,capacity-ingress,rh-marketplace,rhsm-conduit ./gradlew clean :bootRun```
- Quarkus App [run separately or change ports]
1. ```SERVER_PORT=8882 ./gradlew  :swatch-contracts:quarkusDev```

### Verification

1. Watch the local database table for the connections
```select usename, application_name, query_start, query from pg_stat_activity```
You will see the application names in the table.

Note: only "swatch-system-conduit" will appear for Spring apps. In a real deployment, you would have a different file for each pod with the appropriate name.

### CODE REVIEW

**Review by kahowell — APPROVED** [review]

**Comment by ntkathole** [comment]
Removing QE, since regression test should be sufficient.

**Pull request merged**
