### PR TITLE
SWATCH-635 Update RHM producer to use internal subs API

### PR DESCRIPTION
**Pull request by mstead**
Jira issue: [SWATCH-635](https://issues.redhat.com/browse/SWATCH-635)

## Description
When the RHM producer attempts to bill for usage, the subscription ID lookup
now occurs via the internal subscription API, instead of via the DB directly.

A springboot internal subscrtiptions client is now being generated for this purpose.

The subscription lookup code has been refactored out into a new class since it is
identical to that of the AWS usage context API.

The RHM producer supports usage context retries, however, max retries is set to 0
by default to follow the configuration of the AWS marketplace producer.

### Setup
Import events for product billed by RHM
Import offering and subscription data for the above product and test account
```
insert into subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, account_number, subscription_number, billing_provider, billing_account_id) values ('MW01485', 'org123', 'sub-id-ocp', 30, '2023-03-26T04:00:00Z', '2024-03-26T04:00:00Z', 'marketPlaceSubsriptionId-1', 'account123', '123456', 'red hat', '');
```

### Test Steps
Deploy the application as follows
```
DEV_MODE=true SUBSCRIPTION_USE_STUB=true USER_USE_STUB=true ./gradlew :bootRun
```

#### Test the API
Try and fetch the context with the internal API.
```
http GET :8000/api/rhsm-subscriptions/v1/internal/subscriptions/rhmUsageContext \
x-rh-swatch-psk:placeholder \
productId=='OpenShift-metrics' \
date=='2023-05-01T03:59:59.999Z' \
orgId=='org123' \
accountNumber=='account123' \
sla=='Premium'
```

The API should respond with:
```
{
    "rhSubscriptionId": "marketPlaceSubsriptionId-1"
}

```

#### Test the RHM producer
Use the Subscriptions JMX endpoint to fake a message to the RHM Producer. Escaping the JSON is a pain, so I used the browser. Navigate to:

http://localhost:9000/hawtio/jmx/operations?nid=root-org.candlepin.subscriptions.rhmarketplace-RhMarketplaceJmxBean-rhMarketplaceJmxBean

Enter the following JSON into the field for submitTallySummary(String) operation and execute it.

```
{
    "org_id":"org123",
    "tally_snapshots": [
        {
            "id": "c204074d-626f-4272-aa05-b6d69d6de16a",
            "billing_provider": "red hat",
            "billing_account_id": "",
            "snapshot_date": 1683659812,
            "product_id": "OpenShift-metrics",
            "usage": "Production",
            "sla": "Premium",
            "granularity": "Hourly",
            "tally_measurements": [
                {
                    "hardware_measurement_type": "TOTAL",
                    "uom": "Cores",
                    "value": 36
                },
                {
                    "hardware_measurement_type": "PHYSICAL",
                    "uom": "Cores",
                    "value": 36
                }
            ]
        }
    ]
}
```

Check the logs and look for the following:
```
2023-05-09 19:47:46,470 [thread=http-nio-8000-exec-1] [INFO ] [org.candlepin.subscriptions.security.LogPrincipalFilter] self- Internal API: /api/rhsm-subscriptions/v1/internal/subscriptions/rhmUsageContext requested by user: self
2023-05-09 19:47:46,572 [thread=http-nio-9000-exec-8] [INFO ] [org.candlepin.subscriptions.rhmarketplace.RhMarketplaceJmxBean] - usageRequest to be sent: class UsageRequest {
    data: [class UsageEvent {
        start: 1683659812000
        end: 1683663412000
        subscriptionId: marketPlaceSubsriptionId-1
        eventId: c204074d-626f-4272-aa05-b6d69d6de16a
        additionalAttributes: {}
        measuredUsage: [class UsageMeasurement {
            chargeId: null
            metricId: redhat.com:openshift_container_platform:cpu_hour
            value: 36.0
        }]
    }]
}
```

The log shows that the RHM Producer looked up the usage context via the internal API, and that it attempted to send usage to RHM with the correct subscription ID that we created our subscription with: **marketPlaceSubsriptionId-1**

##### Missing Subscription 404
Use the same JMX endpoint to test when a subscription does not exist.

```
{
    "org_id":"org456",
    "tally_snapshots": [
        {
            "id": "c204074d-626f-4272-aa05-b6d69d6de16a",
            "billing_provider": "red hat",
            "billing_account_id": "",
            "snapshot_date": 1683659812,
            "product_id": "OpenShift-metrics",
            "usage": "Production",
            "sla": "Premium",
            "granularity": "Hourly",
            "tally_measurements": [
                {
                    "hardware_measurement_type": "TOTAL",
                    "uom": "Cores",
                    "value": 36
                },
                {
                    "hardware_measurement_type": "PHYSICAL",
                    "uom": "Cores",
                    "value": 36
                }
            ]
        }
    ]
}
```

Verify that the error was logged, and that no data was sent.
```
2023-05-10 13:48:01,297 [thread=http-nio-9000-exec-2] [ERROR] [org.candlepin.subscriptions.rhmarketplace.RhMarketplacePayloadMapper] - SUBSCRIPTIONS3001: Could not find marketplace subscription id - API returned code 404
2023-05-10 13:48:01,297 [thread=http-nio-9000-exec-2] [INFO ] [org.candlepin.subscriptions.rhmarketplace.RhMarketplaceJmxBean] - usageRequest to be sent: class UsageRequest {
    data: []
}

```

##### Ambiguous/Duplicate Subscription
Insert another subscription that differs by only the subscription_id
```
psql -U rhsm-subscriptions rhsm-subscriptions -c "insert into subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, account_number, subscription_number, billing_provider, billing_account_id) values ('MW01485', 'org123', 'sub-id-ocp-2', 30, '2023-03-26T04:00:00Z', '2024-03-26T04:00:00Z', 'marketPlaceSubsriptionId-2', 'account123', '123456', 'red hat', '');"
```

Hit the JMX endpoint again with the following data:
```
{
    "org_id":"org123",
    "tally_snapshots": [
        {
            "id": "c204074d-626f-4272-aa05-b6d69d6de16a",
            "billing_provider": "red hat",
            "billing_account_id": "",
            "snapshot_date": 1683659812,
            "product_id": "OpenShift-metrics",
            "usage": "Production",
            "sla": "Premium",
            "granularity": "Hourly",
            "tally_measurements": [
                {
                    "hardware_measurement_type": "TOTAL",
                    "uom": "Cores",
                    "value": 36
                },
                {
                    "hardware_measurement_type": "PHYSICAL",
                    "uom": "Cores",
                    "value": 36
                }
            ]
        }
    ]
}
```

Verify that only one of the subs was used to bill, and that the logs show that there was a duplicate subscription.

```
2023-05-10 13:55:37,434 [thread=http-nio-8000-exec-1] [WARN ] [org.candlepin.subscriptions.capacity.admin.UsageContextSubscriptionProvider] self- Multiple subscriptions found for billing provider RED_HAT account null or for org org123 with key UsageCalculation.Key(productId=OpenShift-metrics, sla=PREMIUM, usage=PRODUCTION, billingProvider=RED_HAT, billingAccountId=_ANY) and product tag OpenShift-metrics. Selecting first result
2023-05-10 13:55:37,465 [thread=http-nio-9000-exec-8] [INFO ] [org.candlepin.subscriptions.rhmarketplace.RhMarketplaceJmxBean] - usageRequest to be sent: class UsageRequest {
    data: [class UsageEvent {
        start: 1683659812000
        end: 1683663412000
        subscriptionId: marketPlaceSubsriptionId-1
        eventId: c204074d-626f-4272-aa05-b6d69d6de16a
        additionalAttributes: {}
        measuredUsage: [class UsageMeasurement {
            chargeId: null
            metricId: redhat.com:openshift_container_platform:cpu_hour
            value: 36.0
        }]
    }]
}
```

### CODE REVIEW

**Review by lindseyburnett — APPROVED** [review]

**Comment by lindseyburnett** [comment]
Code reviewed and verified test steps are working as expected.

**Comment by mstead** [comment]
@Aurobinda55 found an issue with this PR when testing in EE so this will need to be looked at again once a higher priority items has been addressed.

**Comment by mstead** [comment]
@Aurobinda55 After looking into the issues reported, I fixed a configuration issue which was preventing the swatch-producer-red-hat-marketplace-service from successfully making the rhmUsageContext API call.

I was unable to purchase a product in RHM sandbox to line up with the subscription test data which would cause an error sending usage to RHM. That being said, I validated that the correct data based on the PR changes is getting sent to RHM as usage.

**Review by Aurobinda55 — APPROVED** [review]
rhmUsageContext internal api works as expected and rhmUsageContext lookup is called in swatch-producer-red-hat-marketplace-service.  looks good.Verified

**Pull request merged**
