### PR TITLE
SWATCH-1358: Skip metering on metrics based on metered_by_rhel label

### PR DESCRIPTION
**Pull request by awood**
Jira issue: SWATCH-1358

## Description
Subscription Watch should skip metering certain instances which are of billing_model="marketplace". In these instances the metering is performed by the cloud provider, and not by RH, so Swatch should ignore these instances altogether.

Specifically, swatch should ignore any systems having `metered_by_rh = false.`

This PR sets that label as `metered_by_rh!='false',` to ignore entries with `false` but allow entries with the label set to `true` or unset entirely.

### Setup
1. Start a proxy to telemeter using the `telemeter-stage` script in the `swatch-support-scripts` repo.

### Steps
1. Start `swatch-metrics`
    ```
    EVENT_SOURCE=telemeter PROM_URL="http://localhost:8082/api/v1" ./gradlew :swatch-metrics:quarkusDev
    ```
1. Start `tally` on a different port
    ```
    ./gradlew :bootRun --args="--management.server.port=9001 --server.port=8001"
    ```
1. Find an organization to meter.  Go to http://localhost:8082 and enter
    ```
    group(min_over_time(ocm_subscription{product='moa-hostedcontrolplane', external_organization != '', billing_model='marketplace'}[1h])) by (external_organization)
    ```
    as the query and run to find an organization to meter.  Pick an org ID and then run the query
    ```
    max(cluster:usage:workload:capacity_virtual_cpu_hours) by (_id) * on(_id) group_right min_over_time(ocm_subscription{product="moa-hostedcontrolplane", external_organization=~"ORG_HERE", billing_model="marketplace", metered_by_rh!='false', support=~"Premium|Standard|Self-Support|None"}[1h])
    ```
    Replacing `ORG_HERE` with the org ID you picked.

1. Run a call to the metering endpoint for an organization (replacing `ORG_HERE` with the org ID you picked).
    ```
    http POST :8000/api/swatch-metrics/v1/internal/metering/rosa \                      
    orgId==ORG_HERE \
    endDate==$(date -d '-2 hours' --utc +%Y-%m-%dT%H:00:00Z) \
    rangeInMinutes==180 \
    x-rh-swatch-psk:placeholder
    ```

### Verification
1.  You should see metering events in the log output.  I have `com.red.swa.met.ser.pro.PrometheusService` set to DEBUG level (which I think is the default for dev mode) and there is a `Response from prometheus` log entry that shows the events synced over.  The events you see should have the `metered_by_rhel=true` label.
1. Tally will pick up the events and persist them
    ```
    psql -h localhost -U rhsm-subscriptions rhsm-subscriptions -c "select * from events where org_id = 'ORG_HERE"
    ```

### CODE REVIEW

**Review by lindseyburnett — APPROVED** [review]

**Comment by awood** [comment]
@diegomaranhao Does this pass muster with you?  If so, would you mind approving?

**Comment by diegomaranhao** [comment]
working on it

**Review by diegomaranhao — APPROVED** [review]

**Pull request merged**
