### PR TITLE
SWATCH-1362: Use SortKey for collating HBI and swatch systems

### PR DESCRIPTION
**Pull request by kahowell**
Jira issue: [SWATCH-1362](https://issues.redhat.com/browse/SWATCH-1362)

Description
===========

PR #2152 revealed a bug in the sorting of records during collation. The result is the HBI stream and the swatch stream get out of sync, which results in attempts to create redundant records (and attempts to delete the existing record). This surfaced as a unique constraint violation, because the redundant insert now fails.

Collation was relying solely on the inventory ID to decide which stream should be advanced, so when one system had systems that other did not (e.g. HBI having an extra system), and that extra system having a lexicographically larger inventory ID, the wrong stream could be advanced.

Fixing this involved making sure the collator uses a key equivalent to what the database queries do.

Testing
=======

Setup
-----

(Note: you can use truncate on the hosts table if you wish to have cleaner DBs).

<details>
<summary>Insert some test data into HBI:</summary>

```shell
psql -h localhost -U insights insights <<EOF
insert into hosts(id, org_id, created_on, modified_on, account, display_name, facts, system_profile_facts,
                  canonical_facts, stale_timestamp, reporter)
values ('c0000000-0000-0000-0000-000000000000', 'org123', now(), now(), 'account123', 'system1', '{
  "satellite": {
    "system_purpose_role": "Red Hat Enterprise Linux Server"
  }
}', '{
  "infrastructure_type": "virtual",
  "cores_per_socket": "2",
  "number_of_sockets": "1",
  "arch": "x86_64",
  "installed_products": [
    {
      "id": "69"
    },
    {
      "id": "408"
    }
  ]
}', '{
  "subscription_manager_id": "05000000-0000-0000-0000-000000000000",
  "insights_id": "80000000-0000-0000-0000-000000000000"
}', now() + interval '30 days', 'reporter');

insert into hosts(id, org_id, created_on, modified_on, account, display_name, facts, system_profile_facts,
                  canonical_facts, stale_timestamp, reporter)
values ('40000000-0000-0000-0000-000000000000', 'org123', '2023-06-07T14:40:37.079023Z', '2023-06-07T14:40:37.079023Z',
        'account123', 'system2', '{
    "satellite": {
      "virtual_host_uuid": "05d00000-0000-0000-0000-000000000000"
    }
  }', '{
    "infrastructure_type": "virtual",
    "cores_per_socket": "6",
    "number_of_sockets": "1",
    "arch": "x86_64",
    "installed_products": [
      {
        "id": "69"
      },
      {
        "id": "408"
      }
    ]
  }', '{
    "subscription_manager_id": "b0000000-0000-0000-0000-000000000000",
    "insights_id": "70000000-0000-0000-0000-000000000000"
  }', now() + interval '30 days', 'reporter');
EOF
```
</details>

<details>
<summary>Insert some test data into swatch DB:</summary>

```shell
psql -h localhost -U rhsm-subscriptions rhsm-subscriptions <<EOF
insert into account_services(org_id, service_type) values ('org123', 'HBI_HOST');
insert into hosts(id, inventory_id, account_number, insights_id, org_id, display_name, subscription_manager_id,
                  is_guest, hypervisor_uuid, hardware_type, num_of_guests, last_seen, is_unmapped_guest, is_hypervisor,
                  cloud_provider, instance_type, instance_id, billing_provider, billing_account_id)
values ('50000000-0000-0000-0000-000000000000', '40000000-0000-0000-0000-000000000000', 'account123',
        '70000000-0000-0000-0000-000000000000', 'org123',
        'system2', 'b0000000-0000-0000-0000-000000000000', 'true',
        '05d00000-0000-0000-0000-000000000000', 'VIRTUALIZED', null, now(), 'false', 'false',
        null, 'HBI_HOST', '40000000-0000-0000-0000-000000000000', null, null);
EOF
```
</details>

Steps
-----

1. Run the service:

```shell
DEV_MODE=true ./gradlew :bootRun
```

2. Trigger a nightly tally for org123:

```shell
http PUT :8000/api/rhsm-subscriptions/v1/internal/rpc/tally/snapshots/org123 \
  x-rh-swatch-psk:placeholder
```

Verification
------------

Verify no errors in the logs with this branch (`main` has errors)

### CODE REVIEW

**Review by kartikshahc — APPROVED** [review]

**Comment by kartikshahc** [comment]
Tested the steps and LGTM.

**Comment by kahowell** [comment]
@kartikshahc added some additional comments in the code, hope this helps.

**Review by TrayvonMcKnight — APPROVED** [review]
[SWATCH-1362_testing.txt](https://github.com/RedHatInsights/rhsm-subscriptions/files/11884744/SWATCH-1362_testing.txt)

Looks good!

**Pull request merged**
