### PR TITLE
SWATCH-2600: Prometheus mock data for EEs and local testing

### PR DESCRIPTION
**Pull request by awood**
Jira issue: SWATCH-2600

## Description
This PR adds support for deploying a Prometheus pod in the EEs and for allowing the `swatchdog` tool to create better mock prometheus data.  I've also updated the `bin/prometheus-mock-data.sh` script to import the mock data to a local prometheus container.

## Testing
There are two parts to this PR.  The prometheus ClowdApp and the updates to `bin/prometheus-mock-data.sh`/`swatchdog`.  I'm going to break up the testing description accordingly.

### Script Setup
1. Make sure your Python environment is set up.  Install `python3-poetry` if you haven't already.
    ```shell
    poetry install
    ```
2.  Make sure you have [`promtool`](https://github.com/prometheus/prometheus/releases) installed and on your path.  Promtool is a statically linked binary, so I just dropped it in `~/.local/bin` but whatever works for you is fine.

### Script Steps
1. Generate some PromQL
    ```shell
    poetry run swatchdog prometheus promql
    poetry run swatchdog prometheus promql --metric cores
    poetry run swatchdog prometheus promql --product rosa
    ```
    You can test these out in by running `./telemeter-stage` in the swatch-support-scripts repo and then going to the link the script outputs and paste in the PromQL.
1. Generate some mock data.
    ```shell
    poetry run swatchdog prometheus mock-data --file -
    poetry run swatchdog prometheus mock-data --org ABC --account DEF --product AwesomeOS
    poetry run swatchdog prometheus mock-data --start-time 1970-01-01T00:00:00 --end-time 1970-01-01T03:00:00
    poetry run swatchdog prometheus mock-data --metric a 1 5 --metric b 5 10
    poetry run swatchdog prometheus mock-data --file /tmp/my-mock-data.txt
    ```
    Those commands illustrate what the tool can do: custom values for org, account, product, etc; custom start and end times; custom metrics with bounds on the randomly generated values; write out to a file.  Check `--help` for details.

### Script Verification
1. Import some data.  The `bin/prometheus-mock-data.sh` script uses `swatchdog` internally if you don't give it a file directly.
    ```shell
    bin/prometheus-mock-data --metric a 1 10
    ```
3. Go to http://localhost:9090/graph and search `a[1h]`
4. Kill the container.
5. Generate some more!
    ```
    SWATCHDOG_ARGS="--product AwesomeOS" bin/prometheus-mock-data.sh 
    ```
6. Verify at http://localhost:9090/graph and search `ocm_subscription[1h]`

### ClowdApp Setup
1. Get an EE environment up and running and fitted with the standard deployment.  If you have a preferred method, use that.  Here is my preferred method (note that you'll need to change the IMAGE to point to your quay.io repo)
    ```
    bonfire namespace reserve -d 72h && bin/build-images.sh
    # Now deploy
    VER=$(git rev-parse --short=7 HEAD) ;  bonfire deploy rhsm \                                                                                                                                     
    --source=appsre \                                                                                                                                                                                
    --ref-env insights-production \                                                                                                                                                                  
    --optional-deps-method none \                                                                                                                                                                    
    --frontends false \                                                                                                                                                                              
    --no-remove-resources app:rhsm \                                                                                                                                                                 
    --timeout 1800 \                                                                                                                                                                                 
    -i quay.io/awood/swatch-metrics=$VER \                                                                                                                                                           
    -i quay.io/awood/rhsm-subscriptions=$VER \                                                                                                                                                       
    -i quay.io/awood/swatch-contracts=$VER \                                                                                                                                                         
    -i quay.io/awood/swatch-producer-aws=$VER \                                                                                                                                                      
    -i quay.io/awood/swatch-producer-azure=$VER \                                                                                                                                                    
    -i quay.io/awood/swatch-system-conduit=$VER \                                                                                                                                                    
    -p swatch-metrics/IMAGE=quay.io/awood/swatch-metrics \                                                                                                                                           
    -p swatch-tally/IMAGE=quay.io/awood/rhsm-subscriptions \                                                                                                                                         
    -p swatch-api/IMAGE=quay.io/awood/rhsm-subscriptions \                                                                                                                                           
    -p swatch-contracts/IMAGE=quay.io/awood/swatch-contracts \                                                                                                                                       
    -p swatch-producer-aws/IMAGE=quay.io/awood/swatch-producer-aws \                                                                                                                                 
    -p swatch-producer-azure/IMAGE=quay.io/awood/swatch-producer-azure \                                                                                                                             
    -p swatch-system-conduit/IMAGE=quay.io/awood/rhsm-subscriptions \                                                                                                                                
    -p swatch-system-conduit/CONDUIT_IMAGE=quay.io/awood/swatch-system-conduit \                                                                                                                     
    -p swatch-producer-red-hat-marketplace/IMAGE=quay.io/awood/rhsm-subscriptions \                                                                                                                  
    -p swatch-subscription-sync/IMAGE=quay.io/awood/rhsm-subscriptions
    ```
1.  Edit your `~/.config/bonfire/config.yaml` and add the below section to your RHSM components.  Correct the repo line to point to the correct location for your set up.
    ```yaml
    - name: prometheus                                                                                                                                                                               
      host: local                                                                                                                                                                                    
      repo: /home/awood/devel/rhsm-subscriptions/swatch-metrics                                                                                                                                      
      path: /deploy/mock-prometheus-clowdapp.yaml                                                                                                                                                    
      parameters:                                                                                                                                                                                    
        REPLICAS: 1
    ```
    
### ClowdApp Steps
1. Deploy the prometheus ClowdApp
    ```
    bonfire deploy -C prometheus --source=appsre --ref-env=insights-production --no-remove-resources app:rhsm --frontends=false rhsm
    ```
1. Port-forward the pod
    ```
    oc port-forward $(oc get pods | awk '{print $1}' | grep mock-prometheus) 9090:9090
    ```
1. Generate some mock-data and import it.
    ```
    poetry run swatchdog prometheus mock-data --file /tmp/my-mock-data.txt
    promtool push metrics http://localhost:9090/api/v1/write /tmp/my-mock-data.txt
    ```
    
### Verification
1.  You'll see a success message from promtool.  You can also go to http://localhost:9090/graph and search for `ocm_subscription[1h]`

### CODE REVIEW

**Review by Sgitario — APPROVED** [review]

**Comment by san7ket** [comment]
@awood Could we point swatch-metrics and swatch-rhel-metrics to the deployed prometheus by default in EE.

**Comment by Aurobinda55** [comment]
@awood  I have deployed an EE  with the same tag that was used in the PR check jobs, but don’t see Prometheus deployed automatically. So, I manually added the configuration in ~/.config/bonfire/config.yaml and deployed the Prometheus. Can we avoid the manual setup and deploy the Prometheus automatically .

**Comment by awood** [comment]
> @awood I have deployed an EE with the same tag that was used in the PR check jobs, but don’t see Prometheus deployed automatically

Yes, that is a forthcoming MR in app-interface.  But it needs the clowdapp YAML to be present first :)

**Comment by awood** [comment]
> Could we point swatch-metrics and swatch-rhel-metrics to the deployed prometheus by default in EE.

Yes, I'm was going to handle that by overriding `PROM_URL` in the app-interface ephemeral configuration.  So once that MR lands, `swatch-metrics-*` will point to the prometheus pod.

**Comment by Aurobinda55** [comment]
- Deployed EE from this branch 
- Changed the ~/.config/bonfire/config.yaml manually with the details that mentioned above 
- Deployed Prometheus clowder app again 
- Port forwarded to 9090
- From iqe_rhsm_subscription > smqe_tools > telemeter , import push_metrics_to_prometheus
- push_metrics_to_prometheus(product_id="rhacs",org_id="3340851")
- Open http://localhost:9090/graph and see the below result 
image

- Sync the hourly tally 
- Check the system table for the host, but somehow the host is missing as shown in the graph. I am currently looking into our automation script to debug more. But this is not a blocker for this PR. 

Overall looks good to me

**Review by Aurobinda55 — APPROVED** [review]

**Pull request merged**
