### PR TITLE
SWATCH-2872: deploy kafka-bridge as resource

### PR DESCRIPTION
**Pull request by lindseyburnett**
Jira issue: [SWATCH-2872](https://issues.redhat.com/browse/SWATCH-2872)

https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/116440 
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/118877
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/120174

## Testing

IQE Test MR: 

### Setup

1.
1.

### Steps

1.
1.

### Verification

1.
1.

### CODE REVIEW

**Comment by ntkathole** [comment]
@lindseyburnett Looks like EE deployment is not having kafka bridge service running, 2 tests failing

`failed on setup with "requests.exceptions.ConnectionError: HTTPConnectionPool(host='kafka-bridge-bridge-service', port=8080): Max retries exceeded with url: /consumers/iqe_consumer_group (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f6f5bd29f50>: Failed to resolve 'kafka-bridge-bridge-service' ([Errno -2] Name or service not known)"))"`

**Review by kahowell — APPROVED** [review]

**Pull request merged**
