### PR TITLE
Integrate with cloudigrade

### PR DESCRIPTION
**Pull request by kahowell**
The overall strategy I took was to implement a component parallel to `InventoryAccountUsageCollector` named `CloudigradeAccountUsageCollector`, which enriches calculations with data from Cloudigrade.

Additionally, when enriching cloudigrade data into usage data, if that usage data has any HBI-sourced AWS data, the data is adjusted so that the cloudigrade data contributes to the total in place of the HBI AWS data.

Similarly, when transforming a snapshot for API responses, if both HBI-sourced and cloudigrade-sourced data exists for a snapshot, only the cloudigrade sourced measurement will be included.

I intend to configure `CLOUDIGRADE_{ENABLED,HOST,PORT}` in app-interface prior to this change landing in an environment.

I changed the return type of `InventoryAccountUsageCollector.collect` in order to make it easier integrate cloudigrade data.

To verify the requests, I recommend trying `nc -l 8084`, and then launching via:

```
SPRING_PROFILES_ACTIVE=capture-snapshots CLOUDIGRADE_ENABLED=true CLOUDIGRADE_HOST=localhost CLOUDIGRADE_PORT=8084 ./gradlew bootRun
```

Kill `nc` and observe that the tally continues, without cloudmeter data, logging a warning.

To test against an actual cloudigrade instance, forward a local port to a cluster's cloudigrade service. For example, QA can be reached at cloudigrade-api.cloudigrade-qa.svc.cluster.local:80. Reach out to me or QE for an account with data in it.

Then, launch as previously described.

### CODE REVIEW

**Comment by kahowell** [comment]
b7ca1aa to 08b7073: add missing test properties to new test.

**Comment by dozdowski** [comment]
Logic checking to make sure I get it.

In my mind, the OS level data collectors will be our best source of data for "what products are on the system" - as any number of things may be installed post spinup.  Cloud Meter will be our best source of data on "when exactly did this instance stand up and when did it go away?" It will be an additional strong source for "what is RHEL" (the OS being a product that's very hard to uninstall or overinstall) so in cases where we lack HBI data we can trust Cloud Meter alone for RHEL usage.

As I read this, when checking an account's usage for RHEL, we're saying: "IF we know about an instance in HBI, we ignore its contribution to the account's overall RHEL usage and rely on Cloud Meter data to provide for us its contribution to the overall high watermark?"  That correct?

**Comment by kahowell** [comment]
> In my mind, the OS level data collectors will be our best source of data for "what products are on the system" - as any number of things may be installed post spinup. Cloud Meter will be our best source of data on "when exactly did this instance stand up and when did it go away?" It will be an additional strong source for "what is RHEL" (the OS being a product that's very hard to uninstall or overinstall) so in cases where we lack HBI data we can trust Cloud Meter alone for RHEL usage.

Being able to combine those two sources of data more eloquently is a long term goal, _but not in the scope of this PR_. In order to tie these two sources together, we want to move to an event-driven architecture at some point.

> As I read this, when checking an account's usage for RHEL, we're saying: "IF we know about an instance in HBI, we ignore its contribution to the account's overall RHEL usage and rely on Cloud Meter data to provide for us its contribution to the overall high watermark?" That correct?

It's a little bit more blunt than that. When doing a tally, if Cloud Meter returns data about a particular bucket's* max concurrent usage, then we trust that value for AWS usage, and ignore what we derived from HBI data for AWS usage.

\* bucket defined by product, sla, and (eventually) usage

**Comment by kahowell** [comment]
08b7073 to ed98a9c: rebased against master; see other commits for additional changes

**Comment by ntkathole** [comment]
@kahowell can we please get this deployed on CI before merge ?

**Comment by kahowell** [comment]
> @kahowell can we please get this deployed on CI before merge (if its exposing functionality)?

@ntkathole of course. Also, we can hold on merge until QE validation for this one.

**Comment by kahowell** [comment]
cb67a09 to 75f47c0: rebased

**Comment by mstead** [comment]
Latest changed from my request for retry looks good. Needs another rebase sadly.

**Comment by mstead** [comment]
@kahowell FYI: I added the cloudigrade params and env vars to the worker template and fixed up the merge conflict that was in this PR.

I'm going to attempt to get this deployed to CI here in a few minutes.

**Comment by ntkathole** [comment]
@kahowell @mstead cloudmeter CI env is unstable at this time due to latest development code, we are hitting issues with having cloudmeter data generated in account. I think it make sense to deploy PR to QA env and test in QA.

**Comment by kahowell** [comment]
- cd5657a to 6616677: rebase against master
- 6616677 to 09bb6b7: squash

**Comment by mstead** [comment]
Looks good to me.

**Pull request merged**
