### PR TITLE
SWATCH-2023: Add CSV support subscriptions export

### PR DESCRIPTION
**Pull request by Sgitario**
Jira issue: SWATCH-2023

## Description
- Use CsvMapper from Jackson instead of Apache Commons because it's better integrated with the jsonschema. Thanks to this, we can configure the columns order via the jsonschema manifest.
- Move out the json support out of the ExportSubscriptionListener to JsonExportFileWriter
- Support general CSV support in CsvExportFileWriter.
- Refactor the solution to use a factory design pattern to deal with CSV and JSON when mapping the POJOs.
- Separate jsonschemas for JSON and for CSV since the model is different for each one.

## Testing
1.- start kafka and postgresql: `podman-compose up -d`
2.- start export-service: `podman-compose -f config/export-service/docker-compose.yml up -d`
3.- start subscription sync service: `RHSM_RBAC_USE_STUB=true DEV_MODE=true SPRING_PROFILES_ACTIVE="capacity-ingress,api,kafka-queue" ./gradlew :bootRun`
4.- load some data:

```
INSERT INTO offering (sku, product_name, product_family, cores, sockets, hypervisor_cores, hypervisor_sockets, role, sla, usage, description, has_unlimited_usage, derived_sku, metered) VALUES ('MW02393', 'OpenShift Dedicated', 'OpenShift Enterprise', 0, 0, 0, 0, 'osd', 'Premium', 'Production', 'Red Hat OpenShift Service on AWS Hosted Control Planes (Hourly)', false, null, null);
INSERT INTO subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, subscription_number, billing_provider, billing_account_id) VALUES ('MW02393', '13259775', '13579593', 1, '2023-09-25 08:25:22.797423 +00:00', '2024-09-25 08:25:22.000000 +00:00', 'bcwuzc8ww10vvxfair55mliy8;4G5dKpAKahm', '13579750', 'aws', '505066801768');
INSERT INTO subscription_measurements (subscription_id, start_date, metric_id, measurement_type, value) VALUES ('13579593', '2023-09-25 08:25:22.797423 +00:00', 'Cores', 'PHYSICAL', 5);
INSERT INTO subscription_measurements (subscription_id, start_date, metric_id, measurement_type, value) VALUES ('13579593', '2023-09-25 08:25:22.797423 +00:00', 'Instance-hours', 'PHYSICAL', 1);
```

5.- create a new export request from Export Service:

get the identifier first:
```
echo -n '{"identity":{"account_number":"10001","org_id":"13259775","internal":{"org_id":"13259775"},"type":"User","user":{"username":"user_dev"}}}' | base64 -w 0
> eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6IjEwMDAxIiwib3JnX2lkIjoiMTMyNTk3NzUiLCJpbnRlcm5hbCI6eyJvcmdfaWQiOiIxMzI1OTc3NSJ9LCJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiJ1c2VyX2RldiJ9fX0=
```

call the export service:
```
curl -sS -X POST http://localhost:8002/api/export/v1/exports -H "x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6IjEwMDAxIiwib3JnX2lkIjoiMTMyNTk3NzUiLCJpbnRlcm5hbCI6eyJvcmdfaWQiOiIxMzI1OTc3NSJ9LCJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiJ1c2VyX2RldiJ9fX0=" -H "Content-Type: application/json" -d '{
    "name": "Test Export Request",
    "format": "csv",
    "expires_at": "2025-01-01T00:00:00Z",
    "sources": [
        {
            "application": "subscriptions",
            "resource": "subscriptions",
            "filters": {
                "metric_id": "Cores"
            }
        }
    ]
}'
```

Expected output is:
```
{"id":"e81bc918-6434-4a58-9192-8a8dd73ec8fb","created_at":"2024-03-21T09:05:08.943615204Z","expires_at":"2025-01-01T00:00:00Z","name":"Test Export Request","format":"csv","status":"pending","sources":[{"id":"f564ff70-9176-4413-ab6e-96a02c8ee124","application":"subscriptions","status":"pending","resource":"subscriptions","filters":{"metric_id":"Cores"}}]}
```

6.- verification:

check the subscription sync logs where you should see the new event coming from the Export service topic:
```
Processing event: 'd223e4b2-4ac2-43f3-842d-39b9ae4c3a0b' from application: 'urn:redhat:source:console:app:export-service'
Event processed: 'd223e4b2-4ac2-43f3-842d-39b9ae4c3a0b' from application: 'urn:redhat:source:console:app:export-service'
```

The export-service should have uploaded the generated report by the subscription sync service into S3 (minio instance). 
You can verify that this report has been uploaded by checking the folder 'config/export-service/tmp/minio/exports-bucket' where should be a file at `<BUCKET ID>.json/xl.meta`. The `xl.meta` file is binary, but if you open the txt plain editor, you should see:

```
subscription_id,subscription_number,begin,end,quantity,capacity,hypervisor_capacity,metric_id,sku,product_name,service_level,usage
13579593,13579750,"2023-09-25T08:25:22.797423Z",2024-09-25T08:25:22Z,1.0,5,0,Cores,MW02393,"OpenShift Dedicated",Premium,Production
13579593,13579750,"2023-09-25T08:25:22.797423Z",2024-09-25T08:25:22Z,1.0,0,0,Instance-hours,MW02393,"OpenShift Dedicated",Premium,Production
```

### CODE REVIEW

**Comment by Sgitario** [comment]
> > The xl.meta file is binary, but if you open the txt plain editor, you should see
> 
> Fun fact for anyone that stumbles upon this. The minio instance deployed alongside the export service exposes a console that can be used to download the actual file. Creds are in the compose file.
> 
> `http://localhost:9990/`

Yes, QE does it this way.

**Review by mstead — APPROVED** [review]
Overall, this looks good and functions well. I like the pattern you've applied here. Once the PR checks pass this is good to go.

**Comment by san7ket** [comment]
```
In [11]: filters={"sla": "Premium", "usage": "Production"}

In [12]: export = application.rhsm_subscriptions.create_swatch_export_request(format="csv",filters=filters)
2024-04-26 18:25:02.357 [    INFO] [root] Using <function client_obj_maker.<locals>.make_obj at 0x7f8cf0488700> object....with url http://export-service-service.ephemeral-jpunoe.svc:8000/api/export/v1 and verify_ssl set to False
2024-04-26 18:25:02.357 [    INFO] [iqe.base.auth] Setting auth_type to identity
2024-04-26 18:25:02.373 [    INFO] [iqe.base.rest_client] REST: METHOD=POST, request_id=None, params=[]
2024-04-26 18:25:02.375 [    INFO] [root] Waiting for export request with id 1c94aa08-03b5-4e35-87e3-1b566ec8ab81 to process
2024-04-26 18:25:02.375 [    INFO] [root] {'completed_at': None,
 'created_at': datetime.datetime(2024, 4, 26, 18, 25, 2, 369335, tzinfo=tzlocal()),
 'expires_at': datetime.datetime(2024, 5, 3, 18, 25, 2, 369322, tzinfo=tzlocal()),
 'format': 'csv',
 'id': '1c94aa08-03b5-4e35-87e3-1b566ec8ab81',
 'name': 'erAwJsgiuL',
 'sources': [{'application': 'subscriptions',
              'filters': {'sla': 'Premium', 'usage': 'Production'},
              'id': 'f101e663-b2cb-40f8-a981-1acdfcca69c1',
              'resource': 'subscriptions',
              'status': 'pending'}],
 'status': 'pending'}
2024-04-26 18:25:22.404 [    INFO] [iqe.base.rest_client] REST: METHOD=GET, request_id=None, params=[]

In [13]: export
Out[13]: 
{'completed_at': datetime.datetime(2024, 4, 26, 18, 25, 2, 969806, tzinfo=tzlocal()),
 'created_at': datetime.datetime(2024, 4, 26, 18, 25, 2, 369335, tzinfo=tzlocal()),
 'expires_at': datetime.datetime(2024, 5, 3, 18, 25, 2, 369322, tzinfo=tzlocal()),
 'format': 'csv',
 'id': '1c94aa08-03b5-4e35-87e3-1b566ec8ab81',
 'name': 'erAwJsgiuL',
 'sources': [{'application': 'subscriptions',
              'filters': {'sla': 'Premium', 'usage': 'Production'},
              'id': 'f101e663-b2cb-40f8-a981-1acdfcca69c1',
              'resource': 'subscriptions',
              'status': 'success'}],
 'status': 'complete'}

In [14]: application.export_service.rest_client.default_api.download_export(export.id)
2024-04-26 18:26:11.844 [    INFO] [iqe.base.rest_client] REST: METHOD=GET, request_id=None, params=[]
Out[14]: '/tmp/2024-04-26T18:25:02Z-1c94aa08-03b5-4e35-87e3-1b566ec8ab81.tar.gz'

sh-4.4$ cat f101e663-b2cb-40f8-a981-1acdfcca69c1.csv 
subscription_id,subscription_number,begin,end,quantity,capacity,hypervisor_capacity,metric_id,sku,product_name,service_level,usage
14353330,14353487,2023-02-25T00:00:00Z,2026-02-24T00:00:00Z,1.0,0,2,Sockets,RH00001F3,"RHEL Server",Premium,Production
14353331,14353488,2023-02-25T00:00:00Z,2028-02-24T00:00:00Z,1.0,0,2,Sockets,RH00001F5,"RHEL Server",Premium,Production
14353334,14353491,2023-02-25T00:00:00Z,2026-02-24T00:00:00Z,1.0,0,2,Sockets,RH00006F3,"RHEL Server",Premium,Production
14353336,14353493,2023-02-25T00:00:00Z,2028-02-24T00:00:00Z,1.0,0,2,Sockets,RH00006F5,"RHEL Server",Premium,Production
14387528,14387685,2023-03-31T04:00:00Z,2026-03-30T04:00:00Z,1.0,0,2,Sockets,RH00001F3,"RHEL Server",Premium,Production
14387699,14387856,2023-03-31T04:00:00Z,2028-03-30T04:00:00Z,1.0,0,2,Sockets,RH00006F5,"RHEL Server",Premium,Production
14387740,14387897,2023-03-31T04:00:00Z,2028-03-30T04:00:00Z,1.0,0,2,Sockets,RH00006F5,"RHEL Server",Premium,Production
14387744,14387901,2023-03-31T04:00:00Z,2028-03-30T04:00:00Z,1.0,0,2,Sockets,RH00006F5,"RHEL Server",Premium,Production
14387747,14387904,2023-03-31T04:00:00Z,2028-03-30T04:00:00Z,1.0,0,2,Sockets,RH00006F5,"RHEL Server",Premium,Production
14387750,14387907,2023-03-31T04:00:00Z,2028-03-30T04:00:00Z,1.0,0,2,Sockets,RH00006F5,"RHEL Server",Premium,Production
14387754,14387911,2023-03-31T04:00:00Z,2028-03-30T04:00:00Z,1.0,0,2,Sockets,RH00006F5,"RHEL Server",Premium,Production

```

**Review by san7ket — APPROVED** [review]

**Pull request merged**
