### PR TITLE
SWATCH-2644: Add filter for orgId ++ increase performance of view

### PR DESCRIPTION
**Pull request by Sgitario**
Jira issue: SWATCH-2644

## Description
Changes:
- moved the specification to the view repository, so it can be reused in https://github.com/RedHatInsights/rhsm-subscriptions/pull/3423
- improved the view performance by using the WITH clause
- added the has_infinity_quantity and billing_provider_id that will be needed for [SWATCH-2410](https://github.com/RedHatInsights/rhsm-subscriptions/pull/3423)

## Testing
Added new integration tests to reproduce the bug.
For IQE tooling, follow the instructions from the linked JIRA ticket.

### CODE REVIEW

**Comment by san7ket** [comment]
Automated in Stage

**Review by mstead — APPROVED** [review]
Looks good and addresses the bug.

**Pull request merged**
