### PR TITLE
SWATCH-2671 Set CloudProvider and hardware type on Event messages

### PR DESCRIPTION
**Pull request by lindseyburnett**
Jira issue: SWATCH-2671

# Summary
swatch-metrics was producing messages with billing_provider, but not cloud_provider or hardware_type

When hourly tally reads the events, it was defaulting the hardware type to PHYSICAL (org.candlepin.subscriptions.tally.MetricUsageCollector#getHardwareMeasurementType)

Now events from swatch-metrics should include a `cloud_provider` and `hardware_type: 'Cloud'`
# Part 1 - Verify swatch-metrics produces Events with cloud_provider

This will be happening for Events produced by both **swatch-metrics** and **swatch-metrics-rhel**

# swatch-metrics-rhel using rhel-for-x86-els-payg

```bash
EVENT_SOURCE=rhelemeter PROM_URL="http://10.0.150.94/api/v1" ./gradlew :swatch-metrics:quarkusDev
```

```bash
http POST :8000/api/swatch-metrics/v1/internal/metering/rhel-for-x86-els-payg \
orgId==$ORG_ID$ \
endDate==$(date -d '-2 hours' --utc +%Y-%m-%dT%H:00:00Z) \
rangeInMinutes==180 \
x-rh-swatch-psk:placeholder
```
## swatch-metrics test using ROSA

find an org reporting ROSA data in stage openshift observatorium: 
```promql
group(min_over_time(ocm_subscription{product='moa-hostedcontrolplane', external_organization != '', billing_model='marketplace'}[1h])) by (external_organization)
```

```bash
EVENT_SOURCE=prometheus PROM_URL="http://10.0.151.243:80/api/v1" ./gradlew :swatch-metrics:quarkusDev
```

```bash
http POST :8000/api/swatch-metrics/v1/internal/metering/rosa \
orgId==$ORG_ID \
endDate==$(date -d '-2 hours' --utc +%Y-%m-%dT%H:00:00Z) \
x-rh-swatch-psk:placeholder
```

Check service-instance-ingress topic for events.  We're looking to verify that messages now include hardware type and a cloud provider
```json
  "hardware_type": "Cloud",
  "cloud_provider": "AWS",
```

http://localhost:3030/#/cluster/default/topic/n/platform.rhsm-subscriptions.servietce-instance-ingress/data/rawdata

# Part 2 - Verify snapshot & billable remittance reconciles appropriately with pre-existing data

We want to make sure that usages reconcile correctly for instances that were previously being defaulted to PHYSICAL during an hourly tally.

See attached [test_helpers.zip](https://github.com/user-attachments/files/15964480/test_helpers.zip) file for helper scripts being referred to in these steps.

### On main branch

```bash
EVENT_SOURCE=prometheus PROM_URL="http://10.0.151.243:80/api/v1" ./gradlew :swatch-metrics:quarkusDev
```

- Create Events for a ROSA instance that does NOT include the `hardware_type` or `cloud_provider` attributes.  You can do this one of two ways with the helper script...
	- `sh produce_rosa_physical_message.sh` will put a message on the service-instance-ingress topic
	- `sh create_rosa_event.sh physical` this will directly insert it into the swatch events table.  it's the same instance as the kafka message version (i actually pulled this right from my database after i did the kafka message as a test and i was consumed by swatch-tally.  this direct database insert has less moving parts, but putting a message on the kafka topic would be the test more representative of how it actually works)
- Run an hourly tally
	- `sh hourly_tally.sh`
- Inspect the snapshots/measurements and billable usage
	- `sh snapshots_sql.sh`
	- `sh monthly_totals_sql.sh`
	- `sh billable_remittance_sql.sh`

### Switch branches
* Restart swatch-metrics

```bash
EVENT_SOURCE=prometheus PROM_URL="http://10.0.151.243:80/api/v1" ./gradlew :swatch-metrics:quarkusDev
```

* create a new Event (new timestamp) for that instance, but this time include the hardware type & cloud provider.  This is going to represent what the next hourly metric gathering is going to do after the code changes.
	* Again, two methods to do this...direct db insert is more convenient:
		* kafka message: `sh create_rosa_event.sh cloud`
		* direct db insert: `sh produce_rosa_cloud_message.sh`
- Run an hourly tally again
	- `sh hourly_tally.sh`
- Inspect the snapshots/measurements and billable usage again
	- `sh snapshots_sql.sh`
	- `sh monthly_totals_sql.sh`
	- `sh billable_remittance_sql.sh`

We're expecting to see measurements and billable usages for both PHYSICAL and AWS, but the totals should sum up properly (ie, not double count the old PHYSICAL ones as part of the new AWS one)

### CODE REVIEW

**Comment by san7ket** [comment]
Looks like creating two events from two separate sources for same host and same timestamp results in values for both metrics to be added up 
In short, 
Cost-Management sends value **2** for host **ABC** for timestamp - 10:00 AM - 11 AM
rhelmeter sends value **3** for host **ABC** for timestamp - 10:00 AM - 11 AM

System table reports 1 Host ABC with value **5**
Remittance results value **5** 


Steps:
- Did a setup for promethus in EE to test this logic
- After setup sent metrics to promethus
```
In [41]: push_metrics_to_prometheus(product_id=product_id,billing_account_id="bill123",org_id=app.user.identity.org_id, account_numb
    ...: er=app.user.identity.account_number,hours=1,display_name="host1234")
2024-06-21 13:10:58.728 [    INFO] [root] Generating mock data for cluster_id=cluster_6487554649,product=rhel-for-x86-els-payg,metrics=['vCPUs']
Rsync completed successfully.
> /iqe_venv/lib/python3.11/site-packages/iqe_rhsm_subscriptions/smqe_tools/telemeter.py(202)push_metrics_to_prometheus()
-> logging.info("Importing mock data")
(Pdb) c
2024-06-21 13:11:01.250 [    INFO] [root] Importing mock data
Out[41]: 'cluster_6487554649'
```

- Did perform metering to get events in swatch 
```
In [43]: app.rhsm_subscriptions.perform_metering(product_id=product_id)
2024-06-21 13:11:37.806 [    INFO] [root] POST request response url: http://swatch-metrics-rhel-service:8000/api/swatch-metrics/v1/internal/metering/rhel-for-x86-els-payg?orgId=17790794&endDate=2024-06-21T15:00:00Z&rangeInMinutes=240, status_code: 204
2024-06-21 13:11:37.806 [    INFO] [root] Not valid json output. Returning plain text message.
2024-06-21 13:11:37.806 [    INFO] [root] from 2024-06-21T10:00:00Z to 2024-06-21T15:00:00Z.
2024-06-21 13:11:37.806 [    INFO] [root] Waiting for openshift metering completion...

In [44]: e = app.rhsm_subscriptions.fetch_metering_events(hours=2)
{'event_source': 'rhelemeter',
 'event_type': 'snapshot_rhel-for-x86-els-payg_vcpus',
 'org_id': '17790794',
 'instance_id': 'host1234',
 'metering_batch_id': '93bd16f5-8499-4cdc-8df0-261ee1a1cdf5',
 'event_id': '25af5087-7fb1-4877-9486-fa46472cf299',
 'service_type': 'RHEL System',
 'timestamp': '2024-06-21T12:00:00Z',
 'record_date': '2024-06-21T13:11:37.831535416Z',
 'expiration': '2024-06-21T13:00:00Z',
 'display_name': 'host1234',
 'measurements': [{'value': 48.57142857142857, 'metric_id': 'vCPUs'}],
 'cloud_provider': 'AWS',
 'hardware_type': 'Cloud',
 'product_ids': ['204', '69'],
 'sla': 'Premium',
 'billing_provider': 'aws',
 'billing_account_id': 'bill123',
 'product_tag': ['rhel-for-x86-els-payg'],
 'conversion': True}
```

- Sync tally and get remittance 
```
In [57]: app.rhsm_subscriptions.get_instances_report(product_id=product_id)
2024-06-21 13:24:37.774 [    INFO] [iqe.base.rest_client] REST: METHOD=GET, request_id=None, params=[('limit', 100), ('offset', 0)]
Out[57]: 
[{'id': '85ecfc3b-7f53-453b-a6c5-04822fd916fd',
  'instance_id': 'host1234',
  'display_name': 'host1234',
  'billing_provider': 'aws',
  'billing_account_id': 'bill123',
  'measurements': [48.57142857142857],
  'last_seen': datetime.datetime(2024, 6, 21, 12, 0, tzinfo=tzlocal()),
  'last_applied_event_record_date': datetime.datetime(2024, 6, 21, 13, 11, 37, 831535, tzinfo=tzlocal()),
  'number_of_guests': 0,
  '_labeled_measurements': {'vCPUs': 48.57142857142857}}]

```
Remittance
```
In [56]: app.rhsm_subscriptions.get_account_remittance(product_id=product_id)
2024-06-21 13:24:27.746 [    INFO] [root] GET request response url: http://swatch-billable-usage-service:8000/api/swatch-billable-usage/internal/remittance/accountRemittances?productId=rhel-for-x86-els-payg&orgId=17790794, status_code: 200
2024-06-21 13:24:27.746 [    INFO] [root] Response: [
    {
        "accumulationPeriod": "2024-06",
        "billingAccountId": "bill123",
        "billingProvider": "aws",
        "metricId": "vCPUs",
        "orgId": "17790794",
        "productId": "rhel-for-x86-els-payg",
        "remittanceDate": "2024-06-21T13:23:36.722389Z",
        "remittanceStatus": "pending",
        "remittedValue": 49.0
    }
]
```

- Create a event for the same host for cost-management source
```
In [59]: data
Out[59]: 
{'vcpus': 23,
 'billing_provider': 'aws',
 'billing_account_id': 'bill123',
 'hours': 1,
 'event_source': 'cost-management'}

In [60]: app.rhsm_subscriptions.create_metering_event(product_id=product_id,name="host1234", **data)
2024-06-21 13:25:07.994 [    INFO] [root] [{'event_source': 'cost-management', 'event_type': 'snapshot_vCPUs', 'org_id': '17790794', 'product_tag': ['rhel-for-x86-els-payg'], 'instance_id': 'host1234', 'timestamp': '2024-06-21T12:00:00Z', 'expiration': '2024-06-21T13:00:00Z', 'display_name': 'automation__cluster_host1234', 'measurements': [{'value': 23, 'uom': 'vCPUs', 'metric_id': 'vCPUs'}], 'sla': 'Premium', 'service_type': 'RHEL System', 'product_ids': ['204'], 'usage': 'Production', 'cloud_provider': 'AWS', 'hardware_type': 'Cloud', 'billing_provider': 'aws', 'billing_account_id': 'bill123', 'conversion': True}]
```

- Sync tally , check tally and remittance
```
In [62]: app.rhsm_subscriptions.get_instances_report(product_id=product_id)
2024-06-21 13:25:39.872 [    INFO] [iqe.base.rest_client] REST: METHOD=GET, request_id=None, params=[('limit', 100), ('offset', 0)]
Out[62]: 
[{'id': '85ecfc3b-7f53-453b-a6c5-04822fd916fd',
  'instance_id': 'host1234',
  'display_name': 'automation__cluster_host1234',
  'billing_provider': 'aws',
  'billing_account_id': 'bill123',
  'measurements': [71.57142857142857],
  'last_seen': datetime.datetime(2024, 6, 21, 12, 0, tzinfo=tzlocal()),
  'last_applied_event_record_date': datetime.datetime(2024, 6, 21, 13, 25, 8, 48664, tzinfo=tzlocal()),
  'number_of_guests': 0,
  '_labeled_measurements': {'vCPUs': 71.57142857142857}}]

In [63]: app.rhsm_subscriptions.get_account_remittance(product_id=product_id)
2024-06-21 13:25:52.282 [    INFO] [root] GET request response url: http://swatch-billable-usage-service:8000/api/swatch-billable-usage/internal/remittance/accountRemittances?productId=rhel-for-x86-els-payg&orgId=17790794, status_code: 200
2024-06-21 13:25:52.282 [    INFO] [root] Response: [
    {
        "accumulationPeriod": "2024-06",
        "billingAccountId": "bill123",
        "billingProvider": "aws",
        "metricId": "vCPUs",
        "orgId": "17790794",
        "productId": "rhel-for-x86-els-payg",
        "remittanceDate": "2024-06-21T13:25:15.418412Z",
        "remittanceStatus": "pending",
        "remittedValue": 72.0
    }
]
```

**Comment by san7ket** [comment]
Everything on this, looks good. @lindseyburnett let me know, if we are going to add this logic to internal events api, if not then this is good to merge

**Review by mstead — APPROVED** [review]
Looks good to me and works as expected.

**Comment by mstead** [comment]
Marking this as hold until I can fully test the result of new event conflict resolution work against this PR.

**Comment by lindseyburnett** [comment]
@san7ket not going to update the internal events api as part of this.  If that change is something you guys still need for automation testing, please put in a new card for the request to go through refinement.

**Pull request merged**
